### ISSUE TITLE
How to handle off-scale density values on the Density intro screen

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/density-buoyancy-common#1]
It's possible to set a custom material so that the density goes past 10 kg/L.

**Comment by DianaTavares** [comment]
The custom mass range is restringed to 0.1 to 10 kg. 
![Screen Shot 2019-10-30 at 10 01 58 AM](https://user-images.githubusercontent.com/26031501/67875855-93ce8a80-fafc-11e9-9d7a-3f5c87495e3d.png)

**Comment by jonathanolson** [comment]
Understood, thanks!
