### ISSUE TITLE
Duplicated constants in Cone

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#10]
During https://github.com/phetsims/density-buoyancy-common/issues/5, I noticed some duplicated magic numbers in Cone:

```js
 /**
   * Returns the radius from a general size scale
   * @public
   * @override
   *
   * @param {number} widthRatio
   * @returns {number}
   */
  static getRadiusFromRatio( widthRatio ) {
    return 0.01 + widthRatio * 0.09;
  }

  /**
   * Returns the height from a general size scale
   * @public
   * @override
   *
   * @param {number} heightRatio
   * @returns {number}
   */
  static getHeightFromRatio( heightRatio ) {
    return 2 * ( 0.01 + heightRatio * 0.09 );
  }
```

I also see a lot of 0.75 and 0.25 in this file.  Should some of these constants be factored out and described?

**Comment by jonathanolson** [comment]
The getRadiusFromRatio and getHeightFromRatio are not tied together, just happen to be similar. Otherwise I factored out constants. Can you review?

**Comment by samreid** [comment]
Looks good, thanks!  Closing.
