### ISSUE TITLE
Factor out all usages of a density readout accordion box with `DensityReadoutNode`

### ISSUE THREAD

**Issue by zepumph** [phetsims/density-buoyancy-common#103]
There are at least 4 usages of this kind of component, but they should all be using DensityReadoutNode. Also noting https://github.com/phetsims/buoyancy/issues/96 wants one of these on the buoyancy intro screen too.

**Comment by AgustinVallejo** [comment]
@zepumph I had to comment out a couple of assertions you had added since currently, the custom Explore Screen View options are provided as the whole 2 element list, even when only a single block is displayed. At first I thought it shouldn't be a problem because if the options list is bigger than the bodies, some will just remain unused and cause no harm. But we should discuss.

**Comment by AgustinVallejo** [comment]
Missing: rename DisplayOptionsNode -> BuoyancyDisplayOptionsNode

**Comment by zepumph** [comment]
* Looks like  there strings aren't being used. I'm unsure about how to handle these. We need to be very careful to make sure that the current published version of Density isn't using these (I don't think those are).
  * densityReadoutPattern
  * densityReadoutDecimetersCubedPattern
  * densityReadoutUnitlessPattern

This patch helped me find these, then when you build both density and buoyancy and take a union of the unused strings reported.

<details>

```diff
Subject: [PATCH] update important doc about Node.changedInstanceEmitter, https://github.com/phetsims/scenery/issues/1615
---
Index: js/grunt/buildRunnable.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/grunt/buildRunnable.js b/js/grunt/buildRunnable.js
--- a/js/grunt/buildRunnable.js	(revision 49365d759571523891e8143e8aa5811c93dbd3db)
+++ b/js/grunt/buildRunnable.js	(date 1710443779818)
@@ -149,6 +149,7 @@
 
   // After our string map is constructed, report which of the translatable strings are unused.
   reportUnusedStrings( repo, packageObject.phet.requirejsNamespace, stringMap[ ChipperConstants.FALLBACK_LOCALE ] );
+  reportUnusedStrings( 'density-buoyancy-common', 'DENSITY_BUOYANCY_COMMON', stringMap[ ChipperConstants.FALLBACK_LOCALE ] );
 
   // If we have NO strings for a given locale that we want, we'll need to fill it in with all English strings, see
   // https://github.com/phetsims/perennial/issues/83

**Comment by AgustinVallejo** [comment]
Closing this issue and adding the remaining items to the common issue https://github.com/phetsims/density-buoyancy-common/issues/105
