### ISSUE TITLE
Final items for ReadoutAccordionBox

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/density-buoyancy-common#105]
Things missing for this to be ready. This component addresses the common behavior of DensityAccordionBox and SubmergedAccordionBox

- [x] #106
- [x] Align the text content to the left. @DianaTavares wants the items aligned with respect to the colon ":", so label expands to the left while numbers expand to the right.
- [x] Add functionality for passing in a  MaxWidthProperty
- [x] Renaming DisplayOptionsNode -> BuoyancyDisplayOptionsNode
- [x] As described [here](https://github.com/phetsims/density-buoyancy-common/issues/103#issuecomment-1998241815) remove unused strings

**Comment by zepumph** [comment]
Noting that there are still a number of items specific to the Intro screen listed over in https://github.com/phetsims/buoyancy/issues/96#issuecomment-1996002214

**Comment by zepumph** [comment]
We would like to work on this together from here.

**Comment by zepumph** [comment]
@AgustinVallejo and I did enough research to feel confident about removing these three string keys:

```
densityReadoutPattern
densityReadoutDecimetersCubedPattern
densityReadoutUnitlessPattern
```

Investigation:
* No usages in babel
* No usages in https://phet.colorado.edu/sims/html/density/1.1.6/string-map.json or in phet.chipper.strings of view-source:https://phet.colorado.edu/sims/html/density/1.0.11/density_en.html.
* Looks like one was added over in https://github.com/phetsims/density-buoyancy-common/issues/103 (densityReadoutUnitlessPattern).
* The other two were added by JO, but then eventually removed in exchange for `KILOGRAMS_PER_VOLUME_PATTERN_STRING_PROPERTY`.
* Building density and buoyancy with this patch, then taking the intersection of reported unused string keys helped us find this original list.

Ideas for a script:
1. Runs a webpack build on all repos to get all used strings for all repos,
2. Cross references each with the contents of common code string files on main to determine all string keys on main that aren't used by anything on main. This is done similar to the patch over in https://github.com/phetsims/density-buoyancy-common/issues/103#issuecomment-1998241815 by calling reportUnusedStrings on common code repos. 
3. Each of those are searched for in babel/ and if any usages, then they must remain.
4. I am definitely not writing this right now, but I thought I'd mention it.

**Comment by zepumph** [comment]
I can take the remaining two items here, @AgustinVallejo please reassign yourself if you would prefer we collaborate instead of me taking the lead.

**Comment by zepumph** [comment]
> [ ] Align the text content to the left. @DianaTavares wants the items aligned with respect to the colon ":", so label expands to the left while numbers expand to the right.

@AgustinVallejo will take a look at using layoutOptions for the RichTexts inside setReadoutItems()

**Comment by zepumph** [comment]
ReadoutListAccordionBox now supports a content max width Property, committed over in https://github.com/phetsims/buoyancy/issues/96. Over to @AgustinVallejo for the final layout piece. Let me know if you run into trouble.

**Comment by AgustinVallejo** [comment]
Closing this one as well, used alignBox to achieve the desired effect, byee
