### ISSUE TITLE
Add % Submerged Panel to Shapes Screen

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/density-buoyancy-common#106]
Improve the Shapes API so this component can receive MassProperties as well

**Comment by zepumph** [comment]
I think we can follow the same pattern as for other screens, but also link to when the primary/secondaryMassProperties change.

**Comment by zepumph** [comment]
This is looking really nice, 

Here is what it looks like:

![image](https://github.com/phetsims/density-buoyancy-common/assets/6856943/fc9b672b-d087-4c54-9adf-ad8e201739e1)


Here was the mockup from back in https://github.com/phetsims/buoyancy/issues/112:

![image](https://github.com/phetsims/density-buoyancy-common/assets/6856943/4b876baf-3876-4897-ba0c-a60fa21561b1)


Some thoughts:
* we probably don't want "Block" in the submerged readout, but maybe "Shape"?
* Can we update the formatting like we have on other "two-block" mode-supported screens?

**Comment by AgustinVallejo** [comment]
Thanks for the thoughts! They were good thoughts I hadn't noticed. They have been addressed in the above commit, closing now :)
