### ISSUE TITLE
Elaborate on `* @param {Engine} engine`

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#11]
As part of #5, I saw that `* @param {Engine} engine` appears in many places. Since it is very general terminology, it may be best to explain in the JS doc that it is from the matter physics engine, like:

> * @param {Engine} engine - physics engine from the third party library matter.js

**Comment by samreid** [comment]
My mistake, I just noticed that Engine is our own term.  Perhaps a more specific name would help?  Like DensityBuoyancyCommonPhysicsEngine?  I'm open to other suggestions.

**Comment by jonathanolson** [comment]
I could imagine this being generalized (I would, if I need a physics engine in another sim). Thoughts on `PhysicsEngine`?

**Comment by samreid** [comment]
Leaving Density/Buoyancy out is fine with me, do you think it should indicate "2D" at all?

**Comment by jonathanolson** [comment]
`PhysicsEngine2D`? I guess it would be possible to have 3d engines. Would we also use `P2Engine2D`?

**Comment by samreid** [comment]
`PhysicsEngine` sounds reasonable to me.  We can rename later if something comes up.

**Comment by jonathanolson** [comment]
Renamed above, does this look good to you?

**Comment by samreid** [comment]
Looks good, thanks!  Closing.
