### ISSUE TITLE
Highlight colors for custom thumbs

### ISSUE THREAD

**Issue by zepumph** [phetsims/density-buoyancy-common#110]
From https://github.com/phetsims/density-buoyancy-common/issues/107, we want highlight colors for the blue and red slider thumbs:

<img width="385" alt="image" src="https://github.com/phetsims/density-buoyancy-common/assets/6856943/0089a2c3-cfc2-4671-8a77-e440fefe0d43">

**Comment by AgustinVallejo** [comment]
Reminder to also:
- [x] Also highlight the scale height slider!
- [x] Change the other slider colors to default

**Comment by AgustinVallejo** [comment]
Added default highlighting and color, but would like @zepumph to review the above commit. As I'm not sure if the way I'm using the default colors is appropriate, or if there's a better way like importing those from SliderThumb.ts

Edit: I'm also a bit tangled in how to lighten a TPaint, so I think a quick pairing on this could be benefitial :)

**Comment by AgustinVallejo** [comment]
Bye bye
