### ISSUE TITLE
MassTagView to use "decorate()" pattern. 

### ISSUE THREAD

**Issue by zepumph** [phetsims/density-buoyancy-common#112]
From https://github.com/phetsims/buoyancy/issues/117. We need to do this (a) because it is a better pattern, and (b) because we have layering trouble. We need the depth lines behind the mass tag.

**Comment by zepumph** [comment]
We accomplished what we set out to do. Now the depth lines are behind the tag: 

<img width="488" alt="image" src="https://github.com/phetsims/density-buoyancy-common/assets/6856943/7a2fc300-f774-42a4-993e-1ba03036b800">

**Comment by AgustinVallejo** [comment]
![image](https://github.com/phetsims/density-buoyancy-common/assets/37052186/6b562ccd-0f96-4d7f-b633-4eb34b95ecfc)
This might be a by-product of these changes. The smaller 'A' label

**Comment by zepumph** [comment]
Alright. The above is fixed, and TODOs are complete. @samreid, can you give this one a spot check?

**Comment by samreid** [comment]
Looks good, nice work, closing.
