### ISSUE TITLE
Tweaker buttons needed for ScaleHeightSlider

### ISSUE THREAD

**Issue by zepumph** [phetsims/density-buoyancy-common#117]
From design meeting today, @DianaTavares recommends tweaker buttons on the ScaleHeightSlider for reproducibility. 

See https://github.com/phetsims/density-buoyancy-common/issues/107 for initial implementation.

**Comment by zepumph** [comment]
Taking a look now.

**Comment by zepumph** [comment]
Tweaker buttons have been added, but now there is an overlap:

@DianaTavares, how would you like to proceed? 

<img width="746" alt="image" src="https://github.com/phetsims/density-buoyancy-common/assets/6856943/67140e2d-2d9f-4c52-ae26-271492903cc7">

**Comment by DianaTavares** [comment]
What if you move the left panels just some pixels to the left? Enough to not cover the %submered panel, and leave some brown space between the buttons and the panel. I see that they overlap just for a small quantity. 

Also, the buttons are giving big jumps. It is not easy to use them to make that the block submerge only 20% for example.
