### ISSUE TITLE
PhET-iO State doesn't support layout of some decoration layers

### ISSUE THREAD

**Issue by zepumph** [phetsims/density-buoyancy-common#118]
From loading a standard wrapper from Studio, see the readouts at 0,0 in screen view coords

![image](https://github.com/phetsims/density-buoyancy-common/assets/6856943/2d851b65-52e6-4a64-9a1d-c71c73694f81)

**Comment by zepumph** [comment]
Maybe related to https://github.com/phetsims/density-buoyancy-common/issues/81

**Comment by zepumph** [comment]
We probably don't want the positions to be stateful, but we do want to re-layout the decoration layer after state setting to realign to the new screen bounds of the new sim's instance.

**Comment by samreid** [comment]
I added a commit that addresses this: Studio => Test now comes up like so:

<img width="1990" alt="image" src="https://github.com/phetsims/density-buoyancy-common/assets/679486/87db6609-1237-4eb1-a925-fc859bbe782d">

I originally added similar code to CuboidView (for the lines) and MassView (for the tags) but apparently some other code is managing that correctly already.  So I decided to ask about it.

@zepumph can you please review?

**Comment by zepumph** [comment]
Looks great thanks.
