### ISSUE TITLE
Block has a phantom draggable spot way outside of its bounds

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/density-buoyancy-common#119]
This is tricky to replicate, but apparently in every sceen of Buoyancy (I wasn't able to replicate in Density) all the draggable masses have a region like half a pool to the right where some pixels trigger the cursor to change to a pointer, and it's possible to drag said masses from that phantom spot.

![image](https://github.com/phetsims/density-buoyancy-common/assets/37052186/28764458-771d-4ac9-bfa8-802e5719fbaa)

The image is to get a vague notion of where the phenomenon is ocurring for the block in its default position for the Applications Boat Scene. But it happens in all screens as far as I could tell. You also have to find the right pixels, it's tricky.

**Comment by samreid** [comment]
I am no longer able to reproduce the problem and believe @AgustinVallejo and I may have solved it in https://github.com/phetsims/buoyancy/issues/161
