### ISSUE TITLE
Which parts of config are required?

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#12]
During #5 I noticed this code in Cuboid.js:

```js
    config = merge( {
      body: engine.createBox( size.width, size.height ),
      shape: Shape.rect( size.minX, size.minY, size.width, size.height ),
      volume: size.width * size.height * size.depth,
      canRotate: false,

      tandem: Tandem.OPTIONAL,
      phetioType: Cuboid.CuboidIO
    }, config );

    assert && assert( !config.canRotate );
```

It was unclear which parts were optional and required.  Or if all parts are optional, maybe it should be `options`?

**Comment by jonathanolson** [comment]
I'm curious what's best here. The supertype (Mass) notes what is required. Cuboid fills out everything required EXCEPT for `material` (so do other Mass subtypes). Is there a recommended pattern I can follow here?

**Comment by samreid** [comment]
Thanks, I missed the declaration in Mass.js.  Should it assert that the required values are supplied?

**Comment by jonathanolson** [comment]
Added assertions above.

**Comment by samreid** [comment]
Looks good, thanks!  Closing.
