### ISSUE TITLE
How should we manage directories for the screens?

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#125]
density-buoyancy-common has an unconventional directory structure due to the way it supports 3 simulations.

```
js/
  buoyancy/
  buoyancy-basics/
  common/
  density/
```

Note that buoyancy, buoyancy-basics and density are sims, not screens. I think this directory structure is good, but I also expected to see per-screen directories for each of the sims.  Has this been discussed before?

**Comment by zepumph** [comment]
We haven't discuss it yet. I have felt like things are pretty crowded these days, but really the only subdirectory that needs this is `buoyancy`. Should we just start there and see if it makes sense for the other directories later?

**Comment by zepumph** [comment]
Subdirectories for these files don't seem very valuable:

```
density
	model
		DensityCompareModel.ts
		DensityIntroModel.ts
		DensityMysteryModel.ts
	view
		DensityCompareScreenView.ts
		DensityIntroScreenView.ts
		DensityMysteryScreenView.ts
		DensityNumberLineNode.ts
		DensityTableNode.ts
		densityBuoyancyCommon.ts
		DensityBuoyancyCommonStrings.ts
```

**Comment by zepumph** [comment]
@samreid and I noticed that CCK common/ could really use some screen specific directories, so I think in general it would be good to think about this, but for DBC it isn't quite as important. I could see applying this to some classes in the buoyancy/ repo, but we don't think this needs to applied rigidly for these "mono common sim-suite repo" cases.

**Comment by samreid** [comment]
Sounds good, and it will be good to have this paper trail for when it comes up in the code review. Closing.

**Comment by samreid** [comment]
Upon reflection, I wonder if a screen-centric organization will help my understanding and the maintainability of the project, should we try it? Something like:
```
js/
  buoyancy-intro
  buoyancy-explore 
  buoyancy-lab
  buoyancy-shapes
  buoyancy-applications
  buoyancy-basics-compare
  buoyancy-basics-explore
  density-intro
  density-compare
  density-mystery
  common
  common-buoyancy (optional directory to share code that is just related to buoyancy)
  etc
```

**Comment by samreid** [comment]
Or even subdirectories under each simulation.

> Subdirectories for these files don't seem very valuable:

Agreed, and it is not for that case. It is to help manage the complexity in Buoyancy.

**Comment by samreid** [comment]
In discussion with @AgustinVallejo, he recommended a structure like this:

<img width="477" alt="image" src="https://github.com/phetsims/density-buoyancy-common/assets/679486/e6c6435a-5eb3-4aec-ba34-16bfc01a78e2">

I will do so, thanks!

**Comment by samreid** [comment]
@AgustinVallejo volunteered to apply this heuristic throughout, thanks!

**Comment by samreid** [comment]
Looks good, thanks. Closing.
