### ISSUE TITLE
Convert Fluids Radio Button Group to a ComboBox

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#126]
While working on https://github.com/phetsims/density-buoyancy-common/issues/121 I recalled discussion about this panel turning into a combo box. Is that accurate? Is it tracked in another issue?

<img width="882" alt="image" src="https://github.com/phetsims/density-buoyancy-common/assets/679486/46cc3355-4e56-4534-875e-5b9d7249bd24">

**Comment by DianaTavares** [comment]
Yes, here: https://github.com/phetsims/density-buoyancy-common/issues/127.

Now that I was looking for the issue, this is not the right repository. @samreid feel free to close the one in Buoynacy-Basics and continue with the work here, or what is more convenient.

**Comment by samreid** [comment]
Thanks, closing as duplicate.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by samreid** [comment]
I moved the TODO to the other issue, closing.
