### ISSUE TITLE
New component: BlocksPanel

### ISSUE THREAD

**Issue by zepumph** [phetsims/density-buoyancy-common#128]
We need to bring together the implementations of the "Same X" radio button group panel.

It is in:
Buoyancy Intro
Buoyancy:Basics Compare
Density Compare

- [ ] make sure that the tandem structure is right. "blocksPanel.blocksRadioButtonGroup" for all three.

**Comment by zepumph** [comment]
Noting for @DianaTavares that this will result in adding the "Blocks" title to the Buoyancy intro screen (as done in B:B and density). This will help with consistency. Let us know if you don't like this path.

**Comment by samreid** [comment]
I started pushing to the branch `blocks-panel/density-buoyancy-common/128`

**Comment by samreid** [comment]
I'm trying out pull requests for the review.  I maintained the API compatibility with density, tested precommit hooks in all repos. Probably would have been safe to commit to main but I wanted to test drive pull requests on 2x repos. I wasn't clear on the buoyancy related API changes, probably needs a look.

**Comment by zepumph** [comment]
pull requests are merged. Closing
