### ISSUE TITLE
createMassesCallback has JSDoc indicating one parameter, but it is called with 2 parameters.

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#13]
In DensityBuoyancyModal, `createMassesCallback` has JSDoc indicating one parameter, but it is called with 2 parameters.  Similar problems for `regenerateMassesCallback` and `positionMassesCallback`

**Comment by samreid** [comment]
For instance, BuoyancyIntroModel calls:

```js
super( tandem, createMasses, () => {}, positionMasses, tandem );
```

But the 3rd arg doesn't match the JSDoc type:

```js
* @param {function(Mode):Array.<Mass>} regenerateMassesCallback - Regenerate masses (when given a mode)
```

**Comment by jonathanolson** [comment]
JSDoc was definitely wrong, should be fixed up.

**Comment by samreid** [comment]
Looks good, thanks!  Closing.
