### ISSUE TITLE
Should all Scales be non-interactive?

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/density-buoyancy-common#130]
Opening to decide if scales should be static on all sims. Noticed that non-interactive scales are immune to flickering (https://github.com/phetsims/buoyancy/issues/64). Also, if we don't allow scale dragging, the uneven distribution of weights (- https://github.com/phetsims/buoyancy/issues/132) won't be replicable. 

My opinion is that dragging weights does not fulfill any pedagogical goal. So I vote for keeping them in place.

Assigning to @DianaTavares for the final say.

**Comment by zepumph** [comment]
It doesn't seem like https://github.com/phetsims/buoyancy/issues/64 is important enough to trigger such a design change. I'm excited to discuss!

**Comment by samreid** [comment]
@kathy-phet said:

> If they are infrequent bugs and don't crash, I think moving underwater scale is pedagogically important, so could deal with a few odd corner cases.

Also in https://github.com/phetsims/buoyancy/issues/64#issuecomment-2121526232 there is a hybrid proposal where scales become non-interactive until the user clicks on them.  There are also other ideas how to deal with the model fluctuations.

**Comment by AgustinVallejo** [comment]
Closing this because of the above comment. Scales will remain interactive
