### ISSUE TITLE
Changes in the Block's control panel

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/density-buoyancy-common#135]
This is the new panel:
![image](https://github.com/phetsims/density-buoyancy-common/assets/26031501/5b8c0319-9c35-4fc1-938a-c791f39058b0)

- [ ] Where the mass slide is substituted by a density slider. When the user selects a material, the density slider moves to take the value of the density of that material. If the user moves the density slider, the material changes to "custom".

- [x] This change also requires that the mass value need to be selected by default. 

- [ ] the range of values for density is 0.1 kg/L to 15 kg/L

- [ ] When the user changes material, the Volume conserves it value, and the density slider changes to match the density of the object. 

Probably we need to make some changes to the Density readout, by I need first experiment a little. Then please make this change for now in the explore screen of Buoyancy:Basics, to 1) calculate the time that will be needed to implement this change in all the screens of Buoyancy that has this control (this change affect 3 screens), and 2) I can design the density panel.

**Comment by AgustinVallejo** [comment]
Will start implementing in the 135 branch

**Comment by AgustinVallejo** [comment]
>  This change also requires that the mass value need to be selected by default.

@DianaTavares  This is done. I assume is doesn't mean to hide the checkbox, only have it selected when sim initializes, right?

**Comment by samreid** [comment]
@kathy-phet said:

> Hey team, I have been thinking about the pedagogical moves I did when teaching with the buoyancy sim and realized I used the volume and mass sliders to powerful effect, so before changing out all the sliders I would like to talk with Diana more.
So please hold off on that change.

**Comment by DianaTavares** [comment]
This change will be applied only to B:B, Explore screen, and We better create this issue: #150. Closing this issue.
