### ISSUE TITLE
Use the default sliders when there's no mass constraints

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/density-buoyancy-common#138]

**Comment by samreid** [comment]
Confirming the design before starting on this. How should the volume slider look in this case?

<img width="1591" alt="image" src="https://github.com/phetsims/density-buoyancy-common/assets/679486/c4541463-3c35-4dc1-a07a-90bd4ec7160f">

**Comment by DianaTavares** [comment]
this change is not applied to density blocks' controls. But this issue needs to be solved first #135 to analyze the changes in these controls in Buoynacy.

**Comment by DianaTavares** [comment]
We discussed some sliders in the last Desing meeting, and I opened an issue related to the sliders that need changes. We an close this issue.
