### ISSUE TITLE
Have the pool scale also be draggable with the pointer

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/density-buoyancy-common#139]

**Comment by AgustinVallejo** [comment]
@samreid and I worked to implement this one. Please review and close @DianaTavares

**Comment by DianaTavares** [comment]
it is perfect! But I didn't see it in Buoyancy (lab). Sometimes Phet test takes a lot of time to actualize in my side. but It is strange that I can see it in one sim (intro), and not in the other?

**Comment by DianaTavares** [comment]
it is working now in both sims
