### ISSUE TITLE
TODO: It would be helpful in CompareBlockSetModel if this could just take a Property

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#141]
In https://github.com/phetsims/density-buoyancy-common/commit/4a6c3c766b995ad0310d2f42ee738a721d2c4deb @zepumph wrote:

```ts
    // TODO: It would be helpful in CompareBlockSetModel if this could just take a Property, https://github.com/phetsims/density-buoyancy-common/issues/95
    this.materialProperty = new Property( options.material, combineOptions<PropertyOptions<Material>>( {
```

It is unclear what that means, please clarify.

**Comment by zepumph** [comment]
The TODO is recognizing this duplicated and sloppy logic:

https://github.com/phetsims/density-buoyancy-common/blob/c792d4b0cf78c9c91ee901680eda0e0e219d32f4/js/common/model/CompareBlockSetModel.ts#L154

https://github.com/phetsims/density-buoyancy-common/blob/c792d4b0cf78c9c91ee901680eda0e0e219d32f4/js/common/model/CompareBlockSetModel.ts#L159-L161

This happens for each block set (3). 

If we didn't have PhET-iO concerns, I think a nice API would be allowing Mass to have a material provided via a Property, but this is what the instrumentation of Mass.materialProperty looks like:

https://github.com/phetsims/density-buoyancy-common/blob/e9d3d28b164d9a9e4c7ecb00c4114788f279d391/js/common/model/Mass.ts#L312-L318

It isn't worth figuring out consistency in that department just for saving 6 lines of code. Closing
