### ISSUE TITLE
Review fonts and vertical white spacing 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/density-buoyancy-common#147]
I feel that not all the fonts have the same size (titles and items), and also the separation of the items is not the same in all panels. For example, the next to planes that are part of the "Compare Screen": 

![image](https://github.com/phetsims/density-buoyancy-common/assets/26031501/a622b4b0-e661-44e8-9998-dbb2f3a4e294)
![image](https://github.com/phetsims/density-buoyancy-common/assets/26031501/c1d6961f-d5a3-47cd-8602-847707b04628)

Please review and homogenize.
See if it is related to maxWidth.

**Comment by samreid** [comment]
In the first screen of buoyancy, I use the same word everywhere with ?stringTest=mnemonic, then copied into photoshop so I could compare sizes. It looks like title sizes are the same and contents sizes are the same with the exception of the aqua radio button labels being too big. I saw in the code that most items are font size 14 but the radio button size was 16, so I will reduce it

<img width="1808" alt="image" src="https://github.com/phetsims/density-buoyancy-common/assets/679486/d525934f-218c-45dd-941d-24f434693fae">

**Comment by samreid** [comment]
In the commit, I reduced the radio button font size from 16 to 14 to match the other controls. This shows an overlay copied from the bottom left to the top right, to see that they now match:

<img width="243" alt="image" src="https://github.com/phetsims/density-buoyancy-common/assets/679486/a3354222-61a4-42e3-aee6-bab78b35c3ba">

**Comment by samreid** [comment]
I observed that the display panel and blocks panel radio buttons both declare the same spacing of 8 but the blocks panel radio buttons are more spaced out, perhaps because the dimension of the radio button dots is different. So I adjusted the spacing to compensate:

<img width="148" alt="image" src="https://github.com/phetsims/density-buoyancy-common/assets/679486/85968215-0300-43de-9104-51774cc8c347">

**Comment by samreid** [comment]
@DianaTavares can you please check through and see if these changes are good, and see if there are more adjustments to make? To compare string measurements, you can put ?stringTest=hello so that words can be more easily compared.

**Comment by DianaTavares** [comment]
It looks perfect, thanks!!
