### ISSUE TITLE
Changes in the Slider for the scale under the water.

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/density-buoyancy-common#148]
- [x] The scale under the water in all screens needs to be larger to allow the scale goes outside the fluid. 
Slider scale will be able to come out of the water, and will no longer be volumeless. So you can see that it is the same as the left scale, which is fully out of the water. Make sure there is enough space for a 10L block. Make sure this does not disrupt Lab => fluid displaced. Fluid displaced is just affected by the block, not for the scale going in or out the fluid. 

- [x] change all the scales under the fluid in all screens to this “slider” version. If is not space, move the pool to the left, what is needed to fit the slider. 
The best is to have the pool in the same position on all screens in Buoyancy, (B:B is ok the way it is, already all screens have the scale under the water with this control) the only screen in Buoyancy that can have a different position for the Pool is Lab because it also has important panels in the left size.

**Comment by samreid** [comment]
> The scale under the water in all screens needs to be larger to allow the scale goes outside the fluid.

Does this mean the scale will remain the same size, but the slider will be taller vertically so the scale can be lifted higher?

**Comment by zepumph** [comment]
From notes in https://github.com/phetsims/density-buoyancy-common/issues/152. It may be easiest for layout to change the slider thumb width instead of moving the camera view. Let's ask @DianaTavares.

**Comment by zepumph** [comment]
@DianaTavares liked the idea of trying to make the thumb smaller as long as it still looks like the precision slider thumb.

**Comment by zepumph** [comment]
I have some questions about the max height of the scale if it can come out of the water. 

>Make sure there is enough space for a 10L block.

1. Does this mean that if you submerge the 10L block, then the level should be just under the scale? I'm not sure exactly what the use case is, but to me a reason to remove the scale from the pool is to remove it from the system, in which you'd want this situation to not have a scale partially out of the water. Does the max height need to be high enough that it isn't part of this case? 

<img width="1082" alt="image" src="https://github.com/phetsims/density-buoyancy-common/assets/6856943/e5bbe3a5-8061-452b-bd1b-62e214e748dd">

2. Or perhaps the quote above just meant that in this case, the scale is entirely out of the water:

![image](https://github.com/phetsims/density-buoyancy-common/assets/6856943/fa8bb7b5-555e-45aa-8827-434bba6abaed)

**Comment by samreid** [comment]
My understanding from these discussions is that the scale must be able to fully rise out of the water even if the maximum volume of other large objects are fully submerged.

UPDATE: But maybe it is enough to rise above the level of only one large submerged thing, since the other object would be on the scale?

**Comment by samreid** [comment]
Some recommendations for this issue:

* Rename SlidableScale => PoolScale
* Move these options into PoolScale's constructor:

```ts
      displayType: DisplayType.NEWTONS,
      canMove: false, // No input listeners, but the PoolScaleHeightControl can still move it
      inputEnabledPropertyOptions: {
        phetioReadOnly: true
      }
```

* Make `tandem` a required constructor parameter.

**Comment by AgustinVallejo** [comment]
Noting this issue should be addressed when changing the tandem, see https://github.com/phetsims/buoyancy/issues/56

**Comment by samreid** [comment]
Things are looking good and I added some changes in the branch. I observed this overlap but did not yet have time to work on it:

<img width="657" alt="image" src="https://github.com/phetsims/density-buoyancy-common/assets/679486/b5639668-e375-43fe-b4d5-02cc057580e5">

**Comment by zepumph** [comment]
The above will be handled when the intro screen is replaced by the B:B compare screen.

- [x] We need to adjust the slider thumb to handle this overlap case on the lab screen:

<img width="542" alt="image" src="https://github.com/phetsims/density-buoyancy-common/assets/6856943/72f2771c-6cac-4b54-b19d-61e00f9baa2f">

**Comment by AgustinVallejo** [comment]
I reduced the slider size, but there's still some overlap, which will get us talking about unifying margin spaces... I can totally move the pool to the left in **some** screens. Most have space. But Lab doesn't seem to have plenty of space. Maybe should we try zooming out a little bit? Would it look really weird to have a screen with the things smaller? Another alternative is for the whole sim to have Lab's screen margins (really tiny).

![image](https://github.com/phetsims/density-buoyancy-common/assets/37052186/229a2487-ab37-4d1a-902b-1b261e6caef3)

@DianaTavares, thoughts? Also let me know how the new slider thumb is looking

**Comment by DianaTavares** [comment]
for explore:
* we can also reduce the margin, and then move the pool to not overlap. 

For Lab:
* This screen is tricky. The only alternative I see is reducing the "Fluid displaced" panel. Just to be careful the name still have space for translation, and the beaker that also be smaller if it is needed.

**Comment by zepumph** [comment]
This layout will be handled over in https://github.com/phetsims/density-buoyancy-common/issues/184. On hold until that issue is complete.

**Comment by AgustinVallejo** [comment]
No more overlap with the pool slider. Closing this one
