### ISSUE TITLE
Reduce the size of the arrow in the Force panel, and reduce the size of the panel 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/density-buoyancy-common#149]
This is the mockup for the panels that don't have the Vector Zoom: 

![image](https://github.com/phetsims/density-buoyancy-common/assets/26031501/4b9bdd6f-f7d7-407a-b6d8-3679e99c50d5)

for the panel that have the buttons, also move the buttons to reduce the panel size:
![image](https://github.com/phetsims/density-buoyancy-common/assets/26031501/94205242-991c-4fcc-8edc-4fc7eae086d7)

- [ ] Also in this panel "Vector Scale" needs to change to “Vector Zoom”.

**Comment by samreid** [comment]
OK I changed the vector scale => vector zoom, and reduced the arrow size (and slightly reduced arrow left margin). Here is the before and after:

<img width="599" alt="image" src="https://github.com/phetsims/density-buoyancy-common/assets/679486/7127b36d-edaf-4ac0-b44e-e9402627063d">

@DianaTavares can you please review?

**Comment by DianaTavares** [comment]
Perfect!!
