### ISSUE TITLE
implementation-notes.md and model.md are empty

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#15]
From #5, I noticed that implementation-notes.md and model.md are empty.

**Comment by jonathanolson** [comment]
Added both above, let me know if this looks good?

**Comment by samreid** [comment]
The added information is very helpful.  I was expecting to see more architectural-level detail, perhaps in the direction of:

https://github.com/phetsims/natural-selection/blob/3cbd73fa5e7b7e69c6cf8d5d1dbc1270447538ce/doc/implementation-notes.md
https://github.com/phetsims/natural-selection/blob/53bcf65ab933c3804bcb7513eb33d2420316e468/doc/model.md

I'm not sure it needs to be 100% as detailed as those examples, but wouldn't a larger step in that direction be beneficial?

**Comment by jonathanolson** [comment]
Fleshed out more information on both, can you check?

**Comment by samreid** [comment]
These look great, but I have a minor grammar recommendation.  Several places use the form that can be interpreted as future, like:

> Masses and other objects will have "step"

and 

> Instead of subtyping Node, we'll subtype three.js view types

To some readers, it might sound like those are things we intend to do in the future, instead of describing how it is right now.  Aside from that everything seems good to me!

**Comment by jonathanolson** [comment]
Hopefully fixed above.

**Comment by samreid** [comment]
Looks great, thanks!  I think this issue can be closed, please reopen if there is more to do.
