### ISSUE TITLE
Changes in the Buoyancy:Basics Explore Screen

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/density-buoyancy-common#150]
Mockup:
![image](https://github.com/phetsims/density-buoyancy-common/assets/26031501/d4cf81d5-4018-45c5-9862-b6b92a941b93)

- [x] See https://github.com/phetsims/density-buoyancy-common/issues/154 for changes to the Density control

- [x] Add the “Density Comparison” Panel, to display the block's density and the fluid: 
The picture shows the panel in Comparison. In Explore, the label of each block is only A and B. 
![image](https://github.com/phetsims/density-buoyancy-common/assets/26031501/db8d3695-e52d-4de9-86a9-e82882e9c5b9)

- [x] Mass Values needs to be activated by default

**Comment by zepumph** [comment]
Oops, I got confused while working on the compare screen. Linked above and checked off.

**Comment by AgustinVallejo** [comment]
Assigning back for review

**Comment by DianaTavares** [comment]
All except for the blocks' panel is ready!!! (and it has it own issue, then I guess we can close this)

**Comment by DianaTavares** [comment]
It is not true! the "Density comparison" panel needs the fluid density:
How is now:
![image](https://github.com/phetsims/density-buoyancy-common/assets/26031501/ee832615-4ae7-4d1f-8ba6-39330304ae86)


How it should be (without the 1 in the blocks):
![image](https://github.com/phetsims/density-buoyancy-common/assets/26031501/21851918-e583-4c93-ab17-ed46ab4cd198)
