### ISSUE TITLE
Changes in Lab Screen 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/density-buoyancy-common#152]
- [x] Fluid Displaced need to be open by default 
- [x] Forces (all of them) and Forces Values needs to be active by default. 

- [x] ~moves the pool as needed~ in order to fit the scales' slider (this is in #148, but I write it here as a remainder). Remember that the Fluid displaced is only affected by the Block.

**Comment by zepumph** [comment]
>moves the pool as needed in order to fit the scales' slider 

There really isn't space to move it, instead we want to try to change the slider thumb. Let's discuss this further.

**Comment by AgustinVallejo** [comment]
This is done. Before closing, wanted to make sure: @DianaTavares is it intentional to have the mass values on by default on this screen? Also in the compare screens.

**Comment by DianaTavares** [comment]
No, the mass readout shouldn't be active by default on this screen.

 I just opened the simulation and it is not actualized:

![image](https://github.com/phetsims/density-buoyancy-common/assets/26031501/93cdc54d-8e1c-4222-81f1-fb075c63613b)

Then I am going to wait until tomorrow morning to review that all the changes were implemented.

**Comment by DianaTavares** [comment]
Perfect! this only needs to have the mass not selected as default (it is the only screen with this characteristic)

**Comment by AgustinVallejo** [comment]
Done! Please double check that all the screens have the desirable state of mass tag

**Comment by DianaTavares** [comment]
This is perfect, thanks!!
