### ISSUE TITLE
Small changes in Buoyancy Applications Screen

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/density-buoyancy-common#153]
In the Bottle scene (Applications screen)

- [x] Add an "A" Label to the bottle:
![image](https://github.com/phetsims/density-buoyancy-common/assets/26031501/ddfbbeb2-5d58-45f5-81ef-9e0cc23d30f5)

- [x] Now in the “Objects Density” panel, change `Average` for " `“A" System` put the text in red to make more clearer that is related to the Bottle system.   

In the Boat scene (Applications screen)

- [x] ~change to a regular slider~
![image](https://github.com/phetsims/density-buoyancy-common/assets/26031501/ac75356c-da24-45af-bd16-5978fbfc7842)

- [x] in the “Objects Density” panel, change `Boat Material` to `Boat Hull`
![image](https://github.com/phetsims/density-buoyancy-common/assets/26031501/362344f0-572f-43e9-beef-569a15025029)

**Comment by zepumph** [comment]
This all seems pretty straight forward, I'll pass it to @AgustinVallejo and we can adjust work load balance tomorrow.

**Comment by AgustinVallejo** [comment]
Diana approved in Slack. Closing
