### ISSUE TITLE
Change the "Density" title in the panel for "Objects Density".

### ISSUE THREAD

**Issue by zepumph** [phetsims/density-buoyancy-common#156]

**Comment by zepumph** [comment]
@DianaTavares, over in https://github.com/phetsims/density-buoyancy-common/issues/150 the desire was to call it "Density Comparison" 

When should we use "Objects Density" vs "Density Comparison" vs "Density" for all three sims?

**Comment by zepumph** [comment]
In density, the density panel should keep the same name "Density (unit)"

For the DensityReadoutAccordionBox:

In B:B we like "Density Comparison"

in Buoyancy we like "Object Density" in all screens.

**Comment by zepumph** [comment]
https://github.com/phetsims/density-buoyancy-common/issues/146

**Comment by AgustinVallejo** [comment]
> In B:B we like "Density Comparison"
> in Buoyancy we like "Object Density" in all screens.

Because of how the Compare screen is shared across B and BB, right now the Buoyancy: Compare screen says "Density Comparison", and the rest of Buoyancy says "Object Density". @DianaTavares let me know if this end state is desirable or if we should go and change B: Compare specifically

**Comment by AgustinVallejo** [comment]
Diana approved of these changes, closing
