### ISSUE TITLE
This screen will be the first in buoyancy and Buoyancy: Basics, and in both, the name of the screen is "Compare"

### ISSUE THREAD

**Issue by zepumph** [phetsims/density-buoyancy-common#157]
Buoyancy intro screen will be deleted, and we will use the B:B compare screen for both sims.

Use the Buoyancy Intro screen icon because the default materials are wood and brick.

**Comment by zepumph** [comment]
Ok. we have deleted the intro screen, and Buoyancy's first screen is now the the B:B Compare screen, renames and refactors complete too. @AgustinVallejo can you please spot check me?

**Comment by AgustinVallejo** [comment]
Seems alight to me! Thanks Michael! Closing

**Comment by AgustinVallejo** [comment]
Reopening... @zepumph should BuoyancyIntroModel and BuoyancyIntroScreenView be deleted??

**Comment by zepumph** [comment]
Awesome. Good find. Thanks
