### ISSUE TITLE
Can anything rotate?

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#16]
I noticed there is a lot of `canRotate: false`.  Can anything in density or buoyancy rotate?  Should that be mentioned? For #5

**Comment by jonathanolson** [comment]
Removed this for subtypes of Mass, no they shouldn't be able to rotate.

I did want to keep compatibility in the Engine code, in case we would want to use/refactor it out for future simulations.

**Comment by samreid** [comment]
Looks good, thanks!  Closing.
