### ISSUE TITLE
In the drop-up menus (Materials, Density, and Gravity), “Custom” option need's to be before the mystery options.

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#161]

**Comment by samreid** [comment]
Fixed above. Tested in density (no changes expected), buoyancy and buoyancy-basics (no changes expected). @zepumph or @AgustinVallejo can you please review/test? Commits are in main.

UPDATE: Also would be good for @DianaTavares to check the behavior on phettest.

**Comment by DianaTavares** [comment]
The behavior is perfect!!

**Comment by zepumph** [comment]
Working on this now

**Comment by zepumph** [comment]
Looks great thanks. I don't love duplicating the default customMaterial in all the screen views, but I don't care too much. 

@DianaTavares, can you please confirm for me that the Buoyancy Shapes screen shouldn't have custom or mystery materials for the shapes. If that is still correct for you, I think we are ready to close this issue.

**Comment by DianaTavares** [comment]
That is correct! Shapes doesn't need a custom option. Closing!!
