### ISSUE TITLE
Write model.md

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#166]

**Comment by AgustinVallejo** [comment]
Model.md is ready for review, assigning @DianaTavares

**Comment by DianaTavares** [comment]
Hi team! 

What questions should the model answer? 
[The document ](https://github.com/phetsims/density-buoyancy-common/blob/main/doc/model.md) is a description of each screen in each of the 3 sims. This is what I expected to see in a teacher tips document. 

I don't have a lot of experience with this. I expected the equations, libraries, limitations, units, etc.

I decide to review other models to compare:

- [ Kepler](https://github.com/phetsims/keplers-laws/blob/main/doc/model.md) also describes each screen, but also includes, units, trajectories, and other data. 

- [CCK-common](https://github.com/phetsims/circuit-construction-kit-common/blob/main/doc/model.md) is also a site, and @zepumph (who created the issue, not sure who wrote the model) describes something different, like the principal variables and data of the sim.

- While [ESP](https://github.com/phetsims/energy-skate-park/blob/main/doc/model.md) has equations. 

Does the model have a checklist of what to include or what questions to answer?

**Comment by AgustinVallejo** [comment]
Discussed today on standup:
- [x] Maybe base off https://github.com/phetsims/gas-properties/blob/main/doc/model.md for better reference
- [x] Include more constants and symbols. i.e. L -> m^3, how displaced volume is calculated
- [x] Describe how decimals are shown (1.11 vs 11.1)
- [x] Link common model.md in individual repos https://github.com/phetsims/density-buoyancy-common/blob/main/doc/model.md
- [x] Describe the boat logic
- [x] Describe the dynamics of the contact force: scale weirdness, dragging, etc.
- [x] How System A is calculated
- [x] Zoom factor 2x
- [x] Add mystery material density values

**Comment by AgustinVallejo** [comment]
Back to youu @DianaTavares, I addressed the discussed items. If you think it's done, feel free to close, or assign back otherwise.

**Comment by DianaTavares** [comment]
It is perfect thanks!!
