### ISSUE TITLE
Write implementation-notes.md

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#167]

**Comment by AgustinVallejo** [comment]
- [x] Mention the no-ops in the model introduced by https://github.com/phetsims/density-buoyancy-common/issues/234
- [x] Address how the Shape model is handled
- [x] MappedWrappedProperty

**Comment by AgustinVallejo** [comment]
Here's the draft:

https://o365coloradoedu-my.sharepoint.com/:w:/r/personal/agva1051_colorado_edu/_layouts/15/doc2.aspx?sourcedoc=%7Bb18ea365-ebd9-4e7e-94dd-4b5499671ed9%7D&action=editnew&wdOrigin=OUTLOOK-METAOS.FILEBROWSER.FILES-HOME

**Comment by AgustinVallejo** [comment]
Addressed all of the items I had in mind for the implementation relevant information. Feel free to review and modify as you see fit.

**Comment by samreid** [comment]
I've read through this and compared to a few other simulations. It seems in good shape and I think this issue can be closed.
