### ISSUE TITLE
performance testing and sign-off

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#169]

**Comment by samreid** [comment]
Let's discuss at standup who this issue should be assigned to. Who has an older but supported iPad?  Who has a slower but supported Chromebook? How do we decide if the performance is good enough? Who will sign off on this? Should QA be involved with this step? Should we bundle this with QA dev test 1 which is planned for iteration C2?

**Comment by samreid** [comment]
@zepumph recommends this can be done in dev test 1, putting on hold until then

**Comment by samreid** [comment]
For the QA team, please test performance on a variety of platforms, looking for performance problems. Include but do not limit testing to:

- [x] chromebook
- [x] ipad
- [x] firefox

Please test simulation behavior on all 10 screens, and make sure to explore the screens with boat/bottle/duck since they have more rendering constraints.

**Comment by Nancy-Salpepi** [comment]
This appears in the console of my Lenovo 100e Chromebook when Buoyancy loads:

![Screenshot 2024-06-17 2 38 51 PM](https://github.com/phetsims/density-buoyancy-common/assets/87318828/322dd5e5-ffba-43a6-be3d-4eaf207df5c2)

**Comment by KatieWoe** [comment]
Performance was ok

**Comment by samreid** [comment]
Sounds good, thanks. Closing.
