### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#17]
For #5, Some attributes warrant documentation.  For example, here are some I saw in Mass.js:

```js
    // @public {Property.<Vector3>}
    this.massOffsetProperty = new Property( Vector3.ZERO, {
```

Offset from what?

```js
    // @public {Matrix3}
    this.matrix = config.matrix;

    // @public {Matrix3}
    this.stepMatrix = new Matrix3();
```

How is a step matrix different from the primary matrix?

```js
    // @public {number}
    this.stepX = 0;
    this.stepBottom = 0;
    this.stepTop = 0;
```

What is a step in this context, and why do we need them for X, bottom and top?

My questions are about Mass.js, but it may be helpful to skim around other files and add documentation of this sort.

**Comment by jonathanolson** [comment]
Added better documentation for these, does it look sufficient?

**Comment by samreid** [comment]
Looks good, thanks!  Closing.
