### ISSUE TITLE
review of pointer areas

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#170]

**Comment by samreid** [comment]
@AgustinVallejo volunteered to take a look, thanks!

**Comment by AgustinVallejo** [comment]
Looked through the three sims and didn't notice any overlap. However, should these checkboxes and buttons have a bit of dilation? They seem a bit compact, whereas the rest of the UI does use a bit of spacing for touch area.

![image](https://github.com/phetsims/density-buoyancy-common/assets/37052186/d7d8244d-129a-4ac1-8fc8-9bd81993a138)

**Comment by samreid** [comment]
I recommend to dilate vertically until they are touching, and dilate horizontally to cover the icons on the right (if not too complicated)

**Comment by AgustinVallejo** [comment]
This is done
