### ISSUE TITLE
credits (add right before RC.1)

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#171]

**Comment by samreid** [comment]
@DianaTavares can you please recommend the credits for Buoyancy and Buoyancy Basics?  Density is currently written like so:

```ts
  credits: {
    leadDesign: 'Diana L\u00f3pez Tavares, Kelly Lancaster',
    softwareDevelopment: 'Jonathan Olson, Chris Malley (PixelZoom, Inc.), Sam Reid',
    team: 'Wendy Adams, Trish Loeblein, Ariel Paul, Archie Paulson, Kathy Perkins, Noah Podolefsky, Amy Rouinfar, Carl Wieman',
    qualityAssurance: 'Logan Bray, Steele Dalton, Jaron Droder, Brooklyn Lash, Emily Miller, Liam Mulhall, Devon Quispe, Jacob Romero, Nancy Salpepi, Katie Woessner',
    graphicArts: '',
    soundDesign: '',
    thanks: ''
  },
```

**Comment by DianaTavares** [comment]
```
 credits: {
    leadDesign: 'Diana L\u00f3pez Tavares, Kelly Lancaster',
    softwareDevelopment: 'Michael Kauzmann, Jonathan Olson, Sam Reid, Agustin Vallejo'
    team: 'Wendy Adams, Trish Loeblein, Chris Malley (PixelZoom, Inc.), Ariel Paul, Archie Paulson, Kathy Perkins, Noah Podolefsky, Amy Rouinfar, Carl Wieman',
    qualityAssurance: 'Jaron Droder, Nancy Salpepi, Katie Woessner',
    graphicArts: '',
    soundDesign: '',
    thanks: ''
  },
```

Remember to add the Agustín, the accent!

**Comment by samreid** [comment]
Should the credits for density also be changed? If so, how? Should it use the same as in the preceding comment?

**Comment by DianaTavares** [comment]
These are the ones in Density:
<img width="666" alt="image" src="https://github.com/user-attachments/assets/fa92ab2d-e488-4c27-b5dc-6d0a78e82fc2">

And **yes**, I think that the best is to put the same as Buoyancy, in that way we add Michael and Agustín and delete from the QA the people that are not at PhET right now. 

I guess that for changing the ones on the webpage is something to do in Admin. I will ask @arouinfar.

Process changing the credits in Density!

**Comment by samreid** [comment]
> delete from the QA the people that are not at PhET right now.

It was my understanding that once someone appeared in the credits, they would remain there for all future publications of that sim. Just wanted to double check, it could be I misunderstood or that the plan changed. @arouinfar do you know one way or the other?

**Comment by arouinfar** [comment]
> It was my understanding that once someone appeared in the credits, they would remain there for all future publications of that sim. Just wanted to double check, it could be I misunderstood or that the plan changed. @arouinfar do you know one way or the other?

That's also my understanding @samreid. We should not remove any previous QA credits for Density. 

Let's consider factoring out the credits to be shared across all of the density-buoyancy-common sims, as we've done in other sim suites. The legacy [Density](https://phet.colorado.edu/en/simulations/deprecated/density/credits) and [Buoyancy](https://phet.colorado.edu/en/simulations/buoyancy/credits) sim pages both list the same people in the credits, and in HTML5, the design and development credits are the same for all 3 sims. It seems easiest to maintain one set of credits, especially when it comes time to start adding in QA credits as we near publication.  Do we want to keep track of which subset of sims the testers worked on? This also means that Density's original QA team will be credited in Buoyancy/B:B, but that seems reasonable, as many of the bugs patched in Density likely had downstream effects in Buoyancy/B:B.

**Comment by samreid** [comment]
I updated the credits based on the discussion above. I left Chris M in the software development since he was listed there in density. I sorted developers by last name. The result is:

```ts
{
  leadDesign: 'Diana L\u00f3pez Tavares, Kelly Lancaster',
  softwareDevelopment: 'Michael Kauzmann, Chris Malley (PixelZoom, Inc.), Jonathan Olson, Sam Reid, Agust\u00edn Vallejo',
  team: 'Wendy Adams, Trish Loeblein, Ariel Paul, Archie Paulson, Kathy Perkins, Noah Podolefsky, Amy Rouinfar, Carl Wieman',
  qualityAssurance: 'Logan Bray, Steele Dalton, Jaron Droder, Brooklyn Lash, Emily Miller, Liam Mulhall, Devon Quispe, Jacob Romero, Nancy Salpepi, Katie Woessner',
  graphicArts: '',
  soundDesign: '',
  thanks: ''
}
```

This is factored out to one place. @DianaTavares or @arouinfar any other changes to make?

**Comment by DianaTavares** [comment]
Looks good for me!

**Comment by arouinfar** [comment]
Thanks @samreid, looks good. We'll need to finalize QA credits in RC, so I'll leave this issue open and unassigned.

**Comment by zepumph** [comment]
Let's do QA Credits in https://github.com/phetsims/density-buoyancy-common/issues/353
