### ISSUE TITLE
If the sim uses WebGL, does it have a fallback? Does the fallback perform reasonably well? (run with query

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#174]

**Comment by samreid** [comment]
@zepumph and @AgustinVallejo or @jonathanolson do we intend a fallback renderer for these simulations?

**Comment by samreid** [comment]
With webgl=false it currently looks like this:

<img width="1515" alt="image" src="https://github.com/phetsims/density-buoyancy-common/assets/679486/e42d325a-1fc7-4f57-9348-6118fbaaedd8">

**Comment by zepumph** [comment]
No. This is how Density went through publication. I don't think any extra work should be put into this fallback implementation. I recommend closing.
