### ISSUE TITLE
What is the red line in the debug view?

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#18]
I tested the debug view and saw a red line I didn't understand, is this how it should behave?  For #5 

![image](https://user-images.githubusercontent.com/679486/128764558-26a6bb92-d410-4f56-9140-5de57aaed86f.png)

**Comment by samreid** [comment]
Also, there is a green line.

**Comment by jonathanolson** [comment]
It's essentially a sideways chart, with:

- green proportional to the volume up to that level that is displaced in that basin
- red proportional to the area at that level that is displaced in that basin

So it shows essentially the "how much stuff isn't liquid" and the integral of that. These are incredibly helpful for debugging algorithms that use these (where should the liquid level be for basins), but also for if they are buggy (I had a few integral ones wrong earlier).

**Comment by samreid** [comment]
Sounds good, can you please add notes of that nature to the implementation?

**Comment by jonathanolson** [comment]
Added notes above.

**Comment by samreid** [comment]
Excellent, thanks!  Closing.
