### ISSUE TITLE
PVC breaks the simulation in B:B explore! 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/density-buoyancy-common#180]
The block's controls work amazingly! except when I select PVC. The simulations stop working and I can't interact with anything. PVC is the only material in the list that was added in Buoyancy, compared with Density. 
![PVC](https://github.com/phetsims/density-buoyancy-common/assets/26031501/797e1a95-1f5a-4e71-9f61-e3a0c2d32c46)

**Comment by zepumph** [comment]
We saw this too! I believe it was fixed over in #165.  Likely this is a phettest out-of-date issue.
