### ISSUE TITLE
Inspect `${REPO}-strings_en.json` and verify that all string keys conform

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#183]
From the review, it would be nice to make a few changes to the string keys as long as they do not mess up the density strings.

- [x] material.boatBody => material.boatHull
- [x] shapePattern => shapeTagPattern

Not sure about these, but I think we used this pattern elsewhere:
- [ ] UNSAFE: kilogramsPattern => kilogramsKgPattern
- [ ] UNSAFE: litersPattern => litersLPattern
- [ ] UNSAFE: decimetersCubedPattern => decimetersCubedDm3Pattern
- [x] newtonsUnit => N
- [ ] UNSAFE: newtonsPattern => newtonsNPattern

UPDATE: On second thought, I'm seeing enough discrepancies that it would be good to chat about

**Comment by zepumph** [comment]
@zepumph doesn't care about the key names personally, and totally trusts you. Just be sure that keys in Density 1.1 (the published version) aren't changed: https://phet.colorado.edu/sims/html/density/latest/english-string-map.json

**Comment by zepumph** [comment]
Also noting the script in https://github.com/phetsims/density-buoyancy-common/issues/175#issuecomment-2152977286 that you could use to double check.

**Comment by AgustinVallejo** [comment]
Adding SAFE or UNSAFE before each one after checking Density.
- [x] SAFE: Adding to this the 'densityA' string keys that should change to 'fluidA' as requested in https://github.com/phetsims/density-buoyancy-common/issues/248
- [x] UNSAFE: primary and secondary to A and B, see https://github.com/phetsims/density-buoyancy-common/issues/182 (It's used in PrimarySecondaryControlsNode, which is used by DensityIntroScreenView)

**Comment by AgustinVallejo** [comment]
After exploring in https://phet.colorado.edu/sims/html/density/latest/english-string-map.json it seems the only key not currently in the density translation keys is 'newtonsUnit'. We'd have to see if the others are actually used tho.

**Comment by AgustinVallejo** [comment]
@zepumph advised me to grunt checkout-target to density 1.1. I looked for the strings mentioned above and added SAFE and UNSAFE based on whether they were being used by density. Will change the remaining safe one (Density* to Fluid*) and we should probably discuss the Primary ones.

**Comment by zepumph** [comment]
My recommendation is to not rename the remaining strings, but let's discuss at our meeting today.
