### ISSUE TITLE
The density slider in Compare (both sims) and Explore (B:B) need to go to 3 kg/L

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/density-buoyancy-common#185]
The pool in the simulation can have mercury with a density of almost 14 kg/L, so we need the blocks can sink in it. The density slider needs to have a max value of 15 kg/L, in:

- [x] Compare: Density slider, that appears when “same density” is selected. This is in both simulations.
- Explore, in B:B, density slider in the blocks control (for both blocks).  -> Not needed

This implies that some vectors go beyond the screen. Do we require the zoom vector? 
All student interviewed for B:B, except for one (5 in total), do not use vectors to analyze the phenomena (they only focus on density). I think that most of them don't understand them. Then the options are:

1.  No to the zoom vector: If students don't use them to analyze the phenomena, probably teachers do it. Then it will be a more "teacher feature"  that use in their explanations to go deeper. In that case, teachers can choose a scenario where vectors fit in the sim. 
2. The control can be "visible" or "invisible" by adding the option in the preference panel (as % submerge). Again, thinking that this feature is only to go deeper in the analysis of B:B, teachers to want a more advance experience for their students, can make visible the control.

**Comment by samreid** [comment]
From design meeting:
Should the density slider range be increased to something larger than Mercury? Current max is 2 kg/L.

If the density slider range goes to 15 kg/L, it will affect the interaction when the fluid in the pool is water. Only a small range of values will result in objects that float.

The Explore screen allows density up to 10 kg/L. No changes needed for this screen.

If students understand the relationship between object/fluid density, it’s okay that things don’t float in mercury. It’s really dense!

Compromise: increase density slider max to 3 kg/L. Would maintain more dynamic range for floating objects in water, but allow the blocks to sink a bit more into the mercury.


Consensus:

**In Buoyancy: Basics, and Buoyancy “Compare” screen: Increase max to 3 kg/L for the density slider**

**Comment by samreid** [comment]
OK I changed it to go to 3kg/L on Buoyancy and Buoyancy: Basics and left it at 2kg/L max on Density compare screen. @DianaTavares can you please spot check on phettest? Close if ok.

**Comment by DianaTavares** [comment]
amazing, thanks!!!
