### ISSUE TITLE
Create BuoyancyScreenView

### ISSUE THREAD

**Issue by zepumph** [phetsims/density-buoyancy-common#186]
From https://github.com/phetsims/buoyancy/issues/86, here is a checkbox to do:

> Don't show items that are not shown in screen (i.e. `vectorScaleProperty`)

Right now there is too much logic separated by too much distance for these Properties that are only needed by the view in Buoyancy sims.

Buoyancy logic is way to deep in DBC code. Let's make BuoyancyScreenView to handle the view related items here. 
This could all be contained in a class created in DensityBuoyancyScreenView. Then everything is in the view, and the options passed to the Property creation and likely much closer to where the BuoyancyDisplayOptionsPanel is created.

Here are likely the Properties to move to the view:

```
showGravityForceProperty
showBuoyancyForceProperty
showContactForceProperty
showForceValuesProperty
showMassValuesProperty
vectorZoomProperty
showDepthLinesProperty

**Comment by zepumph** [comment]
- [x] And let's look into cleaning up the signatures of all the MassView subTypes, which are individually providing many of these Properties. Maybe all in one packet like "displayOptionsModel"?

**Comment by samreid** [comment]
I think we also discussed that they would ideally be named like: `gravityForceVisibleProperty`

**Comment by samreid** [comment]
I have progress on this in my working copy. However, we make have to adjust the plan somewhat because subtypes like `CuboidView` are created in `DensityBuoyancyScreenView` and need the display options passed in. Even if we bundle them, it may still be cleaner to create them in `DensityBuoyancyScreenView`. That will still give us a shutoff valve for them, but it would mean we may not need BuoyancyScreenView. I'll keep investigating.

**Comment by samreid** [comment]
I believe I addressed everything here. Some notes for the review:

* BuoyancyScreenView is mostly a marker class, just has one shared/factored out default common to the buoyancy screens.
* Options were moved from nested/named to required top level parameters.
* View properties were renamed
* Constructor for types like Cuboid are much simpler.
* I visually compared the start scenarios of each of the 9 screens to the established version on phettest
* I wrote corresponding migration rules.

This was a very extensive refactoring and it's likely something was disrupted, so it would be good for design + code + studio review.

**Comment by zepumph** [comment]
I didn't love the required parameters. This is very confusing and hard to maintain:

https://github.com/phetsims/density-buoyancy-common/blob/6d38f581a3b732eb601ccd6d40f089e5ba06255c/js/buoyancy/view/shapes/BuoyancyShapesScreenView.ts#L60

I would much prefer these as options, but we can discuss more.



RE: this todo:

> `// TODO: https://github.com/phetsims/density-buoyancy-common/issues/186 Why is the force scale 1/4 here? Won't that be confusing to secretly have the scale differ on 1 out of 5 screens?`


SR asked designers if different default vector scales on different screens was buggy? They said "no" this is right.

**Comment by samreid** [comment]
> I would much prefer these as options, but we can discuss more.

That sounds like it would also help with searchability. Here is how it shows with inlay hints though (which I do not use)

<img width="1316" alt="image" src="https://github.com/phetsims/density-buoyancy-common/assets/679486/c3e28cb8-b2c5-4c99-be1b-45faef95534e">

But moving into options sounds ok to me. Should I go for it or discuss more?

**Comment by zepumph** [comment]
I'd go for it! Also I just looked at studio and it looks really excellent. Good work.

**Comment by samreid** [comment]
OK, I moved things into required options.  I noticed `StrictOmit<DensityBuoyancyScreenViewOptions, 'canShowForces' | 'supportsDepthLines' | 'forcesInitiallyDisplayed' | 'massValuesInitiallyDisplayed' | 'initialForceScale'>` is repeated several times. I also felt ok making them all required, but we could put `initialForceScale` to optional. Can you please review and advise?

**Comment by zepumph** [comment]
@samreid and I found that BuoyancyScreenView should have the `poolScaleHeightControl`, instead of the supertype.

**Comment by zepumph** [comment]
I defer to @samreid if he wants to keep the options required, or provide deafults in DBCSV and BuoyancyScreenView.

**Comment by samreid** [comment]
@zepumph and I addressed the remaining recommendations and agreed to close the issue.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.
