### ISSUE TITLE
Cleanup onMassAdded

### ISSUE THREAD

**Issue by zepumph** [phetsims/density-buoyancy-common#187]
the base ScreenView type for all sims should not need to know how to create every possible MassView that could exist anywhere. This is awkward and leads to importing Buoyancy code in Density (BoatView/DuckView). Let's see about improving this.

https://github.com/phetsims/density-buoyancy-common/blob/f70e04748f761081e5e9466224340a97dfbe6a9e/js/common/view/DensityBuoyancyScreenView.ts#L509-L558

**Comment by zepumph** [comment]
@samreid @AgustinVallejo and I brainstormed making this a prototype method that is overridden for the shapes and applications screens. This will keep all these types out of Density and B:B sims.

**Comment by AgustinVallejo** [comment]
I believe this is mostly working. Not sure how to test that Density and B:B are no longer importing this. 

Also, the above commit msg got an import statement somehow, sorry about that!

**Comment by zepumph** [comment]
In standup we talked about using namespace to see if something was imported. we say that B:B did not have `phet.densityBuoyancyCommon.BoatView` anymore, but did still have `Boat`.

**Comment by AgustinVallejo** [comment]
Closinggg
