### ISSUE TITLE
White Square Appears in top left corner

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#189]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1095 and similar to what I saw in Projectile Data Lab (https://github.com/phetsims/projectile-data-lab/issues/178), a white square appears in the upper left hand corner on all screens when interacting with checkboxes and sliders. 

**Steps to reproduce**
Here is an example:
1. On the Compare Screen, check the Gravity Checkbox -- a small, white square appears in the upper left corner and then disappears after 1-2 seconds
2. Adjust the Mass Slider -- an even larger white square appears and then disappears

**Visuals**
<img width="347" alt="Screenshot 2024-06-12 at 1 09 13 PM" src="https://github.com/phetsims/density-buoyancy-common/assets/87318828/8c231ad9-a870-4539-ba1e-e67f5f32c90e">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Buoyancy‬
URL: https://phet-dev.colorado.edu/html/buoyancy/1.0.0-dev.9/phet/buoyancy_all_phet.html
Version: 1.0.0-dev.9 2024-06-12 15:13:18 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15
Language: en-US
Window: 1380x706
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by samreid** [comment]
Thanks @Nancy-Salpepi. I'll take a look

**Comment by samreid** [comment]
Fixed using the same strategy as in projectile data lab, closing.
