### ISSUE TITLE
Consider changing default location of Object B 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#193]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1095, on the Shapes Screen, when selecting the Two Blocks radio button, the cone drops down directly onto the scale in the pool. Maybe its initial position should be moved more towards the center of the pool similar to the Explore Screen?

**Steps to reproduce**
Go to the Shapes Screen and press the Two Blocks radio button.

**Visuals**
Shapes Screen: 
<img width="347" alt="Screenshot 2024-06-12 at 4 15 47 PM" src="https://github.com/phetsims/density-buoyancy-common/assets/87318828/6923afb9-e355-4eac-80f1-daa3576f97e1">

Explore Screen:
<img width="636" alt="Screenshot 2024-06-12 at 4 25 36 PM" src="https://github.com/phetsims/density-buoyancy-common/assets/87318828/c829d01a-7492-462e-8d89-c3185a19527e">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Buoyancy‬
URL: https://phet-dev.colorado.edu/html/buoyancy/1.0.0-dev.9/phet/buoyancy_all_phet.html
Version: 1.0.0-dev.9 2024-06-12 15:13:18 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Language: en-US
Window: 1352x722
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by DianaTavares** [comment]
Agree! Assigning the developers to do that modification. 
thanks!!

**Comment by samreid** [comment]
I'll work on this

**Comment by samreid** [comment]
Fixed, closing.
