### ISSUE TITLE
Pool scale gets stuck in bottle

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#194]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari and Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1095, on the Applications Screen, it is possible for the pool scale to get stuck in the bottle (or the bottle to get stuck in the scale 🙃) when changing the scale height. 

**Steps to reproduce**
1. On the Applications screen, change the material to Concrete
2. Place the bottle on the scale
3. Lower the height and then raise it to the max value

**Visuals**

https://github.com/phetsims/density-buoyancy-common/assets/87318828/6c480f80-35f5-4835-8a38-cf0066e2da44

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Buoyancy‬
URL: https://phet-dev.colorado.edu/html/buoyancy/1.0.0-dev.9/phet/buoyancy_all_phet.html
Version: 1.0.0-dev.9 2024-06-12 15:13:18 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15
Language: en-US
Window: 1380x706
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by samreid** [comment]
In discussion with @DianaTavares and @zepumph we would like to add a check for overlap, and teleport the bottle out of the scale if they overlap too much. @zepumph thinks @jonathanolson would also be good to consult with for this.

**Comment by samreid** [comment]
I tried checking for an overlap of the bounds, but I think I have them in the wrong coordinate frame or something since they do not overlap when it looks like they should. Would be good to get asssitance

<details>

```diff

Subject: [PATCH] Adjust initial positions, see https://github.com/phetsims/density-buoyancy-common/issues/193
---
Index: density-buoyancy-common/js/buoyancy/model/applications/ApplicationsMass.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/density-buoyancy-common/js/buoyancy/model/applications/ApplicationsMass.ts b/density-buoyancy-common/js/buoyancy/model/applications/ApplicationsMass.ts
--- a/density-buoyancy-common/js/buoyancy/model/applications/ApplicationsMass.ts	(revision 273a6b0e053338db58e3ddb8c1db03a04fd47480)
+++ b/density-buoyancy-common/js/buoyancy/model/applications/ApplicationsMass.ts	(date 1718307283397)
@@ -49,7 +49,8 @@
    */
   protected override getLocalBounds(): Bounds3 {
     const bounds2 = this.shapeProperty.value.bounds;
-    return new Bounds3( bounds2.minX, bounds2.minY, -bounds2.minY, bounds2.maxX, bounds2.maxY, bounds2.minY );
+    const height = bounds2.height;
+    return new Bounds3( bounds2.minX, bounds2.minY, -height / 2, bounds2.maxX, bounds2.maxY, height / 2 );
   }
 
   protected abstract evaluatePiecewiseLinearArea( ratio: number ): number;
Index: dot/js/Bounds3.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/dot/js/Bounds3.ts b/dot/js/Bounds3.ts
--- a/dot/js/Bounds3.ts	(revision 1529ddbebf001e0cbd4c41871eedda1a63ddc191)
+++ b/dot/js/Bounds3.ts	(date 1718307419676)
@@ -203,7 +203,7 @@
   /**
    * Get the volume of the Bounds3 as if it were a cube.
    */
-  public get volume(): number { return this.width * this.height * this.depth;}
+  public get volume(): number { return Math.abs( this.width * this.height * this.depth );}
 
   /**
    * Whether we have negative width, height or depth. Bounds3.NOTHING is a prime example of an empty Bounds3.
Index: dot/js/Bounds2.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/dot/js/Bounds2.ts b/dot/js/Bounds2.ts
--- a/dot/js/Bounds2.ts	(revision 1529ddbebf001e0cbd4c41871eedda1a63ddc191)
+++ b/dot/js/Bounds2.ts	(date 1718307689019)
@@ -253,6 +253,8 @@
     return isFinite( this.minX ) && isFinite( this.minY ) && isFinite( this.maxX ) && isFinite( this.maxY );
   }
 
+  public get area(): number { return Math.abs( this.getWidth() * this.getHeight() ); }
+
   /**
    * Whether this bounds has a non-zero area (non-zero positive width and height).
    */
Index: density-buoyancy-common/js/buoyancy/model/applications/BuoyancyApplicationsModel.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/density-buoyancy-common/js/buoyancy/model/applications/BuoyancyApplicationsModel.ts b/density-buoyancy-common/js/buoyancy/model/applications/BuoyancyApplicationsModel.ts
--- a/density-buoyancy-common/js/buoyancy/model/applications/BuoyancyApplicationsModel.ts	(revision 273a6b0e053338db58e3ddb8c1db03a04fd47480)
+++ b/density-buoyancy-common/js/buoyancy/model/applications/BuoyancyApplicationsModel.ts	(date 1718308361478)
@@ -131,6 +131,32 @@
       'Boat and bottle should not be visible at the same time' );
 
     super.step( dt );
+
+    // Check for overlap between poolScale and bottle
+    if ( this.poolScale && this.bottle && this.bottle.visibleProperty.value ) {
+      // const poolScaleBounds = this.poolScale.getBounds();
+      // const bottleBounds = this.bottle.getBounds();
+      // const intersect = poolScaleBounds.intersection( bottleBounds );
+      // console.log( 'intersect volume: ', intersect.volume );
+
+      // console.log( intersect, poolScaleBounds, bottleBounds );
+
+      // if ( poolScaleBounds.intersectsBounds( bottleBounds ) ) {
+      //   console.log( 'overlap' );
+      // }
+
+      const scaleShape = this.poolScale.shapeProperty.value.transformed( this.poolScale.matrix );
+      const bottleShape = this.bottle.shapeProperty.value.transformed( this.bottle.matrix );
+
+      // compute the amount of overlap between the scale and the bottle
+      // const overlap = scaleShape.intersection( bottleShape );
+      // const overlap = scaleShape.bounds.intersection( bottleShape.bounds ).area;
+      console.log( scaleShape.bounds, bottleShape.bounds );
+      const overlap = scaleShape.bounds.intersection( bottleShape.bounds );
+      console.log( overlap );
+      console.log( overlap.area );
+      // console.log( 'overlap: ', overlap );
+    }
   }
 
   public override getBoat(): Boat | null {
@@ -173,4 +199,4 @@
   }
 }
 
-densityBuoyancyCommon.register( 'BuoyancyApplicationsModel', BuoyancyApplicationsModel );
\ No newline at end of file
+densityBuoyancyCommon.register( 'BuoyancyApplicationsModel', BuoyancyApplicationsModel );

**Comment by samreid** [comment]
@zepumph and I met with @jonathanolson and a barrier may work but it had a vertex offset problem. We also don't know if a barrier will work here, or if we will have to write other code to detect overlap in the step.

**Comment by samreid** [comment]
@AgustinVallejo and I showed that `createBarrier` won't solve the problem, even if the vertices were correct:

<img width="723" alt="image" src="https://github.com/phetsims/density-buoyancy-common/assets/679486/23df2760-c0f6-4e2d-85c4-1489881e16a4">

So we will continue with a "teleport" workaround.

**Comment by samreid** [comment]
- [x] Now that we established good bounds calculations in https://github.com/phetsims/density-buoyancy-common/issues/201 we can use that strategy to position the bounds adjacent to each other.

@zepumph also reviewed this issue and also recommended that we add another step:

- [x] Call `this.engine.bodySynchronizePrevious( mass.body );` in order to prevent the bottle from launching. This clears its velocity.

**Comment by AgustinVallejo** [comment]
I believe this is now working, assigning back to QA

**Comment by zepumph** [comment]
@AgustinVallejo, can you please also document what the "0.1" is in https://github.com/phetsims/density-buoyancy-common/commit/690a183a0db056c35d944ef9b7cd1476e22b478b#diff-ccb3bfe51033b52750506013e16d32154d2e88cbd66a09b424f571046bf04454R244? I don't quite understand it. Is it a number based on the size of the PoolScale?

**Comment by Nancy-Salpepi** [comment]
This looks fixed to me in main. @AgustinVallejo is this ready to close?

**Comment by AgustinVallejo** [comment]
Yup, documentation is in place. Closing.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by AgustinVallejo** [comment]
Redirected one of the TODO's to https://github.com/phetsims/density-buoyancy-common/issues/238 since it was not directly related to this.
