### ISSUE TITLE
"A" label wanders off

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#195]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari and Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1095, on the Applications Screen, the A label next to the bottle changes location or disappears after switching between scenes. It doesn't return to its default position on Reset All. 
Wondering if the A label is even needed here?

**Steps to reproduce**
1. On the Applications screen, move the bottle out of the pool next to the scale
2. Switch to the boat scene and then switch back --> the 'A' is now all the way to the right of the screen
3. Move the bottle to the pool
4. Switch to the boat scene and then switch back --> the 'A' isn't visible

**Visuals**

<img width="512" alt="Screenshot 2024-06-12 at 4 41 14 PM" src="https://github.com/phetsims/density-buoyancy-common/assets/87318828/d5f8bfc7-6771-453f-bdb0-1e40f0f6291e">

**Comment by samreid** [comment]
I can work on this

**Comment by samreid** [comment]
I have a nearly working patch but before continuing, I wanted to ask: should the bottle really have a letter "A" on it?

<details>

```diff

Subject: [PATCH] Round volume and mass instead of using locks, see https://github.com/phetsims/density-buoyancy-common/issues/192
---
Index: js/buoyancy/view/applications/BottleView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/buoyancy/view/applications/BottleView.ts b/js/buoyancy/view/applications/BottleView.ts
--- a/js/buoyancy/view/applications/BottleView.ts	(revision 685ceeded0b56f482e5dc1c902f921db265540b5)
+++ b/js/buoyancy/view/applications/BottleView.ts	(date 1718285262407)
@@ -111,7 +111,7 @@
     this.bottle = bottle;
 
     const bottleSize = bottle.getBounds();
-    this.tagOffsetProperty.value = new Vector3( bottleSize.minX + TAG_OFFSET, bottleSize.maxY - TAG_OFFSET, bottleSize.maxZ );
+    this.tagOffsetProperty.value = new Vector3( -bottleSize.width / 2 + TAG_OFFSET, -bottleSize.height / 2 - TAG_OFFSET, bottleSize.depth / 2 );
   }
 
   /**

**Comment by AgustinVallejo** [comment]
@samreid It was decided in design meeting to put the label so the Object Densities panel showed 'System A' to portray that we're talking about bottle, fluid and air inside, and not just 'Bottle'.

**Comment by samreid** [comment]
Fixed. I checked other occurrences that were positioning the tag based on the object position rather than size, but they didn't seem to exhibit the same bug. @zepumph or @AgustinVallejo can you please review my commit and see if/why it should/shouldn't apply elsewhere?

**Comment by AgustinVallejo** [comment]
Looks good! Also, noting that Sam's solution was changing `bottleSize.minX` to `bottleSize.width/2` and so on. Other shapes are still using `minX`, but with @samreid we realized that the masses in the shapes screen do have a sizeProperty, whereas the bottle was using the bounds, so that's why the ones in shapes were ok.

Closing!

**Comment by Nancy-Salpepi** [comment]
I'm seeing this again in https://github.com/phetsims/qa/issues/1136.

**Comment by Nancy-Salpepi** [comment]
Sorry! I shouldn't work late! I had an old version open because I was comparing something.
