### ISSUE TITLE
Should panels on Compare screen have the same max width?

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#196]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1095, with ?stringTest=dynamic, on the Compare Screen the panels on the right can be different sizes. 

**Steps to reproduce**
With ?stringTest=dynamic, go to the Compare Screen and press the right arrow key a couple of times

**Visuals**
<img width="484" alt="Screenshot 2024-06-12 at 5 00 31 PM" src="https://github.com/phetsims/density-buoyancy-common/assets/87318828/2ffa9b82-3abf-45dd-bdd8-afb3a507032b">

**Comment by Nancy-Salpepi** [comment]
Similarly, should the panels on the bottom of the Lab screen always be the same height?

<img width="563" alt="Screenshot 2024-06-12 at 5 08 27 PM" src="https://github.com/phetsims/density-buoyancy-common/assets/87318828/8a86f7be-b9de-46f7-bb43-cdab5a1fc16f">

**Comment by AgustinVallejo** [comment]
They should. We're addressing that in https://github.com/phetsims/density-buoyancy-common/issues/184. Closing this one.
