### ISSUE TITLE
Icons still visible for forces after setting visibleProperty to false

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#199]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1095, in the Studio wrapper on all screens:
When setting the `visibleProperty` to false for the following checkboxes, the icons are still present. Also--the icons aren't part of the interactive highlight or touch/pointer areas, which is unusual.

-  `view.buoyancyDisplayOptionsPanel.showGravityForceCheckbox.visibleProperty`
-  `view.buoyancyDisplayOptionsPanel.showContactForceCheckbox.visibleProperty`
-  `view.buoyancyDisplayOptionsPanel.showBuoyancyForceCheckbox.visibleProperty`

**Visuals**
<img width="216" alt="Screenshot 2024-06-13 at 11 15 53 AM" src="https://github.com/phetsims/density-buoyancy-common/assets/87318828/bf3a15fb-c65d-4e62-90be-34e5b7d21195">

**Comment by samreid** [comment]
Fixed in https://github.com/phetsims/density-buoyancy-common/commit/c30e096af8dac295f90c3456e6f740f65e9611cb, thanks!  Closing.
