### ISSUE TITLE
undefined when reading from empty masses ObservableArray.

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#2]
DensityBuoyancyScreenView currently has this code:

```js
      // @protected {Property.<Mass>} - Support controlling or changing the latest-touched mass in certain demos.
      this.currentMassProperty = new Property( model.masses.get( 0 ) );
```

However, at this point of initialization, model.masses is empty and model.masses.get(0) returns undefined.  So it seems the type annotation should be changed, or the masses should be populated before this code is run.

This problem was revealed by https://github.com/phetsims/axon/issues/273

**Comment by jonathanolson** [comment]
This looks handled with a check and `null` in master, thanks~
