### ISSUE TITLE
updateArrays are marked as private, but called from public

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#20]
For #5, `updateArrays` is marked as private and the IDE suggests it should not be callable:

![image](https://user-images.githubusercontent.com/679486/128766357-9b7c0b17-9ac2-46be-929b-6d70a35a40b6.png)

**Comment by jonathanolson** [comment]
These seem fine to be public, and it's useful from ScaleView. Done above.

**Comment by samreid** [comment]
Looks good, thanks!  Closing.
