### ISSUE TITLE
Assertions from debug sim

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density-buoyancy-common#200]
Density had a number of assertions show up when fuzzing the debug version of the sim. For https://github.com/phetsims/qa/issues/1095
![loadingassertions](https://github.com/phetsims/density-buoyancy-common/assets/41024075/941ff39d-c4dc-494a-b7ad-58c4836aff4b)
![morefail](https://github.com/phetsims/density-buoyancy-common/assets/41024075/3d7c8c33-ccf5-49ca-8631-dead6feb0ce7)
![andmore](https://github.com/phetsims/density-buoyancy-common/assets/41024075/b45a5817-c35d-45c0-98c3-e59816a88472)

**Comment by zepumph** [comment]
Thanks. @jonathanolson are already aware of this over in https://github.com/phetsims/joist/issues/970 and are working on a fix.

**Comment by samreid** [comment]
Should be fixed in main, we just need to double check.

**Comment by zepumph** [comment]
Confirmed. Closing
