### ISSUE TITLE
Bouncing Objects

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density-buoyancy-common#201]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/1095
On the Shapes screen of the Buoyancy sim, switching between the different shapes can make them bounce up. This seems particularly bad since it can imply a change in density if the object is in the water.
**Steps to reproduce**
1. Set the object on the ground
2. Change the shapes, particularly between the cones.

**Visuals**
![boing](https://github.com/phetsims/density-buoyancy-common/assets/41024075/49f182b3-bbfa-429f-ada7-c3caed05e054)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Buoyancy‬
URL: https://phet-dev.colorado.edu/html/buoyancy/1.0.0-dev.9/phet/buoyancy_all_phet.html
Version: 1.0.0-dev.9 2024-06-12 15:13:18 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Language: en-US
Window: 1536x695
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by samreid** [comment]
We can do the same thing as https://github.com/phetsims/density-buoyancy-common/blob/685ceeded0b56f482e5dc1c902f921db265540b5/js/common/model/Cuboid.ts#L61-L84

**Comment by samreid** [comment]
@DianaTavares @zepumph @AgustinVallejo and I reviewed the proposal above and think it is a good solution. When switching any mass shape, keep the bottom where it was.

**Comment by AgustinVallejo** [comment]
This was addressed in the above commit. Assigning back to @KatieWoe for review, and please assign to @zepumph for follow up code review once you're done, thanks!!

**Comment by KatieWoe** [comment]
Looks fixed on main to me

**Comment by zepumph** [comment]
This looks very nice. Thanks so much.
