### ISSUE TITLE
Reset all does not correctlty reset object position or material on Shapes screen

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density-buoyancy-common#202]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/1095
On the Shapes screen in the Buoyancy sim, the starting position of the object is different from the position it resets to. More concerningly, the material listed in the drop box for the object does not reset, and will appear in the object if you change it's shape.
**Steps to reproduce**
1. On the shapes screen, change the object material
2. Hit reset all
3. Change the object shape

**Visuals**
![resetallshapes](https://github.com/phetsims/density-buoyancy-common/assets/41024075/4fa61f3a-8e3e-4b65-a46f-f66282e18e86)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Buoyancy‬
URL: https://phet-dev.colorado.edu/html/buoyancy/1.0.0-dev.9/phet/buoyancy_all_phet.html
Version: 1.0.0-dev.9 2024-06-12 15:13:18 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Language: en-US
Window: 1536x695
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by samreid** [comment]
I fixed the position reset in https://github.com/phetsims/density-buoyancy-common/issues/193. The material of the second object is still not resetting though. I'll take a look.

**Comment by samreid** [comment]
Looks ok after resetting the material, closing.
