### ISSUE TITLE
Dimensions for some shapes don't reset correctly in the Standard Wrapper

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#204]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1095, in Studio/State Wrappers on the Shapes Screen:
If the sim is launched with the ellipsoid or duck as the selected shape, changing either the height or width and then pressing Reset All will result in a distorted shape.

**Steps to reproduce**
1. In the State wrapper, set state rate = 0
2. On the Shapes Screen, select the ellipsoid or the duck
3. Press Set State Now
4. In the downstream sim, change either the height or width
5. Press Reset All

**Visuals**
<img width="533" alt="Screenshot 2024-06-13 at 4 13 25 PM" src="https://github.com/phetsims/density-buoyancy-common/assets/87318828/fe9fde03-baa8-44c5-8aa7-1302c2b2a576">

<img width="533" alt="Screenshot 2024-06-13 at 4 15 46 PM" src="https://github.com/phetsims/density-buoyancy-common/assets/87318828/88cdf7e7-c8bf-4932-852f-1f6d73ee82c6">

**Comment by AgustinVallejo** [comment]
I also noticed that the sliders didn't transfer state, so I'm instrumenting them.

Also adding this cursed duck in here: 
![image](https://github.com/phetsims/density-buoyancy-common/assets/37052186/7ef30e01-dab2-4ced-92a0-a07c8d25713d)

I got the most extreme replication of this by setting opposite sliders upstream: max width and min height, setting state, and downstream inverting the sliders and resetting. Also, after the second reset it's good again...

**Comment by AgustinVallejo** [comment]
Poor guy:
![image](https://github.com/phetsims/density-buoyancy-common/assets/37052186/95853a78-380e-4b83-9f7a-1ad166b72058)

**Comment by AgustinVallejo** [comment]
This is ready for review! Quite a bug you found 😅

**Comment by Nancy-Salpepi** [comment]
This looks great on main @AgustinVallejo! 
I'm thinking you also fixed https://github.com/phetsims/density-buoyancy-common/issues/222 at the same time because I can't reproduce that one anymore either. 

Closing!
