### ISSUE TITLE
Add vector ZoomButtonGroup to B:B like we have in full sim

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#205]
From today's design meeting:

It’s possible for the vectors to go off-screen. Should we add zoom controls?

Should zoom controls go behind a Preference?
No, don’t need a Preference for this. Vectors are off by default, which is sufficient.

Consensus: **Add vector ZoomButtonGroup to B:B like we have in full sim**

**Comment by samreid** [comment]
The request was to add this feature to B:B. However, adding it in B:B adds it in the Compare screen, which is shared in Buoyancy, so Buoyancy will also get this feature in the compare screen. In the design meeting, it sounded like was no problematic so perhaps this is OK. After I commit I will double check with @DianaTavares

**Comment by samreid** [comment]
Fixed, please review on phettest and please close if ok.

**Comment by DianaTavares** [comment]
looks amazing! thanks!
