### ISSUE TITLE
Suppress Three.js output

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#21]
From https://github.com/phetsims/density-buoyancy-common/issues/5, I noticed the console prints out the following during startup:

```
three-r104.js:22676 THREE.WebGLRenderer 104
three-r104.js:22676 THREE.WebGLRenderer 104
three-r104.js:22676 THREE.WebGLRenderer 104
```

Can this be suppressed, since we have a convention that nothing should be output during normal circumstances?

**Comment by samreid** [comment]
I don't see a flag to enabled/disable that.  Instead I'd recommend commenting out that line in sherpa.

**Comment by jonathanolson** [comment]
I'm happy to do that, but we'll presumably need to note the modifications (at least for license stuff, and also for maintenance, no?) How do we do that?

Patching all three.js versions (including the older one for molecule-shapes) sounds good, just curious about what the precedent and license implications are.

**Comment by samreid** [comment]
We had a similar problem in https://github.com/phetsims/chipper/issues/787 which we fixed by making a minor commit in sherpa.

> for license stuff

THREE is MIT, so we can make this change without complications

> for maintenance

In https://github.com/phetsims/chipper/issues/787 we said if the problem returns when we update to a new version, we'll fix it again in our copy of the new version.

**Comment by jonathanolson** [comment]
Done above, can you verify?

**Comment by samreid** [comment]
Looks good, thanks!  Closing.
