### ISSUE TITLE
Inconsistent slider movement with keyboard.

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density-buoyancy-common#212]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/1095
The amount a single key press with keyboard nav moves a slider seems inconsistent. The mass and volume sliders on the first screen move between .4 and .6 units, rather than a consistent .5. This was done only with up/down/left/right, no pg up/dn, home/end, or shift + arrows. Seemed to happen most at the edges of the slider.

**Visuals**
![inconsistant](https://github.com/phetsims/density-buoyancy-common/assets/41024075/aacc4857-8288-4e8d-b61d-5caca80de2dd)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Buoyancy‬
URL: https://phet-dev.colorado.edu/html/buoyancy/1.0.0-dev.9/phet/buoyancy_all_phet.html
Version: 1.0.0-dev.9 2024-06-12 15:13:18 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Language: en-US
Window: 1536x695
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by AgustinVallejo** [comment]
Thanks! Slider controls should be way improved now. Assigning back for review

**Comment by KatieWoe** [comment]
Looks much better. Movement is now by .05 rather than .5. Is this intended?

**Comment by AgustinVallejo** [comment]
Good call! Updating the step size an closing
