### ISSUE TITLE
Prefer "fluid" to "liquid" and "water"

### ISSUE THREAD

**Issue by zepumph** [phetsims/density-buoyancy-common#213]
WaterLevelIndicator->FluidLevelIndicator
isUnderwater-> isFullySubmerged

**Comment by AgustinVallejo** [comment]
Pretty big renaming here, I tested and made sure not to affect the OG Water Material or Sea Water materials. A second pair of eyes for reviewing would be nice.

**Comment by zepumph** [comment]
I'll keep reviewing. I just factored out a mesh but didn't get through the whole commit.

**Comment by zepumph** [comment]
Looks great. I did a couple more renames, removed a TODO, and I think we are ready to close. Pretty much the only stuff left here is "liquid" in regards to materials (liquidColor/createCustomLiquidMaterial) etc. Closing
