### ISSUE TITLE
Squishing one scale under the other

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density-buoyancy-common#214]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/1095.
It is possible to put the moveable scale under the scale on a slider. It is then possible to move the slider scale down, pushing the first scale under ground with an enormous force shown. The scale usually pops up next to the slider scale part way down.
**Steps to reproduce**
1. Move the slider scale to the very top of its slider
2. Drag the moveable scale under the slider scale
3. Move the slider scale down

**Visuals**
![squish](https://github.com/phetsims/density-buoyancy-common/assets/41024075/d449c222-0993-4756-92a9-122b3d9451e0)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Buoyancy: Basics‬
URL: https://phet-dev.colorado.edu/html/buoyancy-basics/1.0.0-dev.5/phet/buoyancy-basics_all_phet.html
Version: 1.0.0-dev.5 2024-06-12 15:20:01 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Language: en-US
Window: 1536x695
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
You'll need to drag the scale along the bottom.

**Comment by samreid** [comment]
Fixed, closing
