### ISSUE TITLE
Two-block radio button group layout bug when block control is hidden

### ISSUE THREAD

**Issue by zepumph** [phetsims/density-buoyancy-common#215]
In PhET-iO you can hide the control for editing the blocks. When you do that, the radio buttons layout is on the resetAllButton.

![image](https://github.com/phetsims/density-buoyancy-common/assets/6856943/eb52c3ed-b128-44d0-9f6e-13a1466e7ff5)

**Comment by zepumph** [comment]
FURTHERMORE! @samreid just pointed out that the sim will crash if you also hide the other two accordion boxes.

**Comment by AgustinVallejo** [comment]
I'm basing these buttons off the reset all now. Closing
