### ISSUE TITLE
PhET-iO State Support for locks in MaterialMassVolumeControlNode.ts

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/density-buoyancy-common#217]
In MaterialMassVolumeControlNode.ts we have this:

```
    // We need to use "locks" since our behavior is different based on whether the model or user is changing the value
    let modelMassChanging = false;
    let userMassChanging = false;
    let modelVolumeChanging = false;
    let userVolumeChanging = false;
```

There are multiple problems with this:
1. If these were stateful (they aren't). The user upstream could cause some buggyness when the state is being set.
2. Because they are not stateful, the downstream user could cause buggyness when state is being set.
3. When the state is set, these listeners might toggle these values and produce awkward downstream logic.

**Comment by zepumph** [comment]
I just added a resetting listener to make sure that these locks never interfered when setting state. I couldn't produce any bugs before this change, but it was simple and safe enough to add, preventing any potential QA issue when interacting with the sliders while setting state. Closing
