### ISSUE TITLE
Factor out FluidDensityControlPanel

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#218]
From https://github.com/phetsims/buoyancy/issues/86 we saw that a "Panel" tandem is being passed to things that are not Panels, and we have an opportunity to factor out a Panel class, like FluidDensityControlPanel.

This kind of code is repeated:

```ts
    const fluidDensityControlPanel = new Panel( new FluidDensityControlNode( model.pool.fluidMaterialProperty, [
        ...Material.BUOYANCY_FLUID_MATERIALS,
        customMaterial,
        ...Material.BUOYANCY_FLUID_MYSTERY_MATERIALS
      ], customMaterial,
      this.popupLayer, {
        invisibleMaterials: invisibleMaterials,
        tandem: tandem.createTandem( 'fluidDensityControlPanel' )
      } ), DensityBuoyancyCommonConstants.PANEL_OPTIONS );
```

**Comment by samreid** [comment]
Fixed above. I kept some of the "controlPanel" names as @zepumph and @AgustinVallejo and I discussed earlier, so we can be reminded to rename them to just "panel" if we want.  But I noted in screen 1 the liquid panel is already `liquidPanel` and to avoid extra work, I left the class name and variable names like "panel".

**Comment by zepumph** [comment]
`liquidPanel` became `fluidPanel` in https://github.com/phetsims/density-buoyancy-common/issues/218. I think we are ready to close. Thanks for doing this.
