### ISSUE TITLE
What determines the weight when pulling an object down on a scale?

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#22]
From https://github.com/phetsims/density-buoyancy-common/issues/5, I observed very different weights when dragging an object down on a scale.  Adjusting the mouse while dragging (by a pixel or two) can also cause different readings on the scale.  Is this behavior by design, or emergent from the physics engine?  Does anything need to be done about it?

**Comment by jonathanolson** [comment]
It's done by applying forces (similar to examples in p2.js). So if you are dragging down on it, it's applying a large (but capped) force.

@DianaTavares just confirming this is expected/known/ok, anything that should be done?

**Comment by samreid** [comment]
Here's a screen capture that overlaps with this issue:

![Kapture 2021-08-10 at 13 52 24](https://user-images.githubusercontent.com/679486/128926035-76e601de-1a07-498d-abd6-b3cc80dbde59.gif)

**Comment by DianaTavares** [comment]
Nothing to add here. This behavior is acceptable.
