### ISSUE TITLE
Shapes screen doesn't always reset to One Block Scene with Reset All

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#221]
**Test device**
MacBook Air M1 chip and Chromebook

**Operating System**
14.5

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1095, on the Shapes Screen, with the 2 Blocks Scene selected, if I change the shape of Block B and then press Reset All, the screen will not reset to the One Block Scene.

**Steps to reproduce**
1. On the Shapes Screen Select 2 Blocks Scene
2. Change the shape of Block B
3. Press Reset All

**Visuals**

https://github.com/phetsims/density-buoyancy-common/assets/87318828/422d85bc-dab4-4c37-a252-393d41d9ac0e

**Comment by samreid** [comment]
I'll take a look

**Comment by samreid** [comment]
Fixed, closing.

**Comment by Nancy-Salpepi** [comment]
I see this issue again in https://github.com/phetsims/qa/issues/1136.

**Comment by Nancy-Salpepi** [comment]
Sorry! I was in an older dev version. 
Closing.
