### ISSUE TITLE
Empty bottle bounces indefinitely on honey

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#223]
**Test device**
MacBook Air M1 chip and Chromebook

**Operating System**
macOS 14.5

**Browser**
Safari and Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1095, on the Applications Screen when the bottle is empty it will bounce indefinitely on the honey.

**Steps to reproduce**
1. On the Applications screen select 'honey' 
2. Move the volume slider to the minimum

**Visuals**

https://github.com/phetsims/density-buoyancy-common/assets/87318828/3afe3272-c162-4962-8504-57a7097a8389

**Comment by samreid** [comment]
There is probably a bug in the viscous force. Developers will take a look. If we cannot solve it there, @DianaTavares and @arouinfar indicated we may be able to change the minimum amount in the bottle.

**Comment by samreid** [comment]
@AgustinVallejo volunteered to review, thanks!

**Comment by AgustinVallejo** [comment]
Fixed a minor typo in the above commit but otherwise looking good! Assigning back to QA for feature review

**Comment by Nancy-Salpepi** [comment]
The bottle no longer bounces on the honey!
Closing.
