### ISSUE TITLE
Provide maxVolumes in Buoyancy

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/density-buoyancy-common#224]

**Comment by zepumph** [comment]
I got most of the way complete here, but didn't add anything to the boat or bottle. I'd like to discuss this a bit further. Everything else was simple and easy.

https://github.com/phetsims/density-buoyancy-common/blob/7ab86a41341dab7a0443e2ab5ab544f9d0661f81/js/buoyancy/view/applications/BuoyancyApplicationsScreenView.ts#L211-L231

**Comment by samreid** [comment]
@zepumph and I collaborated on the commit above. @zepumph can you please double check and see if there is more to do in this issue? Feel free to close at your discretion.

**Comment by zepumph** [comment]
We wrote a note for AR to double check on the min range on the shapes screen.

**Comment by zepumph** [comment]
Range was added to the boat's displacementVolumeProperty above. The rest will be handled in #228. Thanks @samreid for helping me out with this.
