### ISSUE TITLE
Grabbing falling/bobbing object with alt input causes strange behavior

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#226]
**Test device**
MacBook Air M1 chip and Chromebook

**Operating System**
macOS 14.5

**Browser**
Safari and Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1095, grabbing an object while it is still falling or bobbing in the pool will cause the object to move diagonally when I use the left/right arrow keys to move it across the screen. It will also slide along the edge of the screen when I hit the left/right dev bounds instead of just stopping. 

**Steps to reproduce**
Here is an example:
1. On the Explore Screen of the Buoyancy Sim, press tab to grab the block while it is falling 
2. Use arrow keys to move it up and then to the left (keep left arrow key down to see it slide along wall)
3. Keep moving the block left and right across the screen with the arrow keys

**Visuals**

https://github.com/phetsims/density-buoyancy-common/assets/87318828/f0e52023-2b1f-4643-96f9-da7fe0df21a7

**Comment by samreid** [comment]
Let's wait for the grab drag interaction implementation to see if it helps here. #209

**Comment by samreid** [comment]
@zepumph and @AgustinVallejo and I tested this with the new GrabDragInteraction and it appears fixed. Closing.
