### ISSUE TITLE
Fluid selection PhET-iO Support

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/density-buoyancy-common#228]
https://github.com/phetsims/density-buoyancy-common/blob/808828c767f8492a76291f7d730cc8d6c39ef2dc/js/common/view/ComboNumberControl.ts#L180-L181

These properties are being set blandly with no tandem nor other interesting options. This should be improved to support API control over the liquid density and gravity

**Comment by zepumph** [comment]
In addition to the above, in which ComboNumberControl needing this, `FluidSelectionPanel` needs this behavior too. Right now they are all just internal mapping functions back to the materialProperty in the model, which is an unacceptable way to interoperate with the density. 

- [x] By doing this in ComboNumberControl, we will also solve this problem for the Gravity control, which also cannot be set.

**Comment by arouinfar** [comment]
I think we are on the same page, but to be clear, here are the design requests for Fluid and Gravity controls:

- [x] It should be possible to set the fluid/gravity ComboBox Property, similar to `density.introScreen.view.blockAControlPanel.comboBoxMaterialProperty`
- [x] The slider valueProperty should be API-settable, with the range matching the slider.
- These ComboBox and Slider Properties should be...
    - [x] linked under the applicable view elements.
    - [x] `phetioFeatured: true`

**Comment by samreid** [comment]
Today @AgustinVallejo showed he has working copy changes to address this. However, @zepumph and I would like to take more steps in https://github.com/phetsims/density-buoyancy-common/issues/176 before we proceed.  Going on hold for a bit.

**Comment by zepumph** [comment]
- [x]  FluidDensityPanel probably doesn't want or need a `customMaterial` as an initial value, since custom materials are immutable and recreated.

**Comment by zepumph** [comment]
On hold until https://github.com/phetsims/density-buoyancy-common/issues/256 is a bit more complete.

**Comment by zepumph** [comment]
This issue is ready for a sync co-review with PhET-iO designers. We still have work to do here, and likely we will want DL and AR in the room as we discuss how this looks in studio now, and how it relates to https://github.com/phetsims/density-buoyancy-common/issues/270 (validValue selection).

**Comment by zepumph** [comment]
This issue is ready for review. You are now able to change the fluid and custom density of the custom fluid with PhET-iO. Please note this change equally effects Gravity, and that deserves a review as well. Both in the lab (where there is a control for it), and elsewhere. I believe that we spent no energy limiting the validValues for gravity, even in density.

**Comment by arouinfar** [comment]
Overall, this is a huge improvement to the Fluid and Gravity controls. The `validValues` work was worthwhile, resulting in good Studio UX.

I was surprised to see that the NumberControl is linking to `materialProperty`/`gravityProperty`. The slider sets the numerical value of the custom 
 fluid density/gravity, so it seems more appropriate to link to `materialProperty.customMaterial.densityProperty`/`gravityProperty.customGravity.gravityValueProperty`. Can we switch the target of the linked valueProperty?

**Comment by zepumph** [comment]
Good catch! Anything else here?

**Comment by arouinfar** [comment]
Thanks @zepumph! Looks good on main, closing.
