### ISSUE TITLE
`buoyancy.applicationsScreen.model.objects.bottle.interiorVolumeProperty` should be settable

### ISSUE THREAD

**Issue by zepumph** [phetsims/density-buoyancy-common#229]

**Comment by zepumph** [comment]
sub issue from https://github.com/phetsims/density-buoyancy-common/issues/228. This is the Property driving the volume number control for the bottle scene.

**Comment by zepumph** [comment]
I believe we still need to handle the range change. We don't want PhET-iO to be able to set outside of the slider for this. Can we move the view range over to the model so they are the same? 

https://github.com/phetsims/density-buoyancy-common/blob/aa73797827178418ec56718fcd89db31d556355c/js/buoyancy/view/applications/BuoyancyApplicationsScreenView.ts#L119-L120

**Comment by AgustinVallejo** [comment]
Pushed the above changes, not sure if that's what you meant, could you double check? @zepumph

**Comment by arouinfar** [comment]
@zepumph @AgustinVallejo while you're in there, please add units (m<sup>3</sup>) to  `interiorVolumeProperty`.

**Comment by zepumph** [comment]
Not sure how this related to #245, but all seems good here now @AgustinVallejo.

**Comment by AgustinVallejo** [comment]
Checked and looks good. Also, sufficiently different from the other one for this to be ready to close.

**Comment by zepumph** [comment]
interiorVolumePropertyRange is in the wrong unit. We want the max at 0.01.
