### ISSUE TITLE
Should the values in the density table be right aligned?

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#23]
From #5 Should the values in the density table be right aligned (so the decimals line up)?  They currently look like this.  Right-aligning would make the gold and lead stand out more.

![image](https://user-images.githubusercontent.com/679486/128782098-ad478ac6-d6b2-49cd-9275-e26b85a556e0.png)

**Comment by jonathanolson** [comment]
@DianaTavares thoughts?

**Comment by DianaTavares** [comment]
I agree with @samreid, I think is better to have the decimals line up with a right alignment.

**Comment by jonathanolson** [comment]
Implemented above, can you verify?

**Comment by samreid** [comment]
Looks much better to me, here is a snapshot:

![image](https://user-images.githubusercontent.com/679486/128914516-e91e6916-9ee3-41f7-83a8-18535269bcb1.png)

Thanks, closing.
