### ISSUE TITLE
Updates to `phetioDocumentation`

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density-buoyancy-common#232]
For https://github.com/phetsims/buoyancy/issues/51

@DianaTavares and I identified some places to add/update `phetioDocumentation`. 

- [x] `scaleForceInterpolatedProperty`: Weight measured by the scale, in N.
- [x] `scaleMeasuredMassProperty`: Mass measured by the scale, in kg.
- [x] `block*.massProperty`: Current mass of the object. 
    - This applies to all blocks/shapes in all sims. Current `phetioDocumentation` references screens within Density, but it seems best to remove this information and detail how to customize mass in examples.md.
- [x] `boat.displacementVolumeProperty`: Interior volume of the boat. 
     * Edit: Is it the internal volume, or the total volume? If the latter, let's say: Total volume of the boat, including the hull.
- [x] `boat.volumeProperty`: Volume of the boat hull. 
- [x] `bottle.customDensityProperty`: Density of the material inside the bottle when ‘CUSTOM’ is chosen.
- [x] `bottle.interiorMassProperty`: Mass of the material inside the bottle.
- [x]  `bottle.interiorVolumeProperty`: Volume of the material inside the bottle.
- For internal use only.
    - [x] `buoyancyForceInterpolatedProperty`
    - [x] `contactForceInterpolatedProperty`
    - [x] `gravityForceInterpolatedProperty`
    - [x] `sizeProperty`
    - [x] `userControlledProperty`
    - [x] `hasChangedProperty`

Assigning to the dev team.

**Comment by AgustinVallejo** [comment]
> boat.volumeProperty: Volume of the boat hull.

This is the only one left. Because volumeProperty is created in the parent class, to achieve this we have to use PhET-iO Overrides according to MK. Assigning to him. We can also pair to learn how it's done.

**Comment by zepumph** [comment]
Committed above. This is a bit quick and dirty, but I believe it is better and more maintainable than figuring out a way to provide custom phetioDocumentation to Mass.volumeProperty for only the Boat instance. Tagging @samreid so he is aware of my thoughts on it. @arouinfar would you like to proceed?


@AgustinVallejo FYI, if you run studio with `?admin` it will become very clear quickly how you can change certain metadata. Go to the volumeProperty for the boat and see that the phetioDocumentation is a text box, not just a paragraph. Changing it prints the new overrides json to the console, then you just paste that into the overrides.js file and you're ready to test.

**Comment by arouinfar** [comment]
Thanks @AgustinVallejo @zepumph! Overall looks good, but seems like the phetioDocumentation for `sizeProperty` was only applied to the duck. Can it be applied to all blocks/objects?

>  * For internal use only
> `buoyancyForceInterpolatedProperty`
> `contactForceInterpolatedProperty`
> `gravityForceInterpolatedProperty`

This was a bad request on my part, can we revert? If clients want to collect data about the forces in the system, these are the Properties they should look at. The `phetioID` is self-explanatory, so additional documentation is unnecessary.

**Comment by AgustinVallejo** [comment]
Done in the above commits. However:

>  Can it be applied to all blocks/objects?

It seems sizeProperty only existed on Duck, Ellipsoid and Cuboid. I added the documentation there. Do you think the rest of shapes should have it as well, or is this good to close? @arouinfar

**Comment by zepumph** [comment]
Yes, I don't think it is worth the refactor to change non size-based objects (like cone) to use it, even though technically something like radius+height Properties could be mapped into a sizeProperty. This consistency doesn't seem worth the cost. I recommend closing.
