### ISSUE TITLE
Create grouping of force controls in `displayOptionsPanel`

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density-buoyancy-common#233]
Related to https://github.com/phetsims/buoyancy/issues/51

The `displayOptionsPanel` exists on all screens of Buoyancy and Buoyancy: Basics.

<img width="250" alt="image" src="https://github.com/phetsims/density-buoyancy-common/assets/8419308/4b650d76-9c70-4bba-a749-77fdbee12f7b">
<img width="154" alt="image" src="https://github.com/phetsims/density-buoyancy-common/assets/8419308/c9d491da-9b15-41be-a619-fc4aa34cab11">

The top half of the panel contains controls related to the force vectors. It would be helpful if we could create a subpanel or other grouping of everything under "Forces" so these controls (including the title) could be hidden with one `visibleProperty`. This customization would support scaffolding around the forces and make it easier for instructional designers to design lessons without the vector representations. This could be particularly useful in Buoyancy: Basics, where the learning goals are more introductory.

@DianaTavares and I think an appropriate name would be `displayOptionsPanel.forceControls`. 

If `forceControls` is unacceptable, an alterative would be `displayOptionsPanel.forcesSubapanel` We've previously used the "subpanel" language in Geometric Optics, see `geometricOptics.lensScreen.view.controls.controlPanel.opticSubpanel`.  

Assigning to the dev team.

**Comment by AgustinVallejo** [comment]
I went with `forcesSubpanel`.

Can you review please @zepumph?

**Comment by zepumph** [comment]
Should we also nest `forceValuesCheckbox` too? The VBox change looks great.

**Comment by AgustinVallejo** [comment]
`forceValuesCheckbox` is also nested, when you turn off visibility for the `forcesSubpanel`, the only thing remaining are Mass values and depth lines. Unless I'm missing something...?

**Comment by zepumph** [comment]
Ahhh, what a lovely miscommunication on what "nested" means. I was talking phetioIDs:

<img width="224" alt="image" src="https://github.com/phetsims/density-buoyancy-common/assets/6856943/ddc44090-89c4-42b9-8147-d8c9cb16c10a">

**Comment by AgustinVallejo** [comment]
Oh right I hadn't noticed that. Could you take another look to double check?

**Comment by zepumph** [comment]
Looks perfect. I just found one more thing:

The `vectorZoomButtonGroup` doesn't seem to do what we think it should.

Toggling the visibility doesn't hide the text. 
![image](https://github.com/phetsims/density-buoyancy-common/assets/6856943/8c958972-d8c3-47c4-9b6f-3a0543a07ed6)


Committed above, does this look better to you?

**Comment by AgustinVallejo** [comment]
That's way better, thanks!
