### ISSUE TITLE
Don't import Boat, Bottle and Shapes in density

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/density-buoyancy-common#238]

**Comment by zepumph** [comment]
This seems potentially similar to #234, where we are trying to solve a similar problem for the Boat.

**Comment by samreid** [comment]
@AgustinVallejo is working on https://github.com/phetsims/density-buoyancy-common/issues/187 which may help us get rid of Bottle-related things from DensityBuoyancyScreenView. Let's put this issue on hold until we have progress in https://github.com/phetsims/density-buoyancy-common/issues/187

**Comment by AgustinVallejo** [comment]
This is ready for review. As far as I can tell, now both Density and B:B are free of Boat and Bottle, which were the heaviest ones. If this approach is favorable, we could also do something similar for Shapes.

**Comment by zepumph** [comment]
This looks excellent. Thanks for doing this.

**Comment by AgustinVallejo** [comment]
It seems as Shapes go, B:B and Density only import MassShape, which is an EnumerationValue and just holds the different shape names. Does it make sense to try to tackle this, or is this issue ready to close?
