### ISSUE TITLE
Are there issues for the {{GITHUB_ISSUE_LINK}} in the code review?

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#24]
From #5, I noticed it said: 

The following standard GitHub issues should exist. _If these issues are missing, or have not been completed, pause code review until the issues have been created and addressed by the responsible dev._

- [ ] results of memory testing for `brands=phet`, see {{GITHUB_ISSUE_LINK}}
- [ ] results of memory testing for `brands=phet-io` (if the sim is instrumented for PhET-iO), see {{GITHUB_ISSUE_LINK}}
- [ ] performance testing and sign-off, see {{GITHUB_ISSUE_LINK}}
- [ ] review of pointer areas, see {{GITHUB_ISSUE_LINK}}
- [ ] credits (will not be completed until after RC testing), see {{GITHUB_ISSUE_LINK}}

and

- [ ] Does a heap comparison using Chrome Developer Tools indicate a memory leak? (Describing this process is beyond the scope of this document.) Test on a version built using `grunt --minify.mangle=false`. Compare to testing results done by the responsible developer. Results can be found in {{GITHUB_ISSUE_LINK}}.

I didn't see issues like this in the density-buoyancy-common repo, @jonathanolson can you please advise?

**Comment by jonathanolson** [comment]
https://github.com/phetsims/density/issues/70 is the dedicated performance issue.

**Comment by jonathanolson** [comment]
Credits issue is https://github.com/phetsims/density/issues/31.

**Comment by jonathanolson** [comment]
Added the above issues (or mentioned existing ones), and I'll handle the memory testing again. Does that look sufficient?

**Comment by samreid** [comment]
The side issues look great, thanks!  Closing.
