### ISSUE TITLE
Instrument `resetBoatSceneButton.selfVisibleProperty`

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density-buoyancy-common#240]
For https://github.com/phetsims/buoyancy/issues/51

The `resetBoatSceneButton` only appears in the Boat Scene, so the model needs to control its `visibleProperty`. Clients should have a way to hide it with `selfVisibleProperty`, as we do with other scene-specific controls such as `customBottleDensityNumberControl`.

<img width="386" alt="image" src="https://github.com/phetsims/density-buoyancy-common/assets/8419308/80a647ce-8263-4f4e-b76c-d74896d77f1e">

Assigning the dev team.

**Comment by AgustinVallejo** [comment]
Tossing back to @arouinfar for review

**Comment by arouinfar** [comment]
Thanks @AgustinVallejo. Looks good on main, closing.
