### ISSUE TITLE
Fluid Displaced AccordionBox data should be instrumented

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density-buoyancy-common#242]
For https://github.com/phetsims/buoyancy/issues/51

The data in the Fluid Displaced AccordionBox is not instrumented, but should be.
<img width="193" alt="image" src="https://github.com/phetsims/density-buoyancy-common/assets/8419308/03bb59f7-7ee7-410a-b609-153589dc5b2a">

Please create properties for the displaced volume and weight. 
- [x] `displacedVolumeProperty`
- [x] `displacedWeightProperty`
- [x] Both should be `phetioFeatured: true`

It seems like `buoyancy.labScreen.view.fluidDisplacedAccordionBox` would be a reasonable home for these Properties, but if they need to go elsewhere, please add LinkedProperties to the AccordionBox so users can find the data.

Assigning to the dev team.

**Comment by AgustinVallejo** [comment]
Assigning back to @arouinfar

**Comment by arouinfar** [comment]
Looks great, thanks @AgustinVallejo. Closing.
