### ISSUE TITLE
Figure out how to sort bottle/boat displacedVolumeProperty

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/density-buoyancy-common#245]

**Comment by samreid** [comment]
Can you please elaborate on the problem? The comment in https://github.com/phetsims/buoyancy/issues/180 is unclear.

**Comment by zepumph** [comment]
Both bottle and boat have a displacedVolumeProperty, one is instrumented, phet-io design wants that one renamed, and in general it isn't clear why we have factored this property out. Furthermore, our current definition of this property "volume of the contents", is redundant to bottle.interiorVolumeProperty. So we are quite confused about all of it!

**Comment by zepumph** [comment]
@samreid @AgustinVallejo and I are still a bit confused about how to proceed. 

We found out:
* Bottle.displacementVolumeProperty is the displaced volume for the entire bottle, not just the contents.
* Boat.displacementVolumeProperty is the displaced volume for just the amount of fluid that the boat can hold.

Maybe a better name for this would be capacityVolumeProperty?

Here are some questions to discuss with designers.

- The slider that controls to volume of the boat, should that volume include the hull volume, or not?
- If there is already a label called "Boat Volume", do we need the Property controlling the slider to match that name?

**Comment by zepumph** [comment]
TODO from discussion with the whole buoyancy team

- [x] add "materialInside" to bottle:

```
materialInside
	volumeProperty
	massProperty
	materialProperty
        customDensityProperty
```

- [x] `displacementVolumeProperty` -> `maxVolumeDisplacedProperty` (for bottle and boat).
- [x] Lots of doc in code needs to be updated around "DISPLACEMENT" because it isn't just about what it can hold, but also the hull too.

**Comment by zepumph** [comment]
working on this now

**Comment by zepumph** [comment]
Fixed and ready for review.

**Comment by arouinfar** [comment]
>  `displacementVolumeProperty` -> `maxVolumeDisplacedProperty` (for bottle and boat).

I see this for the boat, but not the bottle. I'm not convinced it's relevant to the bottle, since `bottle.volumeProperty` is effectively the maximum displaced volume. 

Otherwise, the changes look good on main. I think this is probably good to close, but sending back to @zepumph to confirm.

**Comment by zepumph** [comment]
Yes, thanks. All good here, it exists in both, but isn't instrumented in the bottle since it is constant. CLosing
