### ISSUE TITLE
Add stretch feature to BooleanToggleNode

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/density-buoyancy-common#246]
This part specifically:

https://github.com/phetsims/density-buoyancy-common/blob/3d1fb58fa9b5b39fad4c73a90d4a47912aaa5b38/js/common/view/MaterialMassVolumeControlNode.ts#L373-L379

**Comment by samreid** [comment]
Please elaborate? It's unclear what stretching a ToggleNode should do, unless the point is that the stretch would cascade through to the descendants?

**Comment by AgustinVallejo** [comment]
To elaborate: In order to address this in https://github.com/phetsims/buoyancy/issues/180:
> There are dynamic layout issues with the Block's DensityMassNumberControl

Where the mass number display, by default shrinks if we hide the slider. This was solved easily for Volume Number Control, since it's just the child of a VBox. But the Mass ones are, in some screens, contained in the BooleanToggleNode, which does not support (As far as I could tell) layout options, more specifically, stretch: true.

**Comment by zepumph** [comment]
I discussed this issue with @jonathanolson, and he recommended using AlignGroup with align:'center' around all our Nodes for the ToggleNode. This demonstrates the idea [in this example](http://localhost:8080/scenery/tests/sandbox.html?script=%2F%2F%20import%20sun%2Fjs%2FBooleanToggleNode%0A%2F%2F%20import%20sun%2Fjs%2Fbuttons%2FRectangularStickyToggleButton%0A%0Aconst%20alignGroup%20%3D%20new%20AlignGroup()%3B%0A%0Aconst%20trueNode%20%3D%20alignGroup.createBox(%20new%20Rectangle(%200%2C%200%2C%20100%2C%20100%2C%20%7B%20fill%3A%20%27red%27%20%7D%20)%20)%3B%0Aconst%20falseNode%20%3D%20alignGroup.createBox(%20new%20VBox(%20%7B%0A%20%20grow%3A%201%2C%0A%20%20stretch%3A%20true%2C%0A%20%20children%3A%20%5B%20new%20Rectangle(%200%2C%200%2C%2020%2C%2020%2C%20%7B%20sizable%3A%20true%2C%20fill%3A%20%27blue%27%2C%20layoutOptions%3A%20%7B%20minContentWidth%3A%2050%2C%20minContentHeight%3A%2050%20%7D%20%7D%20)%20%5D%0A%7D%20)%2C%20%7B%0A%20%20align%3A%20%27stretch%27%0A%7D%20)%3B%0Aconst%20booleanProperty%20%3D%20new%20BooleanProperty(%20true%20)%3B%0A%0Aconst%20toggleNode%20%3D%20new%20BooleanToggleNode(%20booleanProperty%2C%20trueNode%2C%20falseNode%2C%20%7B%7D%20)%3B%0A%0Aconst%20toggleButton%20%3D%20new%20RectangularStickyToggleButton(%20booleanProperty%2C%20false%2C%20true%2C%20%7B%20size%3A%20new%20Dimension2(%2050%2C%2050%20)%7D%20)%3B%0A%0A%0Ascene.addChild(%20new%20HBox(%20%7B%0A%20%20spacing%3A%2010%2C%0A%20%20children%3A%20%5B%20toggleNode%2C%20toggleButton%20%5D%0A%7D%20)%20)%3B%0A%0A). This makes sense that BooleanToggleNode shouldn't be responsible for this layout, and JO mentioned that most cases don't want to automatically pass this behavior through to children.

**Comment by AgustinVallejo** [comment]
That was really helpful, thanks! The desired stretch has been achieved. Back to @zepumph for a swift review before closing. But the above commit is pretty much JO's example applied to this context.
