### ISSUE TITLE
Mystery fluids should be called 'Fluid A' rather than 'Density A'

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density-buoyancy-common#248]
Related to https://github.com/phetsims/buoyancy/issues/51

During today's design meeting with @DianaTavares @AgustinVallejo @samreid @zepumph, we decided to call the mystery fluids 'Fluid A', etc. They are currently named 'Density A' etc. 

<img width="282" alt="image" src="https://github.com/phetsims/density-buoyancy-common/assets/8419308/c0be4eea-f37d-4401-b79d-b67e4371d36b">
<img width="207" alt="image" src="https://github.com/phetsims/density-buoyancy-common/assets/8419308/db2c2954-ae4f-4201-8b14-53be455dd7d4">

We'll need to change string in the ListBox, associated phetioID, and string key to use the 'fluid' language.

**Comment by AgustinVallejo** [comment]
Pushing this change. What's left is changing the string keys, as I would like to do it with a more experienced developer to avoid translation mishaps.

**Comment by AgustinVallejo** [comment]
Moving that string key part to https://github.com/phetsims/density-buoyancy-common/issues/183. Assigning back to @arouinfar for review.

**Comment by arouinfar** [comment]
Thanks @AgustinVallejo! Looks good in main, closing.
