### ISSUE TITLE
Rename `blocksModeRadioButtonGroup` to `blockSetRadioButtonGroup`

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density-buoyancy-common#249]
For https://github.com/phetsims/buoyancy/issues/51

The `blocksModeRadioButtonGroup` on the Compare Screen is inconsistently named.
<img width="118" alt="image" src="https://github.com/phetsims/density-buoyancy-common/assets/8419308/bf7f32b3-bf0a-4662-93ba-bf12a1e2f447">

While we typically try to match the string used in the sim, `blocksRadioButtonGroup` lacks some helpful context. The underlying property is `blockSetProperty` which designers like, as it makes the tree easier to understand.\
<img width="202" alt="image" src="https://github.com/phetsims/density-buoyancy-common/assets/8419308/99b0d755-a6d7-499c-af90-5a7b7e1faa95">

For consistency, let's rename `blocksModeRadioButtonGroup` to `blockSetRadioButtonGroup`.

Assigning to the dev team.

**Comment by AgustinVallejo** [comment]
While doing this I discovered that the One vs Two Blocks radio button group had the same tandem name as 'blocksModeRadioButtonGroup'. It was changed as part of https://github.com/phetsims/buoyancy/issues/86

>  Rename blocksRadioButtonGroup => blocksModeRadioButtonGroup. Rename the classes, variables and tandems. 7+ occurrences

Wondering if that should change as well.

**Comment by zepumph** [comment]
The code and studio tree both support these definitions:

"block set" is the option for same mass/volume/density, and block mode is the scene selection for one vs two blocks visible. 

I think it is good the way it is, and this issue was in part to fix how "mode" was overloaded.

**Comment by arouinfar** [comment]
The changes look good on main, thanks!

> I think it is good the way it is, and this issue was in part to fix how "mode" was overloaded.

I agree. I don't believe any further changes are needed, so closing.
