### ISSUE TITLE
Make it possible for clients to customize the density of mystery fluids/materials

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density-buoyancy-common#250]
For https://github.com/phetsims/buoyancy/issues/51

Discussed in design meeting with @DianaTavares @AgustinVallejo @samreid @zepumph 

We would like to support adjusting the density of mystery materials/fluids. We cannot change the density directly in `materialProperty` (that only works when the identifier is `null`), so we would like to create an adjustable `densityProperty` that would live under global. 

Proposed tree structure:

```
- global
  - model
    - materials
       - fluidA
           densityProperty
           *colorProperty      // LinkedProperty, colors are usually in global.view.colors
           *stringProperty
       etc.
```

This structure provides the flexibility to instrument any material, not just the mysteries. At this time, we are not introduced in allowing clients to change the density of other known materials such as wood or brick. 

Assigning to the dev team.

**Comment by arouinfar** [comment]
> This structure provides the flexibility to instrument any material

This got me thinking. Could we do the same for 'CUSTOM'? Customizing custom blocks is difficult because the mass/volume interdependency is severed. In Density, we did the somewhat sketchy thing of telling clients to edit the 'density' field of the `materialProperty`, but if we instrumented `materials.custom.densityProperty` we could make all `materialProperty` read-only (which seems like the safest option).

**Comment by samreid** [comment]
We have an existing feature for `buoyancy.applicationsScreen.model.objects.bottle.customDensityProperty`. Is that a good pattern? Should it be applied elsewhere? Asking @arouinfar but also tagging @zepumph since we were working on `customDensityProperty` in other issues today.

**Comment by zepumph** [comment]
It seems a bit different to me. Probably the easiest solution is to have a material's density become an instrumented Property in these cases. The challenge will be in making sure that all spots that read from `Material.density` are prepared to notice when it changes.

**Comment by zepumph** [comment]
The dev team is surprised just how challenging this request is going to be to implement. The sim is very hard coded into a pattern of treating Materials as immutable (can't change), and the only ones that have support for changing simply are custom. 

Possible solutions:
1. Rewrite the whole way in which densities are supported in this sim. Material gets a `densityProperty`, and usages need to update when the` materialProperty` changes, AND whenever the selected material's density changes. This will be an incredible amount of work.  There are 55 usages of `.density` that assume that this density won't change.  
2. A slightly more "workaround"ish implementation where we treat mystery materials more like custom materials. There also 15 spots where we are checking and doing special logic for a custom material, but it doesn't really map to mystery materials. We don't recommend this. 
3. Query Parameters. We could support this pretty easily with something like `?materialXDensity=100`. This comes with the drawbacks that query parameters often do, but the PhET-iO state won't overwrite these values (like for the standard phet-io wrapper), so this would be possible.
4. Wait until a client requests this feature before adding this.

**Comment by zepumph** [comment]
This may get much easier over in https://github.com/phetsims/density-buoyancy-common/issues/256. Let's mark this on hold until then.

**Comment by zepumph** [comment]
#256 has been pushed to main, and is in much better shape to tackle this issue. We now have full control over the density of all materials. Instrumenting every material is now required for supporting state, so likely we will want to proceed by featuring the mystery material densityProperties, and probably nothing else. These static materials live under `global.model.materials`. Next steps are likely to discuss the best path forward synchronously, to make sure we are all on the same page.

**Comment by zepumph** [comment]
- [ ] Review of new mutable materials in the studio tree, once https://github.com/phetsims/density-buoyancy-common/issues/256 and side issues are complete.

**Comment by zepumph** [comment]
Let's give this issue to @arouinfar when the new material feature is ready for PhET-iO review.

**Comment by zepumph** [comment]
Similar to https://github.com/phetsims/density-buoyancy-common/issues/228, this issue is ready for review. Please note that we have not yet completed #237, but otherwise, most everything should be working now. In general, you select the material with the block's materialProperty. You select the custom density with the `materialProperty.customMaterial.densityProperty`. All "static" materials are instrumented under `global.model.materials`, and you can change all of their densities with their densityProperty.

Happy to discuss more, and I'm preemptively sorry for any way that this changeset from #256 has upset the current phet-io design. Good luck out there.

**Comment by arouinfar** [comment]
Thanks, everyone! The changes are feeling really good. It is now possible to customize the mystery materials as requested. There's still some tree cleanup to do, but let's track that over in #282.
