### ISSUE TITLE
Scale icon regression: Black background

### ISSUE THREAD

**Issue by zepumph** [phetsims/density-buoyancy-common#252]
<img width="629" alt="image" src="https://github.com/phetsims/density-buoyancy-common/assets/6856943/be1c98c0-3d5a-4c59-b8c5-70836dd44d88">

**Comment by AgustinVallejo** [comment]
I believe this is done. A background was being passed as null, where the default was rgb(1,1,1). I just removed the null part.

A really simple review would do here before closing. @zepumph

**Comment by zepumph** [comment]
Providing null to the icon generation is supposed to indicate a transparent background. While providing a white background fixes the immediate problem, it doesn't recognize the underlying issue that likely could effect other usages that want to try to render a THREE js stage to a canvas in mobius.

I traced back the bug to

**Comment by zepumph** [comment]
Providing null to the icon generation is supposed to indicate a transparent background. While providing a white background fixes the immediate problem, it doesn't recognize the underlying issue that likely could effect other usages that want to try to render a THREE js stage to a canvas in mobius.

I traced back the bug to this commit:
https://github.com/phetsims/mobius/commit/1961b1f8853ef0597140c6e728c66c278c410d28 in https://github.com/phetsims/density-buoyancy-common/issues/81

@samreid and I were interested in what I consider to be the "main" rendering case, where we would like performance and the assumption that all pixels will be updated by the next render, but for icon generation, this provided a challenge. Now that we see how poorly our change effects spaces that want to keep a transparent background, I at least want to provide an option here. Commits coming soon.

**Comment by zepumph** [comment]
Alright. I believe that does it. When I generated icon images, and then copied the newly rendered scale into the committed png file, there were no changes. @AgustinVallejo can you please take a look?

I also confirmed that the above change still fixes https://github.com/phetsims/density-buoyancy-common/issues/81.

**Comment by AgustinVallejo** [comment]
I double checked this and seems nice. Thanks! Closing
