### ISSUE TITLE
Review and update phetioDocumentation of volume Properties

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density-buoyancy-common#253]
Related to #245 

There are lots of different `volumeProperty` in this suite. We should review and update the `phetioDocumentation` to better explain what is included in the various volumes. Self-assigning for initial review.

**Comment by arouinfar** [comment]
I reviewed all instances of `volumeProperty` across the suite, including related Properties like `maxVolumeDisplacedProperty`. Overall, the current phetioDocumentation is accurate and appropriate. I only found one place where it would be helpful to add documentation:

- [x] `fluid.displacedVolumeProperty`: Volume of fluid displaced by objects in the pool.

Assigning to @AgustinVallejo.

**Comment by AgustinVallejo** [comment]
Done! It was easy so closing
