### ISSUE TITLE
Move adjustableMaterial to a subtype

### ISSUE THREAD

**Issue by zepumph** [phetsims/density-buoyancy-common#255]
This is only to be used by the density mystery screen, and so does not belong in Mass.ts. In fact, @samreid and I have been greatly confused by its presence there for quite some time, and I even tried to (mistakenly) use it for B:B: explore screen blocks, only to be thwarted and need to revert over in https://github.com/phetsims/density-buoyancy-common/issues/254.

On hold until https://github.com/phetsims/density-buoyancy-common/issues/254 is complete.

**Comment by samreid** [comment]
We ultimately deleted `adjustableMaterial`, so it seems this issue can be closed.
