### ISSUE TITLE
Updates to `numberControl*Property` metadata

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density-buoyancy-common#259]
In https://github.com/phetsims/buoyancy/issues/51#issuecomment-1979357490 the devs asked:

> Why is `massNumberControl.numberControlMassProperty` featured? Same for volume. Should they be featured, a doc ought to be written for them.

The `numberControlMassProperty` and `numberControlVolumeProperty` appear on screens with controls similar to this:
<img width="175" alt="image" src="https://github.com/user-attachments/assets/c4775d93-8411-4fcf-a29a-21bd51ae1279">

Over in https://github.com/phetsims/density/issues/155 I asked for these Properties to be uninstrumented, but the conclusion at the time was that they were necessary for State. 

In a recent design meeting with @AgustinVallejo @samreid @zepumph @DianaTavares we decided to double-check that these Properties are necessary to leave instrumented. And if so, we'd like to update the following metadata.

- [x] `phetioDocumentation`: For internal use only.
- [x]  `phetioFeatured: false`

Assigning to the dev team.

**Comment by AgustinVallejo** [comment]
I added the second request in the above commit. I'm not sure if this is needed for state... However, both these properties have an option of `phetioState: false` so not sure what that means exactly... Leaving this open for discussion with the other devs to see if the actual way forward is uninstrumenting.

**Comment by AgustinVallejo** [comment]
Spoke with @samreid and @zepumph and we decided to uninstrument and test thoroughly.
