### ISSUE TITLE
What is happening in `new DynamicProperty( this.leftBarrierViewPointProperty ).lazyLink( resizeBarrier );`?

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#26]
During code review #5, I noticed:

```js
new DynamicProperty( this.leftBarrierViewPointProperty ).lazyLink( resizeBarrier );
```

How is this different from 

```js
this.leftBarrierViewPointProperty.lazyLink( resizeBarrier );
```

I saw a total of 3 DynamicProperty instantiations this applies to.

**Comment by jonathanolson** [comment]
leftBarrierViewPointProperty/rightBarrierViewPointProperty are Properties of Properties, and we need to also listen to the secondary Property for updates. Should those fields be renamed to something with `...PropertyProperty` to better indicate that?

**Comment by samreid** [comment]
I don't understand why `rightBarrierViewPointProperty` should be a `Property<Property>`.  Isn't it a constant value depending on the screen?  For instance, BuoyancyExploreScreenView always has:

```js
    this.rightBarrierViewPointProperty.value = new DerivedProperty( [ this.rightBox.boundsProperty, this.visibleBoundsProperty ], ( boxBounds, visibleBounds ) => {
      return new Vector2( boxBounds.left, visibleBounds.centerY );
    } )
```

Why is this designed to be dynamic?

**Comment by jonathanolson** [comment]
> Why is this designed to be dynamic?

It's easier/simpler to design it that way, in my opinion. No fragility of "when after super() have we properly setup the Property so that NOW we can start to listen to it". Is there a better way?

**Comment by jonathanolson** [comment]
> Isn't it a constant value depending on the screen?

It does eventually end up pointing to a specific Property depending on the screen, yes.

**Comment by samreid** [comment]
I noticed some places use `value.value` and some use `DynamicProperty`.  Are all of those usages appropriate, or should some switch?  For me and perhaps other developers, `DynamicProperty.link` may be more opaque than using `value.value`.

**Comment by samreid** [comment]
@jonathanolson and I discussed this, and thought the documentation was the best way to address this, closing.
