### ISSUE TITLE
'Scene' language on Applications screen is unclear

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density-buoyancy-common#262]
For https://github.com/phetsims/buoyancy/issues/51

The RadioButtonGroup that swtiches between the bottle and  boat representations is the `sceneRadioButtonGroup` and it is controlled by the `sceneProperty`. @DianaTavares and I think "scene" is a bit jargon-y and too vague in this context. We took inspiration from Density's `blocks.modeProperty` and propose some renames.

@AgustinVallejo please rename the following:

- [x] `sceneProperty` > `applicationModeProperty`
- [x] `sceneRadioButtonGroup` > `applicationModeRadioButtonGroup`
- [x] ResetBoatSceneButton > ResetBoatButton

**Comment by AgustinVallejo** [comment]
Back to @arouinfar for review

**Comment by arouinfar** [comment]
Looks good on main, thanks @AgustinVallejo! Closing.
