### ISSUE TITLE
Instrument `zoomLevelProperty` and make `vectorZoomProperty` read-only

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density-buoyancy-common#264]
For https://github.com/phetsims/buoyancy/issues/51

The vector zoom levels scale with a factor of 2, following the pattern 2<sup>-n</sup> with n  ranging [0, 7]. The `vectorZoomProperty` exposes the precise value, e.g. 0.0625, but does not make use of `validValues` or any guarding against clients passing in bad values. 

Even with proper validation, `vectorZoomProperty` is not user-friendly. I propose that we follow the pattern used Geometric Optics, which derives `zoomScaleProperty` (equivalent to `vectorZoomProperty`) from the integer `zoomLevelProperty` that is user-controlled. This way, clients set the index of the zoom level rather than the zoom level itself.

**Comment by AgustinVallejo** [comment]
Back to Amy for review

**Comment by arouinfar** [comment]
Thanks @AgustinVallejo the updated behavior looks good. I noticed that the implementation only exposes the integer zoom index, not the actual scale. For the Buoyancy/Density suite, that seems appropriate. The actual vector lengths are irrelevant, and users have no notion of measurable distances.

That said, I'd like to update the `phetioDocumentation` to:
Controls the zoom level of the force vectors. Smaller values are more zoomed out.

Back to @AgustinVallejo

**Comment by AgustinVallejo** [comment]
Done! Closing :)
