### ISSUE TITLE
ColorProfile is incomplete and also contains unused colors

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density-buoyancy-common#265]
While reviewing the color profile for https://github.com/phetsims/density-buoyancy-common/issues/261, I noticed that it contains unused colors and is missing others. Devs should review and verify that the colors are still used in density-buoyancy-common sims.

Candidates for removal:
- [x] `materialAir` -- It's black with an alpha of 0 (making it invisible). Changing it in the Color Editor doesn't seem to do anything.
- [x] `materialLead` -- Was removed in https://github.com/phetsims/buoyancy/issues/106
- [ ]  `compareOchre` -- It's not used on any of the Compare screens, but it's possible that Density's Mystery screen uses it for the Random set of blocks. If so, I propose renaming it to `mysteryOchre` instead of deleting it.

Missing:
- [x] `materialO`
- [x] `materialP`
- [x] `materialV`
- [x] `materialW`

Other inconsistencies:
- [x] Mystery fluids are named `materialDensityA` but should probably be `materialFluidA`, etc. to be consistent with the changes in https://github.com/phetsims/density-buoyancy-common/issues/248
- [x] Some colors only appear in one sim. Do they all really belong in density-buoyancy-common? I generally only see shared colors live in common repos (e.g. MSaB & soccer-common, Kepler's Laws and solar-system-common).

**Comment by zepumph** [comment]
From https://github.com/phetsims/density-buoyancy-common/issues/275:



- [x] We want to uninstrument color Properties in density. They are read only anyways, and they aren't the way to change the colors of blocks.

**Comment by zepumph** [comment]
> * Some colors only appear in one sim. Do they all really belong in density-buoyancy-common? I generally only see shared colors live in common repos (e.g. MSaB & soccer-common, Kepler's Laws and solar-system-common).

This is an unfortunate side effect of having all code for the whole suite in the common repo. We can still decide what to instrument on a sim by sim basis over in https://github.com/phetsims/density-buoyancy-common/issues/261, but it would be best to keep all colors in the common profile.

**Comment by AgustinVallejo** [comment]
> * `compareOchre` -- It's not used on any of the Compare screens

That material is used in the Compare screen when you change the masses, so they go into custom mode. It's hard to notice since the density filter turns the ochre mostly brown or black in most cases, but here it is in minimum density:
![image](https://github.com/user-attachments/assets/5a9e7a4f-55cb-4960-ba39-22159361122a)

**Comment by AgustinVallejo** [comment]
> * We want to uninstrument color Properties in density

@zepumph For this, those properties were doing `density? createTandem : OPT_OUT`. I just left the opt out. Should I just delete the tandem part?

**Comment by AgustinVallejo** [comment]
Back to @arouinfar for review

**Comment by zepumph** [comment]
> @zepumph For this, those properties were doing `density? createTandem : OPT_OUT`. I just left the opt out. Should I just delete the tandem part?

I see that there are a fair number of spots specifying `Tandem.OPT_OUT`. This isn't needed, so likely we can remove a lot of tandem options declarations.

**Comment by arouinfar** [comment]
Thanks @AgustinVallejo. The changes all look good on main.

> That material is used in the Compare screen when you change the masses, so they go into custom mode.

Got it! Thanks for looking into `mysteryOchre`. 

Looks like there may still be some work left for @AgustinVallejo in this issue, so back to him.

**Comment by AgustinVallejo** [comment]
No more work, ready to disintegrate this issue.
