### ISSUE TITLE
CompareBlockSetModel should be improved

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#273]
This issue will aggregate TODOs from other issues. CompareBlockSetModel is significantly underdocumented and very confusing. It is unclear when the `massProperty` and `densityProperty` and `volumeProperty` are used. It uses a different pattern for managing the material property. It has an awkward `merge` oriented customization approach.  I think it deserves its own issue, and I'll point things over here.

**Comment by samreid** [comment]
On the density mystery screen, we saw:

```
materialProperty
density.mysteryScreen.model.blockSets.set1.block1A.materialProperty

Initial State:
{
  "value": {
    "phetioID": "density.optionalTandem"
```

We believe that optionalTandem should be instrumented.

**Comment by AgustinVallejo** [comment]
In studio, we looked at the compare screens and it seems odd that you can "change" the density via studio (it doesn't even change). `materialProperty.customMaterial` is not used in these screens. Possibly good to start looking here for uninstrumenting.

https://github.com/phetsims/density-buoyancy-common/blob/9580de6d8d61e929c24ede7817e2d07aad8358bf/js/common/model/CompareBlockSetModel.ts#L170

Also, the blocks are listening to these materials when they seem "custom":
![image](https://github.com/user-attachments/assets/2a5ba9a5-7403-4876-82ab-811825e1fbbc)

**Comment by zepumph** [comment]
- [ ] Also noting that it seems like for density compare, we should be able to change the underlying color that darkens/lightens based on density.

**Comment by zepumph** [comment]
Alright. Lots of good stuff has gone on here. Now we don't create materialProperty and densityProperty instances outside of the cubes, and just use the ones made in the Cube. Then we don't have to keep things in sync. 

There is still work to be done with PhET-iO instrumentation of colors, but I'd like to do that over in https://github.com/phetsims/density-buoyancy-common/issues/268. Closing
