### ISSUE TITLE
Delete canRotate

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#277]
`canRotate` seems unused. Can we delete it?

**Comment by AgustinVallejo** [comment]
Did this but would benefit from another pair of eyes. The code removal was pretty straightforward, but I had to change `MassIO` because it had a stateKey associated with canRotate. Added the following migration rule, and it seems to be congrulatory, but again, assigning back to @samreid for review:
```
    new ChangeStateKeyIOType( 'MassIO', 'tag', 'MassTagIO', mass => {
      delete mass.canRotate;
    } )
```

**Comment by zepumph** [comment]
Looks great, thanks.
