### ISSUE TITLE
Cannot Studio autoselect canMove:false Masses (like Scales)

### ISSUE THREAD

**Issue by zepumph** [phetsims/density-buoyancy-common#278]
This bug was discovered while working on https://github.com/phetsims/density-buoyancy-common/issues/270. It is because of this code here:

https://github.com/phetsims/density-buoyancy-common/blob/bf231d321aff32ab1cbd2106009a772843a0d220/js/common/view/DensityBuoyancyScreenView.ts#L165-L168

`getMassViewUnderPoint` respects canMove and inputEnabledProperty because it is mostly used in the input listener for dragging masses. We should allow autoselect for unmovable instrumented masses.

**Comment by samreid** [comment]
This was also reported in #310, I'll continue there. Closing as duplicate
