### ISSUE TITLE
Should Mystery_* have a better naming logic?

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/density-buoyancy-common#279]
| Name       | Material | Density (kg/m^3) | Screen              |
|------------|----------|------------------|---------------------|
| MATERIAL O | Human    | 950              | Lab                 |
| MATERIAL P | Diamond  | 3510             | Lab                 |
| MATERIAL R | Ice      | 919              | Applications Bottle |
| MATERIAL S | Lead     | 11342            | Applications Bottle |
| MATERIAL V | Titanium | 4500             | Applications Boat   |
| MATERIAL W | Mercury  | 13593            | Applications Boat   |
| MATERIAL X | Pyrite   | 5010             | Explore             |
| MATERIAL Y | Gold     | 19320            | Explore             |

This is how mystery materials are sorted throughout the sim. It feels weird that they are not ordered based on screens, and they don't follow an alphabetical sequence. Do we want some changes on that?

**Comment by zepumph** [comment]
We like:
* Explore: R S 
* Lab: T U 
* Application Bottle: V W 
* Application Boat: X Y

We thought about numerals, but don't want to:

<details>

```
I II
III IV
V VI
VII VIII

1 2
3 4
5 6
7 8

**Comment by zepumph** [comment]
* String keys
* documentation table
* color names

**Comment by AgustinVallejo** [comment]
- [x] Delete string keys O, P. The rest are just going to change order
- [x] Mystery materials are currently instrumented in D and B:B. Should we uninstrument? Unfeature? We see some downsides to uninstrumenting, and un-featuring could be the second easiest solution, right after leaving it as it is. Will ask @arouinfar 
- [x] documentation table

**Comment by AgustinVallejo** [comment]
Passing this back to @arouinfar to double check and close :)

**Comment by arouinfar** [comment]
Looks good on main, thanks @AgustinVallejo! Closing.
