### ISSUE TITLE
Usage of scenery/layout

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#28]
During #5 I observed that density-buoyancy-common uses scenery/layout quite a bit.  The behavior seems good and it is the right direction to go in, but I wanted to check the status of scenery/layout, since I saw several files that had numerous TODOs, missing documentation, etc.  Is this the first sim that will be published with extensive usage of scenery/layout?  Is it ready to be in production code?  Is the team aware of its status?  Are we expecting it to change significantly once it is more thoroughly reviewed?  Should it be reviewed as part of #5?

**Comment by jonathanolson** [comment]
I believe @kathy-phet noted that this should not block Density, but will be good to do sometime. Marking as deferred and unassigning.

**Comment by AgustinVallejo** [comment]
The new scenery/layout system is in production since this issue was created. Closing.
