### ISSUE TITLE
Do we need these order dependencies marked?

### ISSUE THREAD

**Issue by zepumph** [phetsims/density-buoyancy-common#280]
With all that has gone on in #256, we may not need these anymore. Promoting todo:

https://github.com/phetsims/density-buoyancy-common/blob/e39c558536b612994966232b6fa7b47d17a54173/js/common/model/CompareBlockSetModel.ts#L154-L156

**Comment by samreid** [comment]
I recall removing that order dependency and still seeing the same problem. Also, I feel this ordering may be related to https://github.com/phetsims/buoyancy/issues/67

**Comment by samreid** [comment]
Since this order dependency is still needed, we should keep it. Closing.
