### ISSUE TITLE
Update numberControl when changing default gravity values from studio

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/density-buoyancy-common#281]
Currently, if you have Earth gravity selected and you change the gravityValue from studio to something else (i.e 10), the number control does not update, and shows the old value.

**Comment by AgustinVallejo** [comment]
In the above commit I:
1. Moved the MappedWrappedProperty (MWP) locking `isChangingToPredefinedValueLock` from the ComboNumberControl into the class declaration, seems more consistent. However this might or might not introduce some logic changes I didn't see in the sim:
    - In the doc it says the lock happens "Often, but not always", but it seemed to me it was indeed happening always. Left a TODO regarding that. I'd suppose the times it wasn't happening was outside ComboNumberControl, but those MWP only lived in relation to the ComboNumberControls. 
    - In the doc it also said something pretty specific to Explore Screen, and it didn't read as an example. But the logic doesn't suggest anything Explore Screen related, so reworded it.
 2. Left a TODO asking for better documentation on MWP, all those customProperty, dynamicProperty and so, are very esoteric and it was pretty hard to guess the structure. customProperty has a .valueProperty and .value which is a gravity or fluid, but dynamicProperty only has .value which is a number???
 3. Linked all the availableValues of the MWP with the custom property, see below. This is the part that achieves the functionality desired in this issue, that is, changing the selected gravity/fluid value from studio also updated the number display, without going into custom. And changing from studio an availableValue that isn't currently selected just doesn't update anything. This works, but the abstraction on MWP makes me pretty confused, and I'm not totally certain this is the right fix, as you can see there's like `valueProperty.valueProperty.value`. So as my second point says, it's confusing.

https://github.com/phetsims/density-buoyancy-common/blob/aa3a6d77e986ac61a85438ba20dc9996f65b7b82/js/common/model/MappedWrappedProperty.ts#L76-L84

**Comment by AgustinVallejo** [comment]
Assigning @samreid for review. Mainly to green-light items (1) and (3). I could work on the documentation, but need more info about this class.

**Comment by AgustinVallejo** [comment]
Changing title as it is now not possible to change a default fluid's density via phetio. But we do want the default gravities to be writable.

**Comment by samreid** [comment]
I think I understand @AgustinVallejo's proposal to move the logic from one UI component to the model. It seems reasonable but I'm having difficulty thinking through corner case behavior. I'll add one commit that duplicates a small amount of code but hopefully is more understandable. After that, I recommend we meet up and/or consult with @zepumph.

**Comment by samreid** [comment]
@AgustinVallejo and I worked on this and I believe it is ready to close. Over to @AgustinVallejo to confirm.
