### ISSUE TITLE
Cleanup of `global.model.materials`

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density-buoyancy-common#282]
Related to https://github.com/phetsims/buoyancy/issues/51.

I reviewed the updated materials for https://github.com/phetsims/density-buoyancy-common/issues/250, and identified some needed cleanup. 

- [x] Move sand to `materials.solids`
- [x] Rename `mysteryY` > `materialY`. 
- [x] All non-custom, non-mystery materials should have a read-only density.
- Uninstrument all materials that aren't user-selectable: 
   - [x] air
   - [x] boatHull
   - [x] diamond
   - [x] glass
   - [x] human
   - [x] lead
   - [x] titanium
- [x] Materials should only appear in the trees of relevant sims. (No non-water fluids in Density, for example.)

Over to @AgustinVallejo. Please let me know if you have any questions.

**Comment by AgustinVallejo** [comment]
I believe this is done, back to @arouinfar to review.

**Comment by samreid** [comment]
Uninstrumenting the boat body caused the CT error which is also tracked in https://github.com/phetsims/density-buoyancy-common/issues/301.  I'll close that issue and address it here

**Comment by arouinfar** [comment]
Overall, the changes look good. If I'm not mistaken, @samreid reinstrumented the boat's material, which in retrospect, seems like useful information for the clients. Thanks!

@samreid @AgustinVallejo can you please rename `boatBody` to `boatHull`? It was previously `boatHull`, which is the more appropriate terminology.

**Comment by AgustinVallejo** [comment]
Renamed the tandem, closing. Also, thanks @samreid for fixing the CT issue! Didn't catch that
