### ISSUE TITLE
Mark buoyancy and buoyancy-basics as phetioDesigned: true, and add "compareDesignedAPIChanges": true

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#289]
From #123 .

Mark buoyancy and buoyancy-basics as phetioDesigned: true

Additionally:

> In main, mark package.json's add "compareDesignedAPIChanges": true, to the "phet-io" section. This will add it to perennial/data/phet-io-api-stable/ (after the automatic nightly grunt generate-data). This will start CT tests and incorporate the sim for other tasks that update or check the APIs.

**Comment by samreid** [comment]
Implemented in the commits, @zepumph can you please review?

**Comment by zepumph** [comment]
Great to know this has been done. Congratulations all!
