### ISSUE TITLE
Are any significant chunks of code duplicated? In addition to manual identification, tools include: WebStorm

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#291]
Discovered during #123, there are significant parts of the code that are duplicated.  For instance:

Duck.ts and Ellipsoid.ts has this identical code:

```ts
getDisplacedVolume( fluidLevel: number ): number {
    if ( fluidLevel <= this.stepBottom ) {
      return 0;
    }
    else if ( fluidLevel >= this.stepTop ) {
      return this.stepMaximumVolume;
    }
    else {
      const ratio = ( fluidLevel - this.stepBottom ) / ( this.stepTop - this.stepBottom );

      return this.stepMaximumVolume * ratio * ratio * ( 3 - 2 * ratio ); // 4/3 * pi * a * b * c * t^2 * ( 3 - 2t )
    }
  }
```

Likewise VerticalCylinder and Cuboid have identical `getDisplacedVolume` aside from a comment change.

Here is a snapshot of many high cost duplicates discovered by using WebStorm=>locate duplicates:

<img width="1438" alt="image" src="https://github.com/user-attachments/assets/4854ed78-d966-44c4-b3fc-475d61ab8864">

**Comment by samreid** [comment]
Here is another example:

BuoyancyExploreModel:
```ts
    // Left scale
    this.availableMasses.push( new Scale( this.engine, this.gravityProperty, {
      matrix: Matrix3.translation( -0.65, -Scale.SCALE_BASE_BOUNDS.minY ),
      displayType: DisplayType.NEWTONS,
      tandem: options.tandem.createTandem( 'scale' ),
      canMove: true,
      inputEnabledPropertyOptions: {
        phetioReadOnly: false
      }
    } ) );
```

BuoyancyCompareModel:

```ts
    // Left scale
    this.availableMasses.push( new Scale( this.engine, this.gravityProperty, {
      matrix: Matrix3.translation( -0.70, -Scale.SCALE_BASE_BOUNDS.minY ),
      displayType: DisplayType.NEWTONS,
      tandem: providedOptions.tandem.createTandem( 'scale' ),
      canMove: true,
      inputEnabledPropertyOptions: {
        phetioReadOnly: false
      }
    } ) );
```


BuoyancyLabModel:

```ts
    // Left scale
    this.availableMasses.push( new Scale( this.engine, this.gravityProperty, {
      matrix: Matrix3.translation( -0.65, -Scale.SCALE_BASE_BOUNDS.minY ),
      displayType: DisplayType.NEWTONS,
      tandem: options.tandem.createTandem( 'scale' ),
      canMove: false,
      inputEnabledPropertyOptions: {
        phetioReadOnly: false
      }
    } ) );
```

**Comment by AgustinVallejo** [comment]
Will focus on the larger ones. The Webstorm tool is `Code > Analyze Code > Locate Duplicates`

**Comment by AgustinVallejo** [comment]
Some notes/ideas/questions:
- [x] Duck is modelled closely after an Ellipsoid, so there's significant duplication there, but I'm not sure if it's enough for Duck to extend Ellipsoid... Any thoughts?
- [x] Left a TODO for discussion: Moved displayOptionsPanel to the common class as a field, but it's only used in B and B:B, not D. Is that okay? Is it better to have it be conditionally created otherwise null?
- [x] I want to factor out the rightBarrierViewPointPropertyProperty from the subclasses, but it depends on the rightSideVBox, which is not in the common class (Compare has its own). Doing it later.

**Comment by samreid** [comment]
I reviewed the remaining occurrences detected by WebStorm, and it seems @AgustinVallejo got the most important ones. I opened a side issue for a likely bug in one duplicate. Closing.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.
