### ISSUE TITLE
Eliminate MassShape and its related Property instances

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#292]
Discovered during #123, BuoyancyShapeModel has these attributes:

```ts
public readonly shapeNameProperty: Property<MassShape>;
public readonly shapeProperty: TProperty<Mass>;
private readonly shapeCacheMap = new Map<MassShape, Mass>();
```

This is parallel to the change we made regarding material and MaterialEnum. Since we are preallocating all the Mass instances on this screen, we do not need a separate data structure to manage the `shapeNameProperty`. `MassShape` also adds the translatable name, and we would need another place for that though.

**Comment by AgustinVallejo** [comment]
With @samreid we agreed that this is actually in good shape! Closing
