### ISSUE TITLE
Document how DensityBuoyancyModel.masses differs from availableMasses

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#293]
From #123, please document how DensityBuoyancyModel.masses differs from availableMasses

**Comment by samreid** [comment]
Equivalently, why do we need `availableMasses` at all?

**Comment by AgustinVallejo** [comment]
Will take a quick look

**Comment by samreid** [comment]
@AgustinVallejo and I figured out what is happening here, documented, renamed, opened a side issue. This one can be closed.
