### ISSUE TITLE
Mass.internalVisibleProperty differs from GatedVisibleProperty's defaults

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#294]
From #123:

```ts
    // TODO: We create internalVisibleProprety to pass into GatedVisibleProperty, but it differs from the defaults
    // and naming in GatedVisibleProperty. Can we use the default one in GatedVisibleProperty instead? Or match up with its
    // conventions
    this.internalVisibleProperty = new BooleanProperty( options.visible, {
      phetioDocumentation: 'For internal use only',

      // instrumentation is needed for PhET-iO State only, not customizable.
      tandem: tandem.createTandem( 'internalVisibleProperty' ),
      phetioReadOnly: true
    } );

    this.visibleProperty = new GatedVisibleProperty( this.internalVisibleProperty, tandem );
```

**Comment by samreid** [comment]
I determined that `Mass.internalVisibleProperty` no longer needed to be instrumented. It always takes its value based on the computation of an upstream instrumented variable. This matches the convention we have in other usages of `GatedVisibleProperty` where the passed-in property is not instrumented.

After making this change, I tested it thoroughly in PhET-iO Studio, including clicking "Test" to make sure that the customizations were preserved and that everything worked correctly after pressing "Reset All" in the test scenario. Everything seemed to work fine.

This change also allowed us to remove the `internalVisibleProperty` from the Studio tree, which simplifies and cleans it up quite a bit.

@arouinfar can you please test mass visibility in studio and in the studio tree?

**Comment by arouinfar** [comment]
Thanks @samreid! Getting rid of `internalVisibleProperty` is a nice improvement. I tested on main, setting `selfVisibleProperty` to `false` and confirmed that the customization is stateful. Closing.
