### ISSUE TITLE
Create a directory js/common/model/mass

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#299]
From https://github.com/phetsims/density-buoyancy-common/issues/123, it is recommended to create a subdirectory js/common/model/mass which would include at least the 12 subtypes of Mass.ts:

* Mass
* Cube
* Cuboid
* Ellipsoid
* etc

This will help organize and clean the common model directory

- [ ] likewise, in common/view, create a subdirectory for view files like `ConeView`, 'MeasurableMassView`, etc.

**Comment by samreid** [comment]
Or if many of these shapes are only used in the shapes screen, they could move there.

**Comment by samreid** [comment]
After moving out the "shapes" screen ones, the number of remaining Mass subclasses in common/ is small, so does not warrant another directory.  Closing.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.
