### ISSUE TITLE
Remove PhysicsEngine abstraction

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#302]
Discovered during #123. It is clear that `PhysicsEngine` would be a useful abstraction while exploring different physics engines to choose an appropriate one. However, now that we would like to go to production with p2, the PhysicsEngine abstraction is adding unnecessary complexity and does not help modularize/simplify/document the system. I recommend removing that layer.

**Comment by samreid** [comment]
Removed, closing.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by samreid** [comment]
Fixed, closing.
