### ISSUE TITLE
Uninstrument `materialProperty.customMaterial` when "custom" isn't a valid value

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density-buoyancy-common#308]
For https://github.com/phetsims/buoyancy/issues/51

There are many instances of `materialProperty.customMaterial` for materials where "custom" isn't a valid value. This creates a really awkward experience in Studio. Can we uninstrument `customMaterial` in these instances?

- [x] `fluid.materialProperty.customMaterial` for Buoyancy -- Compare, All of Buoyancy: Basics, All of Density 
- [x]  `shapes.*.materialProperty.customMaterial`
- [x]  `applicationsScreen.model.objects.boat.materialProperty.customMaterial`

Assigning to @AgustinVallejo and @samreid.

**Comment by samreid** [comment]
I'll take a look. Solo assigning for now

**Comment by samreid** [comment]
For the fluids and solids, I added a check if "CUSTOM" was available. If not available, then I passed OPT_OUT to the custom material.  It appears to be fixed in my testing. @arouinfar can you please review and close if all is well?

**Comment by arouinfar** [comment]
Thanks @samreid! Everything looks good for the fluids and solids on main.

While reviewing, I noticed that  `customGravity` has a similar issue, but the problem seems to be with the valid values themselves, so I opened #311.

Nothing else remains for this issue, closing.
