### ISSUE TITLE
Density of the bottle should be read-only

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density-buoyancy-common#309]
For https://github.com/phetsims/buoyancy/issues/51

`bottle.materialProperty.customMaterial.densityProperty` controls the density of the bottle. There is no reason for clients to be able to change this value, so let's make it read-only. 

Over to @AgustinVallejo.

**Comment by samreid** [comment]
Similar to https://github.com/phetsims/density-buoyancy-common/issues/311#issuecomment-2266335601, let's discuss whether some/most/all readonly Properties should be uninstrumented.

**Comment by AgustinVallejo** [comment]
Decision: make it readonly :)

Use overrides to add phetioDocumentation: 'Density of the bottle system.'

**Comment by AgustinVallejo** [comment]
Back to @arouinfar for review.

**Comment by arouinfar** [comment]
Looks good on main, thanks @AgustinVallejo. Closing.
