### ISSUE TITLE
Studio autoselect doesn't function when `inputEnabledProperty` is `false`

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density-buoyancy-common#310]
For https://github.com/phetsims/buoyancy/issues/51

I noticed that some of the scales in Buoyancy are autoselectable in Studio, and some are not. For example, the pool scale is never autoselectable, even when outside of the pointer area of the slider. The difference seems to come down to the state of `inputEnabledPoprety`. 

Setting `inputEnabledProperty: false` to other items, such as a block, has a similar effect. Autoselect stops working once an object is not pickable. This is inconsistent with the behavior in other PhET-iO simulations, such as CCK: DC. 

Steps to reproduce:
1. Open Buoyancy in Studio on main
2. Autoselect a block and set `inputEnabledProperty` to `false`.
3. Autoselect something else in the sim to move the tree focus elsewhere.
4. Attempt to autoselect the block, and nothing happens.

Compare to CCK: DC
1. Open CCK: DC in  Studio on main
5. Drag a battery out of the carousel and opt/alt to autoselect the view element.
6. Set `inputEnabledProperty` to `false`.
7. Autoselect something else in the sim to move the tree focus elsewhere.
8. Use opt/alt or ctrl autoselect modes and select the battery. Note that autoselect is still functional, even though the battery is no longer draggable.

The behavior in the Density/Buoyancy suite is highly undesirable and creates a major inconvenience to Studio users. The problem is limited to density-buoyancy-common sims, so this seems like the appropriate repo.

Assigning to @samreid and @AgustinVallejo to investigate.

**Comment by samreid** [comment]
I believe this is the same as the problem identified in https://github.com/phetsims/density-buoyancy-common/issues/278. Closing that one as duplicate and solo assigning for investigation.

**Comment by samreid** [comment]
I pushed a proposed fix that seems to work well in my testing. It additionally made the immovable scale in density autoselectable (that is controlled by a separate `canMove` flag). @arouinfar can you please review/test? Please close if all is well.

**Comment by arouinfar** [comment]
Thanks @samreid! Autoselect is now working nicely in Studio, closing.
