### ISSUE TITLE
Uninstrument gravityProperty everywhere but in B:Lab

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/density-buoyancy-common#313]
Uninstrument model.gravityProperty, the global gravities are fine :)

Also make double sure to uninstrument the custom child.

Based on https://github.com/phetsims/density-buoyancy-common/issues/311

**Comment by AgustinVallejo** [comment]
@arouinfar Can you double check and close please?

**Comment by arouinfar** [comment]
This is great, thanks @AgustinVallejo! Closing.
