### ISSUE TITLE
`displacedWeightProperty` should have units of N

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density-buoyancy-common#322]
For https://github.com/phetsims/buoyancy/issues/51

On the Lab Screen, there is a Property for the weight of the displaced fluid, `fluidDisplacedAccordionBox.displacedWeightProperty`. The units are null, but should be N. 
![image](https://github.com/user-attachments/assets/af4bef82-72fb-49b5-8ba2-6cc9cbee1986)
 
![image](https://github.com/user-attachments/assets/57468d7a-be50-4a9d-8e44-1b951c6311cd)

**Comment by samreid** [comment]
Good idea, I added the units. It was easy to verify, so I'll close the issue.
