### ISSUE TITLE
Shapes Screen: Use "Controls" suffix instead of "ControlNode"

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density-buoyancy-common#323]
For https://github.com/phetsims/buoyancy/issues/51

The controls related to the objects on the Shapes screen all live in this panel:
![image](https://github.com/user-attachments/assets/7a839732-7c78-40a0-80b9-2201b9c2a9e8)

There are three different sets of controls that make up this panel, all ending with "ControlNode".
![image](https://github.com/user-attachments/assets/3ff834f4-329a-4d63-ac57-b936493b12bf)

The Applications screen originally used a similar naming scheme, but we renamed them using "Controls" as the suffix over in https://github.com/phetsims/buoyancy/issues/180.

For consistency, let's use the "Controls" suffix instead of "ControlNode" on the Shapes Screen. The tandems to rename are:
- [x] `buoyancy.shapesScreen.view.materialControlNode`
- [x] `buoyancy.shapesScreen.view.objectAShapeSizeControlNode` 
- [x]  `buoyancy.shapesScreen.view.objectBShapeSizeControlNodeTandem` (Looks like we all missed the "Tandem" typo in this one!)

**Comment by samreid** [comment]
Thanks for the good recommendation. I addressed it in the commit, can you please verify and close if all is well?

**Comment by arouinfar** [comment]
Thanks @samreid, looks good on main. Closing.
