### ISSUE TITLE
Shapes Screen: Instrument object's volume display

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density-buoyancy-common#324]
For https://github.com/phetsims/buoyancy/issues/51

The volume readouts for each object on the Shapes screen is part of `object*ShapeSizeControlNode`, and will be hidden when `object*ShapeSizeControlNode.visibleProperty: false`. However, volume readout itself doesn't appear to be instrumented.

![image](https://github.com/user-attachments/assets/cfd10f2a-c331-4093-bf86-4e9f2439472c)

These volume readouts should be instrumented and have a `visibleProperty`, much like the bottle's Air Volume readout, see `bottleControls.airVolumeDisplay`.

**Comment by samreid** [comment]
I instrumented both occurrences of the `volumeDisplay` on the shapes screen, @arouinfar can you please verify/test? Please close if all is well.

**Comment by arouinfar** [comment]
Thanks @samreid! Looks good on main, closing.
