### ISSUE TITLE
Can we eliminate availableMasses.remove?

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#331]
Discovered in https://github.com/phetsims/density-buoyancy-common/issues/293, we saw that only one site calls `availableMasses.remove`, it is BuoyancyShapesModel.ts

```ts
        if ( this.availableMasses.includes( oldMass ) ) {
          this.availableMasses.remove( oldMass );
          this.availableMasses.add( newMass );
        }
```

This adds to a lot of complexity at the declaration site for `availableMasses` and a `map` that could be removed.  Should we eliminate `availableMasses.remove`? Other screens get by just changing the visibleProperties.

**Comment by samreid** [comment]
@zepumph thinks this is worth investigation, we can try to convert the `availableMasses.remove` to `internalVisibleProperty.value=false`, then we can remove the `availableMasses.addItemRemoveListener` part. Also add all of the preallocated shapes into the `availableMasses` in `BuoyancyShapeModel`.

**Comment by samreid** [comment]
The proposal worked very well. Over to @zepumph for review, thanks.

**Comment by zepumph** [comment]
Excellent. Just a few small improvements above. Closing.

**Comment by zepumph** [comment]
Actually. I think that all this code could do well to be moved over to the shape model.

**Comment by zepumph** [comment]
Ok. This feels much cleaner. There were a few logic changes, but for the most part things seems tighter. Can you review?

**Comment by samreid** [comment]
This is a much better way, thanks! Closing.
