### ISSUE TITLE
Try to use optionize instead of combineOptions, specially in constructors

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/density-buoyancy-common#333]

**Comment by AgustinVallejo** [comment]
First go at this: Screen Views now look way more cleaner. 

- [x] Adding a reminder to check if some of those options can be made default, because they look really similar.

**Comment by AgustinVallejo** [comment]
This is ready for a dev review :)

**Comment by AgustinVallejo** [comment]
Will factor out ScreenView options and pass to Sam for review

**Comment by samreid** [comment]
Thanks, nice work @AgustinVallejo and I added a few more embellishments. @zepumph want to review or do anything else here?

**Comment by zepumph** [comment]
perfect. Thanks
