### ISSUE TITLE
Modularize and improve documentation of DensityBuoyancyScreenView

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/density-buoyancy-common#334]
Currently there's two TODOs on the top of the file which state

> Elaborate on the main responsibilities of this class
> Currently at 871 lines, this file is more complex. Can it be simplified or modularized?

**Comment by samreid** [comment]
@zepumph volunteered since it partly overlaps with #120

**Comment by zepumph** [comment]
Alright, DBCScreenView has gone from 900 to 475 lines of code. I created MobiusScreenView for THREE.js related common code, and 4 new mesh classes in common/view/mesh/. I didn't take a look at documentation today. @samreid can you please review my changes, take another look through the file, and let me know if you see anything that could use more work or documentation?

**Comment by samreid** [comment]
I reviewed the code and tested at runtime, things are looking great. I added some documentation and TODOs. Back to you @zepumph

**Comment by zepumph** [comment]
TODOs addressed, and a few more improvements. Spot check please?

**Comment by samreid** [comment]
Looks great, thanks! Closing.
