### ISSUE TITLE
Uninstrument `poolScaleHeightControl.numberDisplay`

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density-buoyancy-common#339]
While reviewing #325, I noticed that the pool scale NumberControl has an instrumented NumberDisplay, which seems unnecessary. The height/width controls on the Shapes screen had a similar issue, and we decided to uninstrumented the NumberDisplays over in https://github.com/phetsims/density-buoyancy-common/issues/239.

Let's uninstrument `poolScaleHeightControl.numberDisplay`.

**Comment by samreid** [comment]
I opted out of the PoolScaleHeightControl's numberDisplay tandem, please review.

**Comment by arouinfar** [comment]
Thanks @samreid! Looks good on main, closing.
