### ISSUE TITLE
tapping on a block (without dragging) increases its weight on the scale

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#34]
For #5 and related to https://github.com/phetsims/density-buoyancy-common/issues/22

 ![Kapture 2021-08-10 at 15 47 46](https://user-images.githubusercontent.com/679486/128939431-6ecbf8a5-2b3b-4d16-9df8-4a15858dbf5c.gif)

Just tapping on a block (without dragging) increases its weight on the scale

**Comment by jonathanolson** [comment]
@DianaTavares @kathy-phet thoughts on how problematic this is? I'm not seeing an easy way to handle this, it looks like just the existence of the drag constraint in the physics engine is causing this.

**Comment by DianaTavares** [comment]
On the 08/26 design meeting was decided that this is not a priority to solve.  The strange behaviour stop once the user is not clicking/taping, and we don't see issues during the interviews.  The decision was to close the issue.
