### ISSUE TITLE
Updates to a few Shapes model Properties

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density-buoyancy-common#340]
Discovered while reviewing https://github.com/phetsims/density-buoyancy-common/issues/325

Cones and cylinders have additional Properties to change their size, but the object size should be set through the Height/Width controls instead. Let's make these read-only:
 
- [x] `radiusProperty`
- [x]  `heightProperty` 

The Properties used to set the height/width of the shapes need an appropriate range. Let's use 0-1 to match the range of the sliders.
- [x]  `heightRatioProperty`
- [x] `widthRatioProperty`

**Comment by samreid** [comment]
Fixed in the commits, @arouinfar can you please review? Close if all is well.

**Comment by arouinfar** [comment]
Looks good on main, thanks @samreid! Closing.
