### ISSUE TITLE
Uninstrument `vectorZoomLevelProperty` in Density

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density-buoyancy-common#342]
For https://github.com/phetsims/density/issues/200

There are no vectors in Density,  so the `vectorZoomLevelProperty` is irrelevant. Let's uninstrument it.

**Comment by samreid** [comment]
Fixed, can you please review and close?

**Comment by arouinfar** [comment]
Thanks @samreid! Looks good on main, closing.
