### ISSUE TITLE
Tandem names for Density's Compare blocks should refer to letter, not color

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density-buoyancy-common#343]
For https://github.com/phetsims/density/issues/200

The blocks on Density Compare screen are named by color, e.g. `blueBlock`.
<img width="205" alt="image" src="https://github.com/user-attachments/assets/8093700a-2910-47b3-b0e1-fecce0fd03fe">

This is inconsistent with how we name blocks elsewhere in the suite. Let's rename the blocks so that they are called `blockA`, `blockB`, etc. Note that there isn't a consistent letter-to-color mapping, so take care when renaming things.

**Comment by samreid** [comment]
Fixed in the commits, @arouinfar can you please review the behavior in studio? @zepumph can you please spot check the code? OK to close if both check out.

**Comment by arouinfar** [comment]
Thanks @samreid, this is a nice improvement. Everything looks good on main.
