### ISSUE TITLE
Shapes screen: `volumeProperty` differs from the displaced volume when fully submerged

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density-buoyancy-common#347]
I noticed that the volume displaced by the shape when fully submerged does not match the Volume display (same as `volumeProperty`). The starting volume of the pool is 100 L with the scale submerged.

For some shapes, there's a factor of 2 difference:
<img width="200" alt="image" src="https://github.com/user-attachments/assets/37d20537-62f9-4570-b0b4-5d1f1fae22b4"> <img width="195" alt="image" src="https://github.com/user-attachments/assets/dcaed24c-d890-4847-992e-8c20b518854d">
<img width="200" alt="image" src="https://github.com/user-attachments/assets/f981a6a5-3470-4a4f-87f6-c2073d7a2916"> <img width="195" alt="image" src="https://github.com/user-attachments/assets/bf56822a-9b97-44c1-8f27-ac1d50a85021">

For other shapes, it's a factor of 3 difference:
<img width="200" alt="image" src="https://github.com/user-attachments/assets/aacaaf46-7461-4d8f-95c5-073d8ddb482d">  <img width="198" alt="image" src="https://github.com/user-attachments/assets/f3a17ac3-8444-4370-9d6f-8875b382ebdb">

**Comment by samreid** [comment]
I tried several times to reproduce what is shown in the screenshots above. But my volumes keep matching up:

<img width="776" alt="image" src="https://github.com/user-attachments/assets/ce1f089c-20df-42c5-949b-1727eb930a6a">

Any idea or recommendation how to reveal the inconsistency? Maybe a small but nonzero probability it is related to this newly discovered bug: https://github.com/phetsims/density-buoyancy-common/issues/345 ?

**Comment by arouinfar** [comment]
@samreid after pulling all and refreshing my cache, I'm no longer able to reproduce this bug. My guess is that I somehow caught main at an odd moment. Closing.
