### ISSUE TITLE
QA Credits

### ISSUE THREAD

**Issue by zepumph** [phetsims/density-buoyancy-common#353]
This issue is for all three sims in the suite.

**Comment by zepumph** [comment]
https://github.com/phetsims/density-buoyancy-common/issues/171

**Comment by samreid** [comment]
The QA credits currently reads:

* Logan Bray
* Steele Dalton
* Jaron Droder
* Brooklyn Lash
* Emily Miller
* Matthew Moore
* Ashton Morris
* Liam Mulhall
* Devon Quispe
* Jacob Romero
* Nancy Salpepi
* Katie Woessner

@KatieWoe or @Nancy-Salpepi should anyone else be added?

**Comment by KatieWoe** [comment]
Clifford Hardin should be added.

**Comment by samreid** [comment]
Thanks! I updated the credits. Closing. Anyone feel free to reopen for any reason.

**Comment by zepumph** [comment]
@KatieWoe will these need to be updated during the RC?

**Comment by KatieWoe** [comment]
I doubt it, but if it does I'll let you know
