### ISSUE TITLE
Block A is last in focus order on Shapes screen

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#355]
**Test device**
MacBook Air M1 chip

**Operating System**
14.6.1

**Browser**
Safari 17.6

**Problem description**
For https://github.com/phetsims/qa/issues/1136, Block A is after Reset All in the focus order on the Shapes screen (only).

**Steps to reproduce**
EDIT: 
1. see steps in [comment](https://github.com/phetsims/density-buoyancy-common/issues/355#issuecomment-2305986448) below. 

**Visuals**

https://github.com/user-attachments/assets/ac285748-eef5-4abd-b3b0-b94907809ecf

**Comment by samreid** [comment]
I'll work on this one, thanks!

**Comment by samreid** [comment]
I see it is buggy in your screen capture but cannot reproduce it myself. Does this always happen? Are there more steps to get it into this state?

**Comment by Nancy-Salpepi** [comment]
huh....I see what you are saying. I'm stumped. I will see if I can figure it out!

**Comment by Nancy-Salpepi** [comment]
Now when I go to the Shapes screen and tab through, the slider for the pool scale has focus after the Reset All button.

**Comment by Nancy-Salpepi** [comment]
Here are the steps:
1. Change A to a duck
2. Press Reset All
3. Press 2 Blocks scene
4. Tab through the focus order

**Comment by samreid** [comment]
Thank you! It was easy to reproduce the problem with those steps. @Nancy-Salpepi can you please check if it is fixed on phettest?  @zepumph can you please code review?  Issue can be closed after both @Nancy-Salpepi and @zepumph sign off.

**Comment by Nancy-Salpepi** [comment]
@samreid "B" needs the same fix.

**Comment by samreid** [comment]
Thanks! I was able to reproduce that problem and it seemed to be caused by a missed update when changing between one vs two blocks.  I committed a fix for that part, but am not certain if it is complete. It now seems OK in my testing. Can you please test?

**Comment by Nancy-Salpepi** [comment]
Looks good on main! 
Closing.
