### ISSUE TITLE
Contact Force value may oscillate continuously

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#357]
**Test device**
MacBook Air M1 chip

**Operating System**
14.6.1

**Browser**
Safari 17.6

**Problem description**
For https://github.com/phetsims/qa/issues/1136, on the Applications Screen, when the block is a certain size and material the contact force will oscillate continuously between 2 values. 

**Steps to reproduce**
Here is one example:
1. On the Applications screen check the Force Values and Contact Checkboxes
2. Switch to the Boat Screen
3. Move the brick over so that if won't hang over edge of pool when volume is increased
4. Switch the block's material to Tantalum
5. Increase the volume to 8.0 L --value oscillates 
6. Change the material to Gold
7. Increase the volume to 8.5 -- value oscillates 

**Visuals**

https://github.com/user-attachments/assets/529f21bd-32ee-468c-aaaf-25c15860050a

**Comment by samreid** [comment]
@DianaTavares we have previously discussed this in https://github.com/phetsims/density-buoyancy-common/issues/241. Should anything further be done here? It could be OK to label this issue as wontfix and close it if that matches a prior consensus.

**Comment by DianaTavares** [comment]
Yes, it is ok to label it as wontfix and close the issue!
