### ISSUE TITLE
Shapes can shoot left when weight measurer is moved quickly with a shape on it. Shapes screen

### ISSUE THREAD

**Issue by Matthew-Moore240** [phetsims/density-buoyancy-common#358]
**Test device**
Desktop Win 11

**Operating System**
Windows 11 23H2

**Browser**
129.0.2

**Problem description**
On the Shapes screen, objects can get shot to the left if the object is on the weight measurer and the weight measurer is moved from the bottom to the top quickly. This happens with both the mouse and alt input using the Home and End keys. I believe this also appears to occur with all the shapes except the inverted cone. 

**Steps to reproduce**
1. Pick a shape, make sure it sinks to the bottom
2. Put it on the weight measurer
3. Quickly move the weight measurer to the top either using the mouse or the Home and End keys

**Visuals**
Using the mouse

https://github.com/user-attachments/assets/289f438d-bf96-494a-b521-323716813ee1

Using alt input

https://github.com/user-attachments/assets/c1a66c38-09ad-42c6-bd46-dec2bf55a8f0

https://github.com/phetsims/qa/issues/1136

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Buoyancy‬
URL: https://phet-dev.colorado.edu/html/buoyancy/1.2.0-dev.4/phet/buoyancy_all_phet.html
Version: 1.2.0-dev.4 2024-08-22 14:24:15 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0
Language: en-US
Window: 2048x1019
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0), or similar)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by Nancy-Salpepi** [comment]
Tagging https://github.com/phetsims/qa/issues/1136.

**Comment by samreid** [comment]
In https://github.com/phetsims/buoyancy-basics/issues/14 we introduced an invisible barrier below the scale to prevent objects from getting trapped underneath it. We refined this in https://github.com/phetsims/density-buoyancy-common/issues/214 and https://github.com/phetsims/density-buoyancy-common/issues/194.  We are somewhat hampered by limitations of the p2 physics engine library and how we are using it. @DianaTavares would you like to mark as wontfix as close?

**Comment by DianaTavares** [comment]
Yes, we tried to fix this earlier, and this behavior is the best that we can do, and  I think it is ok! Students can continue using the simulation (before the object get below the scale, and it was not possible to manipulate it). Then closing and mark it as wontfix.
