### ISSUE TITLE
Ellipsoid shape has visual glitch when dropped on the far right weight measurer. Shapes screen.

### ISSUE THREAD

**Issue by Matthew-Moore240** [phetsims/density-buoyancy-common#359]
**Test device**
Desktop Win 11

**Operating System**
Windows 11 23H2

**Browser**
129.0.2

**Problem description**
Ellipsoid glitches out if dropped on the weight measurer. Happens using alt input and the mouse. 

**Steps to reproduce**
1. Make sure the Ellipsoid can sink
2. Drop the Ellipsoid onto the far right weight measurer

**Visuals**

https://github.com/user-attachments/assets/5bbf2f46-95a1-41e2-8f29-e62378435e95

https://github.com/phetsims/qa/issues/1136
<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Buoyancy‬
URL: https://phet-dev.colorado.edu/html/buoyancy/1.2.0-dev.4/phet/buoyancy_all_phet.html
Version: 1.2.0-dev.4 2024-08-22 14:24:15 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0
Language: en-US
Window: 2048x1019
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0), or similar)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by Nancy-Salpepi** [comment]
Tagging https://github.com/phetsims/qa/issues/1136.

**Comment by samreid** [comment]
I believe this is caused by the same problem as in https://github.com/phetsims/density-buoyancy-common/issues/358#issuecomment-2306018679.  In this case, the ellipsoid penetrates through the pool scale, and hits the invisible barrier. @DianaTavares please advise.

**Comment by samreid** [comment]
@DianaTavares and I saw that the ellipsoid has this problem from a very low height, and it is the only shape with this problem. Therefore, it is unlikely to be the same explanation as https://github.com/phetsims/density-buoyancy-common/issues/358#issuecomment-2306018679. I'll take a closer look.

**Comment by samreid** [comment]
@zepumph and I proposed a fix in the commit that works nicely here. @Matthew-Moore240 can you please test on phettest? Please close if it is OK.

**Comment by Matthew-Moore240** [comment]
The fix works great! No issues. Closing.
