### ISSUE TITLE
Usage of this deprecated constant: `SunConstants.VALUE_NUMBERED_PLACEHOLDER`

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#36]
From #5, I observed usage of this deprecated constant: `SunConstants.VALUE_NUMBERED_PLACEHOLDER`.

**Comment by samreid** [comment]
This also relates to the code review item:

> Use named placeholders (e.g. "{{value}} {{units}}") instead of numbered placeholders (e.g. "{0} {1}").

**Comment by jonathanolson** [comment]
Ahh, looks like NumberDisplay now works with the named placeholder by default (handled above).

**Comment by samreid** [comment]
Looks good, thanks!  Closing.
