### ISSUE TITLE
Wooden block stays at bottom of pool after switch from PVC

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#360]
**Test device**
MacBook Air M1 chip

**Operating System**
14.6.1

**Browser**
Safari 17.6

**Problem description**
For https://github.com/phetsims/qa/issues/1136, on the Shapes screen, switching the material from PVC to Wood doesn't cause the block to float again. If I then switch to the Explore screen, that wooden block will now be at the bottom of the pool as well. Pressing Reset All doesn't fix the problem. 

**Steps to reproduce**
1. Go to the Shapes Screen and switch the material to PVC 
2. Switch the material back to Wood
3. Switch to the Explore Screen

**Visuals**

https://github.com/user-attachments/assets/4a9c5260-fda3-445f-a592-3ca06988d979

**Comment by samreid** [comment]
@Nancy-Salpepi great bug, good discovery. I pushed a fix and it seems better in my testing. Can you please confirm on phettest? Please close if ok.

**Comment by Nancy-Salpepi** [comment]
Working great! 
Closing.
