### ISSUE TITLE
Add drag cues to the GrabDragInteraction

### ISSUE THREAD

**Issue by zepumph** [phetsims/density-buoyancy-common#364]
From https://github.com/phetsims/density-buoyancy-common/issues/354#issuecomment-2310551563

@DianaTavares let's discuss the design for this a bit more. I'm not sure if we have defaults here since they normally surround the sim object.

**Comment by DianaTavares** [comment]
Tomorrow after stand-up, I am available!

**Comment by zepumph** [comment]
We want to try to duplicate the WASD + arrow cue from BASE. It seems nice!

![image](https://github.com/user-attachments/assets/b9868d32-927c-4bc3-8d24-f455aaba9f86)

**Comment by zepumph** [comment]
Alright. I believe this is ready for design review.

Let's focus on the look of the cue here, and talk about the hiding logic over in https://github.com/phetsims/density-buoyancy-common/issues/368.

![image](https://github.com/user-attachments/assets/f19bbf77-2258-4340-91f9-4b3949125c49)

**Comment by samreid** [comment]
There appear to be memory leaks in this feature, I proposed a partial remedy in https://github.com/phetsims/density-buoyancy-common/issues/168

**Comment by zepumph** [comment]
In design meeting we love this. No notes. Closing
