### ISSUE TITLE
Sometimes you have to press tab twice to get to the first focus item

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#365]
Discovered during https://github.com/phetsims/density-buoyancy-common/issues/359, sometimes you have to press tab twice before the first item gets focus. I observed this on the shapes screen just now. I thought I saw it earlier for Applications/bottle too, but maybe it was spurious.

**Comment by samreid** [comment]
I also saw this when testing Friction, but it only occurred on the 1st try out of 20. Maybe focus was somewhere unexpected?

**Comment by samreid** [comment]
I cannot get this to happen reliably. @jessegreenberg or @terracoda do you recall seeing anything like this? If not, it is probably safe to close.

**Comment by jessegreenberg** [comment]
I tried to reproduce this in buoyancy but could not. Maybe focus was somewhere in the address bar or one of its buttons? I think it is OK to close but let us know if it continues to behave strangely.
