### ISSUE TITLE
Portion of duck's tale disappears in pool wall

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#366]
**Test device**
iPad 9th generation and MacBook Air

**Operating System**
iPadOS 17.6.1 and MacOS 14.6.1

**Browser**
Safari 

**Problem description**
For https://github.com/phetsims/qa/issues/1136, on the Shapes screen: A wide duck on top of the pool scale will lose a portion of its tail when the scale is lowered into the pool. This doesn't happen with the inverted cone. Instead, when the cone hits the pool's edge, it moves to the left on the scale so that it fits into the pool. 

**Steps to reproduce**
1. On the Lab Screen, select the Duck shape
2. Increase its Height and Width & Depth to max values
3. Raise the pool scale all the way up
4. Place duck on the middle of the scale
5. Slowly lower the scale

**Visuals**

https://github.com/user-attachments/assets/72baca86-3972-4b6c-81a0-fdf0ac823b2a

**Comment by samreid** [comment]
I can try reshaping the duck ellipse, self assigning for investigation.

**Comment by samreid** [comment]
I used ?showDebug to calibrate the duck geometry, this is working much better:

<details>

```diff

Subject: [PATCH] Eliminate top center and bottom center vertex for the ellipsoid, and only teleport away when beneath the scale, see https://github.com/phetsims/density-buoyancy-common/issues/359
---
Index: js/buoyancy/model/shapes/DuckData.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/buoyancy/model/shapes/DuckData.ts b/js/buoyancy/model/shapes/DuckData.ts
--- a/js/buoyancy/model/shapes/DuckData.ts	(revision cac7c01941846b4cadb2b889e132646329499052)
+++ b/js/buoyancy/model/shapes/DuckData.ts	(date 1724711924883)
@@ -71,11 +71,12 @@
   maxValues.subtract( minValues );
   const normalizationFactors = new Vector3( Math.abs( maxValues.x ), Math.abs( maxValues.y ), Math.abs( maxValues.z ) );
 
-  duckGeometry.scale( 1 / normalizationFactors.x, 1 / normalizationFactors.y, 1 / normalizationFactors.z );
+  // Calibrate with p2 geometry using ?showDebug
+  duckGeometry.scale( 1 / normalizationFactors.x * 0.975, 1 / normalizationFactors.y, 1 / normalizationFactors.z );
 }
 
-// translate the 3d shape up
-duckGeometry.translate( 0, 0.08, 0 );
+// Calibrate with p2 geometry using ?showDebug
+duckGeometry.translate( -0.06, 0.08, 0 );
 
 // Parsing the geometry of the 2d duck
 export let flatDuckData = FlatDuckData;
@@ -83,7 +84,7 @@
 const bounds = Shape.polygon( grahamScan ).bounds;
 
 // translate the vertices so that the centroid is at the origin
-flatDuckData = flatDuckData.map( vertex => vertex.subtractXY( bounds.center.x, bounds.center.y - 0.04 ) );
+flatDuckData = flatDuckData.map( vertex => vertex.subtractXY( bounds.center.x, bounds.center.y ) );
 
 // Normalizing the vertices
 flatDuckData = flatDuckData.map( vertex => vertex.componentMultiply( new Vector2( 1 / bounds.width, 1 / bounds.height ) ) );

```

</details>

I do not have an understanding of why it was uncalibrated or why this step is necessary, or why this fixes in the x direction and no fixes are needed in the y direction.  @zepumph can you please help with next steps?

**Comment by zepumph** [comment]
I committed @samreid's patch. Let's keep moving and not worry too much about this kind of manual manipulation.

**Comment by zepumph** [comment]
@Nancy-Salpepi can you please review?

**Comment by Nancy-Salpepi** [comment]
Looks great! Closing.
