### ISSUE TITLE
Are there leaks due to registering observers or listeners? The following guidelines should be followed unless documentation (in-line or in implementation-notes.md) describes why following them is not necessary.

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#37]
From #5, there are many DerivedProperty and `link` calls which are neither disposed, nor commented to describe why disposal is not necessary.

**Comment by jonathanolson** [comment]
Added comments describing why disposal isn't necessary (and one listener disposal for `?showDebug` handling that wasn't proper)

**Comment by samreid** [comment]
Looks good, thanks!  Closing.
