### ISSUE TITLE
Unfeature userControlledProperty

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#370]
For https://github.com/phetsims/qa/issues/1136, the `userControlledProperty` is described as "For Internal Use Only" but is currently featured. 
It makes sense to unfeature this property for all draggable items--blocks, shapes, scales, boat and bottle. 

<img width="972" alt="Screenshot 2024-08-27 at 2 53 33 PM" src="https://github.com/user-attachments/assets/3e2ecf22-c894-4a44-8b93-9a8770c7cbe7">

**Comment by samreid** [comment]
Since this is `phetioState: false` and `phetioReadOnly: true`, can it be uninstrumented?

**Comment by zepumph** [comment]
**History**
* Featured in https://github.com/phetsims/density-buoyancy-common/issues/325
* "Internal Use Only" in https://github.com/phetsims/density-buoyancy-common/issues/232
* Instrumented via dev discretion in https://github.com/phetsims/density-buoyancy-common/commit/4fecbbbe1a84ba9ab8152d4a03bd9ce89d7e789e.

My opinions:
1. Knowing if a block is being used seems like a primary metric/analytic, but perhaps wasn't explicitly asked for by the design.  
1. It would be buggy if state set this to true because state was captured while a user was interacting with a block.


Perhaps best to call upon designers to decide how to proceed.

**Comment by samreid** [comment]
@zepumph and I were wondering if we should leave it featured and change the documentation to: `'Indicates whether the user is currently controlling the Mass'`.  @arouinfar what do you recommend?

**Comment by zepumph** [comment]
From design meeting:
* Add in a guard to set userControlledProperty to false when setting state.
* Update the phetioDoc to: `Indicates whether the user is currently controlling the Object`.

**Comment by samreid** [comment]
Surprisingly, this patch was not enough to fix the behavior in the state wrapper when dragging a downstream block. What other parts may need to be guarded?

<details>

```diff

Subject: [PATCH] Use blended values for gravity and buoyancy force in the force diagram, and increase threshold for showing values, see https://github.com/phetsims/density-buoyancy-common/issues/380
---
Index: js/common/model/Mass.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/model/Mass.ts b/js/common/model/Mass.ts
--- a/js/common/model/Mass.ts	(revision 19bc7ee4eba57150a61f0918e9fa311aa79770e0)
+++ b/js/common/model/Mass.ts	(date 1725149806328)
@@ -226,12 +226,18 @@
     const tandem = options.tandem;
     this.userControlledProperty = new BooleanProperty( false, {
       tandem: tandem.createTandem( 'userControlledProperty' ),
-      phetioDocumentation: 'For internal use only',
+      phetioDocumentation: 'Indicates whether the user is currently controlling the item',
       phetioReadOnly: true,
       phetioState: false,
       phetioFeatured: true
     } );
 
+    // If a user was dragging a Mass at the moment the state is set, it should no longer be user controlled.
+    phet.phetio.phetioEngine.phetioStateEngine.stateSetEmitter.addListener( () => {
+      this.userControlledProperty.reset();
+      this.interruptedEmitter.emit();
+    } );
+
     this.inputEnabledProperty = new BooleanProperty( options.canMove, combineOptions<BooleanPropertyOptions>( {
       tandem: options.canMove ? tandem.createTandem( 'inputEnabledProperty' ) : Tandem.OPT_OUT,
       phetioDocumentation: 'Sets whether the element will have input enabled, and hence be interactive',

**Comment by AgustinVallejo** [comment]
Working on this. @samreid could you specify what is the desired downstream behavior is for this? Also, I pushed the phetioDocumentation part of the patch so we can easily focus on the other feature.

**Comment by AgustinVallejo** [comment]
Back to QA for double checking, this should be good now :)

**Comment by Nancy-Salpepi** [comment]
@AgustinVallejo Can I get some help on what I need to verify with the state wrapper? It isn't clear to me what I should do.

**Comment by samreid** [comment]
Drag a block in the downstream simulation, when the state is automatically set it should release the downstream block and set it back to the upstream position.

**Comment by Nancy-Salpepi** [comment]
>Add in a guard to set userControlledProperty to false when setting state.

The objects all go back to match the upstream position, except for the boat, which continuously sinks if I move it to the bottom of the pool in the downstream sim. I think that will be addressed in https://github.com/phetsims/density-buoyancy-common/issues/384, but would like dev confirmation on that.

>Update the phetioDoc to: Indicates whether the user is currently controlling the Object.

EDIT: This has been updated in sparky (sorry I was looking at the wrong link)

**Comment by samreid** [comment]
Thanks, I added the comment above to #384 and this issue seems good to close. Anyone please reopen for any reason.
