### ISSUE TITLE
Able to grab an object when inputEnabledProperty is false

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#372]
For https://github.com/phetsims/qa/issues/1136 and related to https://github.com/phetsims/density-buoyancy-common/issues/368, when a moveable object's `inputEnabledProperty` is set to false 
-the grab cue is still there when using alt input
-it can still be grabbed but not moved with both mouse and alt input 

Even though it is a slightly different interaction, I looked at MSaB and when the balls are disabled, I can't grab the ball and the grab cue isn't there. Only the solid interactive highlight is present.
 
<img width="1440" alt="Screenshot 2024-08-27 at 4 46 01 PM" src="https://github.com/user-attachments/assets/57c4b1ac-3075-47b9-bf16-78f6391374d1">

<img width="635" alt="Screenshot 2024-08-27 at 5 05 21 PM" src="https://github.com/user-attachments/assets/cd239cfa-5aa8-40cc-aebc-705fe694c5c4">

**Comment by zepumph** [comment]
Working on this now.

**Comment by zepumph** [comment]
Fixed above, can you please confirm? You should still be able to focus it, but you cannot interact with it.

**Comment by Nancy-Salpepi** [comment]
Working great! Closing.
