### ISSUE TITLE
Changing values on scale when

### ISSUE THREAD

**Issue by JaronDroder** [phetsims/density-buoyancy-common#373]
**Test device**
Alien Ware m15 R7

**Operating System**
 
Win 22H2

**Browser**
Chrome 128.0.6613.84

**Problem description**

  For https://github.com/phetsims/qa/issues/1136
I found this on buoyancy basics on the explore screen. I have been able to recreate the bug under oil and seawater, although it is easiest under oil.  When a certain weight is reached on the scale under the liquid, the number indicating newtons can start to switch rapidly between other values after, usually by about a tenth of a newton.  The Bug occurs for a lot of different N values, and depending on the value there are different rates at which the number will switch

**Steps to reproduce**

Go to explore, and select oil or sea water as the liquid for the pool (I found it easiest to do with oil). 
After setting the scale at the bottom, place the block on the scale and raise the density or the volume. Around 350 N is where I found the bug to start, and it was easiest to just turn the density all the way up, although I found multiple weights caused the bug to occur.
 
**Visuals**

![saltwaterbug](https://github.com/user-attachments/assets/86358b74-e7e9-4ec4-aab7-3536301eabfa)
![oilbug](https://github.com/user-attachments/assets/a1e62785-7dde-45e1-b0b4-0e9bfaf2a06e)

**Comment by samreid** [comment]
Prior work in https://github.com/phetsims/buoyancy/issues/64, let's chat at an upcoming standup.

**Comment by zepumph** [comment]
Thanks for reporting. We discussed similar oscillations over in https://github.com/phetsims/density-buoyancy-common/issues/357 and https://github.com/phetsims/density-buoyancy-common/issues/241. We aren't able to handle this entirely because this is just noise in the p2 physics engine. Closing
