### ISSUE TITLE
Possible for ducks to get stuck together

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#377]
**Test device**
iPad 9th generation and MacBook Air

**Operating System**
iPadOS 17.6.1 and macOS14.6.1

**Browser**
Safari 

**Problem description**
For https://github.com/phetsims/qa/issues/1136, on the Shapes Screen it is possible for the 2 ducks to get stuck together. It is also possible to push a duck through the bottom of the pool.

**Steps to reproduce**
1. On the Shapes Screen select the 2 Blocks radiobutton
2. Make both objects ducks
3. Push one duck into the back of the other at a downward angle

**Visuals**

https://github.com/user-attachments/assets/8b861322-91f2-44c8-9d01-8e8433adcd89

<img width="340" alt="Screenshot 2024-08-28 at 3 01 43 PM" src="https://github.com/user-attachments/assets/d96a5e59-332f-4d4e-819f-5b988d2ba5e0">

**Comment by samreid** [comment]
Using the convex hull for the p2 shape fixes this problem:

<details>

```diff

Subject: [PATCH] Adjust font and maxWidth to prevent resizing, see https://github.com/phetsims/density-buoyancy-common/issues/375
---
Index: js/buoyancy/model/shapes/Duck.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/buoyancy/model/shapes/Duck.ts b/js/buoyancy/model/shapes/Duck.ts
--- a/js/buoyancy/model/shapes/Duck.ts	(revision 7946d593dab68270831e960b25e0e372513e90a5)
+++ b/js/buoyancy/model/shapes/Duck.ts	(date 1724966167384)
@@ -18,6 +18,7 @@
 import { MassShape } from '../../../common/model/MassShape.js';
 import { flatDuckData } from './DuckData.js';
 import Ellipsoid, { EllipsoidOptions } from './Ellipsoid.js';
+import ConvexHull2 from '../../../../../dot/js/ConvexHull2.js';
 
 type SelfOptions = EmptySelfOptions;
 export type DuckOptions = SelfOptions & EllipsoidOptions;
@@ -68,7 +69,9 @@
     const vertices = this.getFlatGeometry();
 
     // Scale the vertices to the given width and height
-    return vertices.map( vertex => vertex.componentTimes( new Vector2( width, height ) ) );
+    const vector2s = vertices.map( vertex => vertex.componentTimes( new Vector2( width, height ) ) );
+
+    return ConvexHull2.grahamScan( vector2s, false );
   }
 
   private static getFlatGeometry(): Vector2[] {


```

</details>

It looks like so:

<img width="695" alt="image" src="https://github.com/user-attachments/assets/175222c0-2681-44b3-bbd0-dccbb7012a10">

@AgustinVallejo can you please review/test? Is this OK to commit?

**Comment by AgustinVallejo** [comment]
I think the only tradeoff is that the duck's hitbox is now more strict, so what is shown in the image is no longer possible. IMO it's a reasonable tradeoff for fixing this.

![image](https://github.com/user-attachments/assets/0618d388-68cc-43d0-9969-9740fe31ec28)

Committing and passing back to QA.

**Comment by Nancy-Salpepi** [comment]
I can no longer get the ducks to combine but I still see the second part of the issue. 
I didn't get anything stuck in the bottom of the pool today, but I can get a shape(duck, ellipse) stuck in the wall by the scale--either by colliding one object into the other or by hitting the wall at a certain again with one object.



https://github.com/user-attachments/assets/f49a0319-19ed-4293-80bf-7588deb1c7db

**Comment by AgustinVallejo** [comment]
Pushing another potential fix: Interrupting drag when teleporting shapes back from the shadow realm, and no longer comparing vertical centers of shapes and scale, but rather, horizontal (make sure its to the right, not necessarily above the scale)

Back to QA for testing and hopefully closing

**Comment by Nancy-Salpepi** [comment]
This still looks broken on sparky. I had trouble getting an object stuck in the wall on the scale side, but had no problem pushing it through the left bottom corner of the pool. 

https://github.com/user-attachments/assets/24961319-30fd-4e45-85e8-91c6862206ed

**Comment by AgustinVallejo** [comment]
And do you consider this a regression or has it always been like this? @Nancy-Salpepi

**Comment by Nancy-Salpepi** [comment]
I just tried in the dev version and it occurs there too. I don't usually try and do such odd things....I usually find these issues accidentally.

**Comment by AgustinVallejo** [comment]
This is now addressed in a similar way, back to QA :)

**Comment by Nancy-Salpepi** [comment]
looks much better! Closing!
