### ISSUE TITLE
Add GrabDragInteraction to keyboard help dialog

### ISSUE THREAD

**Issue by zepumph** [phetsims/density-buoyancy-common#379]
Oversight as part of #209. Let's add this now.

**Comment by zepumph** [comment]
`GrabReleaseKeyboardHelpSection`

**Comment by zepumph** [comment]
https://github.com/phetsims/density-buoyancy-common/issues/368

**Comment by zepumph** [comment]
- [x] Let's use "Item" to match the moving section. 
- [x] Make sure to test every screen in every sim.

**Comment by zepumph** [comment]
- [ ] In addition to the above work, I realized that we aren't passing an accessibleName correctly into GrabDragInteraction, and so we likely want to update the `accessibleName` setter of the focusablePath to instead use the GrabDragInteraction options:

Let's do that here in case we need to change "Item" or the mass's accessibleName to make either work better.

https://github.com/phetsims/density-buoyancy-common/blob/032324449214780681fa607fa239f1c9c7768e81/js/common/view/MassView.ts#L97

https://github.com/phetsims/scenery-phet/blob/88f8d7782a4bb249f034773acce4e211592dbf07/js/accessibility/grab-drag/GrabDragInteraction.ts#L84-L89

**Comment by zepumph** [comment]
I don't think my above comment was very clear. We want to remove the accessibleName from the focusablePath, because it is just getting overridden anyways, and we want to only use grab drag options to get the right accessibleName for the mass view.

**Comment by zepumph** [comment]
@DianaTavares could you please take a look at the new keyboard help dialogs, and the accessible names in the a11y view and let us know if there is anything else. The keyboard help can change based on the screen, so let us know if any of them need any tweaking.

![image](https://github.com/user-attachments/assets/287ccfbb-6e9e-4158-966f-8ff3d1bb8dcd)


![image](https://github.com/user-attachments/assets/8ae8b27e-7ed7-4a36-8ee3-2aa419b56f05)

**Comment by DianaTavares** [comment]
The help dialogs in the three sims (Buoyancy, B-B and Density)looks amazing! 

I have to accept that this is the first time that I review the a11y view. I think that Grab Mass is ok!! I like that it differentiates them from the scale, bottle, and boat. 

I observe other stuff that I don't know is important: 

- In density, I observe that when random is selected, appears this button: 

![image](https://github.com/user-attachments/assets/2b2a5010-9a19-4303-a1d5-b8baf9e41220)
It don't have Name in the ... I think the name is PDOM: 
![image](https://github.com/user-attachments/assets/4d5e6132-fa9c-4041-9dff-22a02fa184cb)

No sure how big a name can be, but what about "Random Block Refresh" it is the way it is in PhET-iO. 

-  I understand that this view is for people that hear the interactions with the sim, what happen with the numbers that are not one decimal long? For example this one:

![image](https://github.com/user-attachments/assets/70919dc5-d08e-4e65-a605-008a6936d3ea)
In the view is only 5.9

- In Buoyancy-Compare, the name of this control is "Density Comparison", but it said only density:
![image](https://github.com/user-attachments/assets/87e336af-c611-4842-adb4-e0b6c0a0d406)
![image](https://github.com/user-attachments/assets/0e714bbb-6c7d-492e-8955-29cb9f84070c)

- The reset Boat button is also strange, it doesn't have a name and is on the same line that the Fluid Density:
![image](https://github.com/user-attachments/assets/9a54f608-f9fb-42d1-b617-321541e0ecef)

![image](https://github.com/user-attachments/assets/ff78f11b-9eac-41ed-b72d-b85c858bab7f)


Not sure if all this analysis was needed! Please close if the intention was only reviewed the help dialogs and if I agree to use Mass, and I agree!!

**Comment by AgustinVallejo** [comment]
Addressed all suggestions except this one
> I understand that this view is for people that hear the interactions with the sim, what happen with the numbers that are not one decimal long?

Which I understand is a general a11y situation and not within the scope of the sim.

Back to @DianaTavares to double check, thanks for the insights

**Comment by DianaTavares** [comment]
The sim doesn't want to charge: 
![image](https://github.com/user-attachments/assets/431c48e5-69da-40c3-8f06-f3b5df43df16)
 I will wait till tomorrow.

**Comment by DianaTavares** [comment]
This still like that, bur I guess is not a big issue.
> In Buoyancy-Compare, the name of this control is "Density Comparison", but it said only density:
image
image

The rest is perfect! I am ready to close, but I see that @zepumph has a comment with a checkbox that is not checked, then not sure if still work to do.

**Comment by DianaTavares** [comment]
Fixed!
