### ISSUE TITLE
Studio freezes when setting customMaterial.densityProperty

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#381]
**Test device**
Dell

**Operating System**
Win10

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1136 and possibly related to https://github.com/phetsims/density-buoyancy-common/issues/378, in Buoyancy and Density on the Explore Screen:
 If I try and set the customMaterial.densityProperty for a block when 'Custom' isn't selected in the combo box, studio freezes. Nothing shows up in the console. It isn't possible to reload Studio. You need to open in again in another tab. 

**Steps to reproduce**
1. In Studio, open the Explore Screen
2. Go to `buoyancy.exploreScreen.model.blocks.blockA.materialProperty.customMaterial.densityProperty` and change the density to 500. Set Value. --studio freezes

**Visuals**

https://github.com/user-attachments/assets/411f2261-6e06-4ff3-907f-1fee0bc09e49

**Comment by samreid** [comment]
This patch shows the infinite loop that gets triggered:

<details>

```diff

Subject: [PATCH] Use blended values for gravity and buoyancy force in the force diagram, and increase threshold for showing values, see https://github.com/phetsims/density-buoyancy-common/issues/380
---
Index: js/common/view/MaterialMassVolumeControlNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/MaterialMassVolumeControlNode.ts b/js/common/view/MaterialMassVolumeControlNode.ts
--- a/js/common/view/MaterialMassVolumeControlNode.ts	(revision 979e09c6cd87c4cd74bb5c9b7093d3a89935c964)
+++ b/js/common/view/MaterialMassVolumeControlNode.ts	(date 1725374191162)
@@ -255,7 +255,9 @@
           adjustedMass = max;
         }
 
-        numberControlMassProperty.value = Utils.clamp( adjustedMass, min, max );
+        const newValue = Utils.clamp( adjustedMass, min, max );
+        console.log( 'numberControlMassProperty.value', newValue );
+        numberControlMassProperty.value = newValue;
 
         modelMassChanging = false;
       }

**Comment by samreid** [comment]
@zepumph recommends to add logging in MaterialProperty to see what is causing the loop. Check on the guards, and also on these ones:

```
    // We need to use "locks" since our behavior is different based on whether the model or user is changing the value
    let modelMassChanging = false;
    let userMassChanging = false;
    let modelVolumeChanging = false;
    let userVolumeChanging = false;
```

**Comment by samreid** [comment]
@zepumph and @AgustinVallejo and I discussed it today and agreed the solution is to make `customMaterial.densityProperty` phetioReadOnly: true in cases where it is controlled by the mass and volume. I did that in the commit.

I checked buoyancy, and need to do buoyancy basics and density next.

**Comment by samreid** [comment]
I completed the rest. I noted that in Density: compare in "same density" the densities are set as read only but it would actually be OK to make them writable. They are using this code: https://github.com/phetsims/density-buoyancy-common/blob/8ab5a708d599aa71c8716f49ac1cc5f9e0449586/js/common/model/CompareBlockSetModel.ts#L83-L100 which says we decided in https://github.com/phetsims/density-buoyancy-common/issues/270#issuecomment-2243371397 to make them all readOnly: false (even the same density ones). That's OK with me but I'll check with @zepumph. What do you recommend?

**Comment by zepumph** [comment]
Discussed with SR and we are ready to close.
