### ISSUE TITLE
Block Volume doesn't reset after pressing boatResetButton

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#383]
**Test device**
iPad 9th generation

**Operating System**
iPadOS 17.6.1

**Browser**
Safari 

**Problem description**
For https://github.com/phetsims/qa/issues/1136, on the Applications Screen in the Boat scene, pressing the boatResetButton only resets the boat volume back to the default. Through Slack, @samreid said that it should reset the block volume as well. 
I'm also wondering what should happen with the block's material on this reset?

**Steps to reproduce**
1. On the Applications Screen go to the Boat scene
2. Change the volume for both the boat and the block
3. Press the boatResetButton

**Visuals**

https://github.com/user-attachments/assets/a2dcce61-41a6-45b0-a8c0-af1ebd3ec540

**Comment by samreid** [comment]
I recommended @Nancy-Salpepi open this issue, but in discussion with @zepumph and @AgustinVallejo we aren't actually sure. @DianaTavares what do you recommend?

**Comment by DianaTavares** [comment]
The mini-reset button was created to just "un-sink" the boat. Clicking it should just put the block out of the boat (the position close to the scale is perfect!) and put the boat again floating in the pool. It wouldn't modify any other values of the block and boat, It should maintain volume and mass for boat and block.

Then, in the video that Nancy is showing, when the button is clicked, the block is correct! But the boat needs to maintain the 30L

**Comment by samreid** [comment]
Fixed in the commit. I also centered the x-position of the boat so that at full volume it doesn't collide with the left wall on reset.  @Nancy-Salpepi and @DianaTavares can you please test on https://sparky.colorado.edu/continuous-testing/buoyancy/buoyancy_en.html?brand=phet&ea&debugger while bayes is offline?

**Comment by samreid** [comment]
Fixed in the commit. I also centered the x-position of the boat so that at full volume it doesn't collide with the left wall on reset.  Will need testing when bayes is back online.

**Comment by Nancy-Salpepi** [comment]
I tested on sparky and the volumes no longer reset, but the boat automatically sinks on reset.

**Comment by DianaTavares** [comment]
Yes, the boat is sinking. Looks like the button is not getting out the fluid of the boat, and for that reason, it sinks again. 

Also, the button is restating the fluid density of the pool. If I move it to another density, when I press the button, it comeback to water. The idea behind that button is that students try configurations, and when they don't get it and sink the boat, all values are the same (just the boat go back to float and the block out of the boat to not sink it again). Then students can modify the variables that they think will result in a successful experiment.

**Comment by samreid** [comment]
Thanks @Nancy-Salpepi and @DianaTavares for describing the problems. I tried to correct them in the commits. Can you please re-test? Please close if it seems OK.

**Comment by Nancy-Salpepi** [comment]
@samreid the boat no longer sinks, but the fluid material still resets to water on sparky.

**Comment by samreid** [comment]
@zepumph can you comment whether sparky maybe didn't pull https://github.com/phetsims/density-buoyancy-common/commit/4551cd781605148db7741087a98b25b2e6a766c8 yet?

**Comment by Nancy-Salpepi** [comment]
This looks good this morning on Sparky. Closing.
