### ISSUE TITLE
Boat position can be incorrect when setting state

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#384]
**Test device**
iPad 9th generation

**Operating System**
iPadOS 17.6.1

**Browser**
Safari 

**Problem description**
For https://github.com/phetsims/qa/issues/1136, this is pretty random but if I sink the boat in the downstream sim only, pressing Set State Now will not return the boat to the floating position. 

**Steps to reproduce**
1. In the State Wrapper, go to the Applications screen of the Buoyancy sim and switch to the Boat scene
2. Set State rate=0
3. In the downstream sim, drag the boat to the bottom of the pool
4. Press Set State Now

**Visuals**

https://github.com/user-attachments/assets/3acf7a28-98b3-4577-b739-d6b83c11a627

**Comment by samreid** [comment]
Note in #370 @Nancy-Salpepi said: [when setting state where the downstream boat is sunk]:

> The objects all go back to match the upstream position, except for the boat, which continuously sinks if I move it to the bottom of the pool in the downstream sim. I think that will be addressed in https://github.com/phetsims/density-buoyancy-common/issues/384, but would like dev confirmation on that.

So let's make sure to check that as part of this issue.

**Comment by AgustinVallejo** [comment]
Fixed in the above commit, back to QA, thanks!

**Comment by Nancy-Salpepi** [comment]
This original comment as well as https://github.com/phetsims/density-buoyancy-common/issues/384#issuecomment-2331828041 are fixed on sparky! Closing.
