### ISSUE TITLE
List order is incorrect when migrating 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#385]
**Test device**
MacBook Air M1 chip

**Operating System**
14.6.1

**Browser**
Safari 17.6

**Problem description**
For https://github.com/phetsims/qa/issues/1136, when migrating from Density 1.1 to 1.2, if I change the order of the materials, that order isn't accurately reflected in 1.2. It says in the console that PVC will be added to the end of the list but it will be the first item. The item that I moved to the first spot (index=0) will be the last item in the list. 

**Steps to reproduce**
1. Go to `density.introScreen.view.blockAControlPanel.comboBox.listBox.aluminumItem` and change the index to 0. 
2. Press Migrate Now
3. Open the combo box in version 1.2

**Visuals**
<img width="505" alt="Screenshot 2024-09-03 at 2 31 06 PM" src="https://github.com/user-attachments/assets/731f51b6-910d-4a85-a9d4-8cf77e60284f">
VERSION 1.1:
<img width="196" alt="Screenshot 2024-09-03 at 2 59 55 PM" src="https://github.com/user-attachments/assets/0cb422a8-76f4-40ce-a25d-72aa5de34f89">

VERSION 1.2:
<img width="276" alt="Screenshot 2024-09-03 at 3 00 21 PM" src="https://github.com/user-attachments/assets/67a21534-576a-40f4-8fd5-0b76f7b84085">

**Comment by samreid** [comment]
I'm seeing PVC appear at the top as well. I don't know where in the code @zepumph and I thought would cause PVC to appear at the end. I'm wondering if we should add a migration process to move it to the end, or maybe even put `density.introScreen.view.blockAPanel.comboBox.listBox.pvcItem.visibleProperty` to be false? for panel A and B.

@zepumph can you please advise?

**Comment by Nancy-Salpepi** [comment]
I also wanted to point out that not only is PVC at the top, but aluminum is at the bottom of the list even though I moved it to the '0" position.

**Comment by zepumph** [comment]
We thought a processor like this could work, but got stuck because other processors and the report analyzer assume that all state entries are in the API, and pvc is not. We could likely add to the API, but decided to give up and just commit updates to the client message.


```

    new ( class hi extends MigrationProcessor {
      public constructor() {super();}

      protected processProtected( x, state ): void {
        state[ 'density.introScreen.view.blockBPanel.comboBox.listBox.pvcItem' ] = {
          index: 6
        };
      }
    } )()
```

`PVC was added as a new material to the Intro Screen. During migration, list box order will not be preserved. Please double check this.`

@Nancy-Salpepi FYI. Closing as a wont fix.
