### ISSUE TITLE
Mass Control Visibility does not migrate

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density-buoyancy-common#386]
**Device**
Samsung
**OS**
Win 11
**Browser**
Firefox
**Problem Description**
For https://github.com/phetsims/qa/issues/1136
If you have `density.compareScreen.view.massNumberControl.visibleProperty` set to false in Density 1.1, then the control panel will be visible when that file is migrated to 1.2. I haven't yet found other elements that do this, but I'll keep an eye out.
**Visuals**
![massgone](https://github.com/user-attachments/assets/87831c94-ff88-4197-b87a-03b619befbea)
![masshere](https://github.com/user-attachments/assets/8bd5284d-c3d5-45aa-b2eb-5df099d6f565)

**Comment by KatieWoe** [comment]
`density.mysteryScreen.model.blockSets.set1.block1E.visibleProperty` and `density.mysteryScreen.model.scale.visibleProperty` don't migrate either.

**Comment by samreid** [comment]
In 1.1, we have:

density.compareScreen.view.massNumberControl
density.compareScreen.view.volumeNumberControl
density.compareScreen.view.densityNumberControl

which are all independent and have independent visibility controls.

However, in 1.2, we have a new container:
density.compareScreen.view.blocksValuePanel

which contains all of the massNumberControl, volumeControl and densityNumberControl.

We could add a rule like "if the user hid all 3 of them in 1.1, then hide blocksValuePanel in 1.2", but what would we want to do if the user only hid 1 or 2 of them?

Let's keep this issue about blocksValuePanel, and move the other problems elsewhere.  @zepumph can you please advise?

**Comment by zepumph** [comment]
@samreid and I got this all cleaned up.

Doc in https://github.com/phetsims/phet-io-sim-specific/blob/0742f76f8ae0fd1fcb169607bbb7be545b88b324/repos/density/js/density-migration-processors.ts#L327-L329:

Basically hiding any in the upstream will hide all in the downstream. @KatieWoe will you please review?

**Comment by KatieWoe** [comment]
Things look better to me on main
