### ISSUE TITLE
Studio handles select an element of blocks oddly

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density-buoyancy-common#387]
**Device**
Samsung
**OS**
Win 11
**Browser**
Firefox
**Problem Description**
For https://github.com/phetsims/qa/issues/1136. Seen in Density. When using the "select an element" commands on blocks in studio you do not seem to get the elements you should. If you use alt on a block, it should take you the view element, but it takes you to the model element. Ctrl should take you to the model element, but takes you to the string element instead.

**Comment by samreid** [comment]
It seems this is a consequence of the fact that the mass views are not instrumented. So when discovering with "view" mode, it finds the mass model, and when finding a linked element, it finds the string label. We do not have any plan to instrument the mass views, and I am unaware of a way around this. @zepumph does this sound correct to you? Want to do anything or close?

UPDATE: We could document the abnormality in examples.md, if that would help.

**Comment by zepumph** [comment]
Yeah, I have kinda noticed that was weird for a while. How about this? Now it will always be the mass, never the nameProperty.

**Comment by KatieWoe** [comment]
This looks much better to me on main.
