### ISSUE TITLE
mass visible properties don't migrate

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#388]
From https://github.com/phetsims/density-buoyancy-common/issues/386

`density.mysteryScreen.model.blockSets.set1.block1E.visibleProperty` and `density.mysteryScreen.model.scale.visibleProperty don't migrate either`

**Comment by samreid** [comment]
Fixed, @KatieWoe can you please test? Close if all is well.

**Comment by KatieWoe** [comment]
The scale migrates, but hiding the blocks does not.

**Comment by samreid** [comment]
Thanks, we discovered that some blocks were migrated (around 2/3) but around 1/3 were inadvertently missing. I added the missing ones in the commit. Can you please re-test?

**Comment by KatieWoe** [comment]
Everything looks good to me on main.
