### ISSUE TITLE
Top block obstructed for stringTest=long

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#39]
From #5, the top block is obstructed when ?stringTest=long:

![image](https://user-images.githubusercontent.com/679486/128961127-72c889db-5eb4-4425-a840-dfeb8efb79b4.png)

**Comment by jonathanolson** [comment]
@DianaTavares should I shorten the maxWidths here so that it won't overlap?

**Comment by DianaTavares** [comment]
Yes, @jonathanolson. I think that is the best solution for it.

**Comment by jonathanolson** [comment]
Should be fixed above, @DianaTavares can you verify?

**Comment by DianaTavares** [comment]
working!!
