### ISSUE TITLE
Webgl failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density-buoyancy-common#396]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/1141
When in another tab, webgl failed and the graphics of the sim disappeared.

**Visuals**
![lostwebgl](https://github.com/user-attachments/assets/4f8330e3-7bc2-4a29-83ee-00e78b42c26b)
![whathappened](https://github.com/user-attachments/assets/9556d35c-89f1-4de4-8b72-0bee53fe0bae)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Buoyancy‬
URL: https://phet-dev.colorado.edu/html/buoyancy/1.2.0-rc.1/phet/buoyancy_all_phet.html
Version: 1.2.0-rc.1 2024-09-10 21:26:52 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Language: en-US
Window: 1536x695
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
I've only seen this once so far, and haven't yet been able to reproduce it. If I see it again or find a way to reliably reproduce it I'll update this issue.

**Comment by KatieWoe** [comment]
I had this happen again. I switched to a tab with youtube so I could pause my background music. That tab appeared black momentarily, before coming back, and when I returned to the sim this error was there.
![image](https://github.com/user-attachments/assets/bd223d3a-9389-4757-981e-a6642ccdb11e)

**Comment by samreid** [comment]
In the scenery webgl development, we investigated context loss recovery, and decided that it would not be in scope for development. Instead we implemented the context loss dialog which is shown above. https://github.com/phetsims/molecule-shapes/issues/100

Therefore, this is the expected behavior, closing. @zepumph and I agreed to close as wontfix
