### ISSUE TITLE
Second block shows grab help text when it shouldn't [Buoyancy Basics]

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#397]
**Test device**
MacBook Air M1 chip

**Operating System**
14.6.1

**Browser**
Safari 17.6

**Problem description**
For https://github.com/phetsims/qa/issues/1141 on the Explore Screen of the Buoyancy Basics sim, after moving one block with keyboard navigation, the second block will still show the grab help text. This is different behavior than indicated in https://github.com/phetsims/density-buoyancy-common/issues/368#issuecomment-2321936942.
The Compare Screen doesn't show this issue, nor do I see a problem in Buoyancy and Density.

**Steps to reproduce**
1. In the Buoyancy Basics sim, go to the Explore Screen and select the 2 Blocks scene
2. Tab to, grab and move Block A 
3. Tab to block B

**Visuals**
<img width="1351" alt="Screenshot 2024-09-12 at 8 49 34 AM" src="https://github.com/user-attachments/assets/7b0b5a51-2842-4098-94dd-d31919d3914c">

**Comment by zepumph** [comment]
My best guess is we just missed one spot where we provide masses a  shared cue model.

**Comment by Nancy-Salpepi** [comment]
Fixed in rc.2. Closing.
