### ISSUE TITLE
Block position is frozen if reset while hold block

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density-buoyancy-common#399]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/1141
If you reset the sim while holding a block, the block is stuck in that position. You can grab it again and move it, but dropping it puts it back in the bugged position. This bug only seems to resolve by refreshing the page.
**Steps to reproduce**
1. Use keyboard nav to grab a block and hold it above the pool
2. Use alt+r to reset the sim

**Visuals**
![possesedblock](https://github.com/user-attachments/assets/91f1e229-6e84-4d5f-863d-bd3750a2497a)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Buoyancy‬
URL: https://phet-dev.colorado.edu/html/buoyancy/1.2.0-rc.1/phet/buoyancy_all_phet.html
Version: 1.2.0-rc.1 2024-09-10 21:26:52 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Language: en-US
Window: 1536x695
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
If this is done on a block that isn't visible upon reset all, such as the Same Volume set, it seems to make it so that a number of things can't be visibly focused on with keyboard nav anymore.

**Comment by Nancy-Salpepi** [comment]
After Reset All, if you try to select "same volume" or a different shape on the shapes screen with the mouse this console error repeatedly pops up:
<img width="364" alt="Screenshot 2024-09-12 at 5 07 53 PM" src="https://github.com/user-attachments/assets/feed401d-8c9e-457e-8b65-4292ab0381e4">

**Comment by zepumph** [comment]
Aha! You found it! Nice job. Tracking over in https://github.com/phetsims/density-buoyancy-common/issues/390.

**Comment by KatieWoe** [comment]
Also happens with the scale.

**Comment by zepumph** [comment]
The fix above should solve everything @KatieWoe reported. Can you please review main and let me know if you run into any trouble.

@Nancy-Salpepi let's pick yours up in https://github.com/phetsims/density-buoyancy-common/issues/390#issuecomment-2347299280.

**Comment by zepumph** [comment]
Actually, we think it is best to have this just verified in rc.2. Unassigning.

**Comment by Nancy-Salpepi** [comment]
For https://github.com/phetsims/qa/issues/1149
This https://github.com/phetsims/density-buoyancy-common/issues/399#issuecomment-2347233560 is still broken in rc.2.

Example Steps:
1. Go to the Shapes screen and select the Ellipsoid shape
2. Tab to the Ellipsoid, grab it and hold it above the pool 
3. Press `Option` + `R`
4. Continually press tab to try and get to all the items in the focus order -- many comboboxes, checkboxes, etc will not have focus. 

https://github.com/user-attachments/assets/71b17798-b393-4e76-bf27-fd22f5d88d01

**Comment by KatieWoe** [comment]
This looks solved to me!
