### ISSUE TITLE
Make sure the string keys are all perfect, because they are difficult to change after 1.0.0 is published. Guidelines for string keys are:

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#40]
From the #5, I saw string keys like so:

```json
  "material.wood": {
    "value": "Wood"
  },
  "shape.block": {
    "value": "Block"
  },
```

I see how it is structured using the dot notation and maybe that is a good fit for this sim.  However, since it is difficult to change string keys after publication, let's make sure it's exactly what is desired.  The code review checklist calls for string keys like so:

> (1) Strings keys should generally match their values. E.g.:

```js
"helloWorld": {
  value: "Hello World!"
},
"quadraticTerms": {
  value: "Quadratic Terms"
}
```

I recall we also have been working on nesting structure in string files, like:
```json
  "material": {
    "wood": {
      "value": "Wood"
    }
  },
```

But I don't know if that is ready for production in non-ally code.  

@jonathanolson how should we proceed?

**Comment by jonathanolson** [comment]
> I recall we also have been working on nesting structure in string files, like:

I had it nested, but had to revert in https://github.com/phetsims/density-buoyancy-common/commit/f38c00eee6c2502b0f533e9311082d508f021579#diff-91764b689d6a982eb69fdb9a705b86ab0a0ed1593706a3fd43da3923ed009175 (due to the linked issues, it wasn't supported).

The grouping here feels natural to me, thoughts on whether it should be changed?

**Comment by samreid** [comment]
It seems reasonable to me, but I don't know all the reasons for the code review document.  Perhaps we should get a second opinion and/or revise the code review checklist.  I'll reach out on slack.

**Comment by samreid** [comment]
@zepumph said:

> I think that dots in the name are totally fine, but at some point will likely become a rich data structure, like a11y strings are at this time.

I replied:

> When we get the rich data structure upgrade, will it cause a complication for the string dot concatenation? Or will it be like _.hasIn where it supports both?

@zepumph said:

> the current string "plugin" already supports both.

**Comment by samreid** [comment]
I updated the CRC accordingly, @jonathanolson can you please review?

**Comment by jonathanolson** [comment]
Looks great to me, thanks!
