### ISSUE TITLE
Changes to custom.densityProperty in examples.md

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#400]
For https://github.com/phetsims/qa/issues/1141, the following PhET-iO IDs were made readOnly=true in work done [here.](https://github.com/phetsims/density-buoyancy-common/issues/381).

The examples.md doesn't reflect these changes and I'm not sure that @arouinfar was aware that these properties were changed. 

**Density:** 

`density.introScreen.model.blocks.blockA.materialProperty.customMaterial.densityProperty`
`density.introScreen.model.blocks.blockB.materialProperty.customMaterial.densityProperty`

**Buoyancy:**

`buoyancy.exploreScreen.model.blocks.blockA.materialProperty.customMaterial.densityProperty`
`buoyancy.exploreScreen.model.blocks.blockB.materialProperty.customMaterial.densityProperty`
`buoyancy.labScreen.model.block.materialProperty.customMaterial.densityProperty`
`buoyancy.applicationsScreen.model.objects.block.materialProperty.customMaterial.densityProperty`

**Comment by arouinfar** [comment]
Thanks @Nancy-Salpepi. This will be a fairly major rewrite, as `customMaterial.densityProperty` is hardly ever editable. I'll wait until after the RC testing is complete to address this issue, in case other issues arise.

**Comment by arouinfar** [comment]
QA for rc.1 is now complete, so I'll start working on these changes.

**Comment by arouinfar** [comment]
Changes made in the above commits and ready for cherry-picking. Over to @samreid  and @zepumph.

**Comment by zepumph** [comment]
Cherry picking now.

**Comment by zepumph** [comment]
Cherry picks complete. Ready for confirmation in QA RC.2

**Comment by KatieWoe** [comment]
This looks fixed
