### ISSUE TITLE
mass value for custom block doesn't migrate

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#401]
**Test device**
MacBook Air M1 chip

**Operating System**
14.6.1

**Browser**
Safari 17.6

**Problem description**
For https://github.com/phetsims/qa/issues/1141, when migrating from Density 1.1 to 1.2, the mass value doesn't migrate for the Custom material. The mass value migrates for other materials (wood, styrofoam). I don't see this issue with the volume. 

**Steps to reproduce**
1. In 1.1 change the material for Block A to Custom
2. Move the mass slider (min or max is easiest to see)
3. Press Migrate Now

**Visuals**
Version 1.1:
<img width="822" alt="Screenshot 2024-09-13 at 1 58 15 PM" src="https://github.com/user-attachments/assets/7d8a78df-eda3-4ee9-9f8b-2dc688c8d12d">

Version 1.2:
<img width="822" alt="Screenshot 2024-09-13 at 1 58 38 PM" src="https://github.com/user-attachments/assets/475df2f9-8f53-460a-830c-59c0ea50e167">

**Comment by Nancy-Salpepi** [comment]
I also see this on the Compare Screen with all the radio buttons. 

For example in 1.1 with Same Volume selected, if I change the volume to min value, the masses will be incorrect in version 1.2.
<img width="374" alt="Screenshot 2024-09-13 at 2 14 05 PM" src="https://github.com/user-attachments/assets/f56b3220-ea5d-4411-8018-711a8fadbe44"><img width="352" alt="Screenshot 2024-09-13 at 2 14 22 PM" src="https://github.com/user-attachments/assets/7ad30707-de04-4ee7-995f-cbf637fce5c8">

**Comment by samreid** [comment]
The 1.1 block a mass property is not stateful, and not being calculated in the downstream simulation. Let's check in with @zepumph

**Comment by zepumph** [comment]
I need to manually cherry pick this. Working on it now.

**Comment by zepumph** [comment]
Done. Here were the steps:

```

  ////////////////////////////////////////////////////////
  // https://github.com/phetsims/density-buoyancy-common/issues/404
  // await cherryPickSHA( 'phet-io-sim-specific', '5c20b634f709527ea5836c00735bdfe8fe8b90f4' );
  // Didn't work, manual cherry picks needed
  // git checkout phet-io-sim-specific@49eb85d1965837d604eac643e56fea6370dd07ec
  // git cherry-pick 5c20b634f709527ea5836c00735bdfe8fe8b90f4
  // manually fix -> 6d28aa30163993447d61e3508b16cf5e80bbcedd
  // const patchName = getPatchName( 'phet-io-sim-specific', '5c20b634f709527ea5836c00735bdfe8fe8b90f4' );
  // m.addPatchSHA( patchName, '6d28aa30163993447d61e3508b16cf5e80bbcedd' )
  // m.applyPatches();
  // m.updateDependencies();
```

**Comment by zepumph** [comment]
Ok. Ready for QA to confirm.

**Comment by KatieWoe** [comment]
This looks ok to me

**Comment by zepumph** [comment]
CT is breaking because of an incomplete deletion. Commit coming soon.

**Comment by zepumph** [comment]
Cherry picked
