### ISSUE TITLE
Scale reading can fluctuate for almost a minute

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density-buoyancy-common#402]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/1141
If a very heavy block is dropped on a scale for the first time the reading can fluctuate for a very long time. I've seen it go on for 45 seconds. Once it finally does stop it doesn't seem to do it again.
**Steps to reproduce**
1. Go to the Explore Screen in Buoyancy: Basics
2. Max out volume and density
3. Drop the block onto the scale on land

**Visuals**
![settledown](https://github.com/user-attachments/assets/36ef27aa-fa68-43ea-bc2e-748843a3414c)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Buoyancy: Basics‬
URL: https://phet-dev.colorado.edu/html/buoyancy-basics/1.2.0-rc.1/phet/buoyancy-basics_all_phet.html
Version: 1.2.0-rc.1 2024-09-10 21:36:52 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Language: en-US
Window: 1536x695
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by zepumph** [comment]
I believe this is another example of an intricacy of the model that we aren't planning to solve. @DianaTavares can you please weigh in (no pun intended)

**Comment by DianaTavares** [comment]
Yes, this is an issue that we are going to fix, all the issues related to vectors and weighs that fluctuate. We did the best that we cant to fix that.
