### ISSUE TITLE
Console errors when dragging Custom block to bottom with alt input

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#403]
**Test device**
MacBook Air M1 chip

**Operating System**
14.6.1

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1141, in Buoyancy Basics on the Explore Screen, dragging a block at min density and min volume to the bottom of the pool causes an error which makes the block temporarily unmovable with alt input. Tabbing away and then back again fixes the problem. 

**Steps to reproduce**
1. In Basics on the Explore Screen, Select "Custom"
2. Move the Density and Volume sliders to minimum values
3. Tab to and grab the block
4. Drag the block to the bottom of the pool
5. Once the block pops back up, try to move it with alt input

**Visuals**

https://github.com/user-attachments/assets/1ab32451-fa99-4b2b-9c9b-ba8742404827

<img width="352" alt="Screenshot 2024-09-14 at 4 24 14 PM" src="https://github.com/user-attachments/assets/1213502e-0c68-457b-8002-9462e157d9a6">

**Comment by Nancy-Salpepi** [comment]
When the block is at the minimum density but not at minimum volume (ex. 3.5 or 4.5), the block will continuously sputter when dragged to the bottom of the pool with alt input.


https://github.com/user-attachments/assets/edfe88bf-2bcb-4b4f-88c9-eb4750b66ae5

**Comment by Nancy-Salpepi** [comment]
Also, when using the pointer, I can drag the block through the scale when it has the minimum density and volume values.

https://github.com/user-attachments/assets/80f1a74c-fb88-4486-83de-24feaa1212cb

**Comment by Nancy-Salpepi** [comment]
Following the steps in https://github.com/phetsims/density-buoyancy-common/issues/403#issue-2526601994 in Studio shows this:
<img width="1222" alt="Screenshot 2024-09-19 at 9 00 30 AM" src="https://github.com/user-attachments/assets/f4115134-d4cb-451e-b6f3-710e3b6e652e">

**Comment by zepumph** [comment]
Maybe related to other work we were doing with the pivot/constraint logic in https://github.com/phetsims/density-buoyancy-common/issues/367, but I thought we reverted that.

**Comment by samreid** [comment]
This problem is easy to reproduce. Dragging the low density, small block to the bottom of the pool triggers this code which was added in https://github.com/phetsims/density-buoyancy-common/issues/377

```js
      // If the mass is under the pool (likely because user forced it there), interrupt dragging and move it back up.
      if ( !( mass instanceof Scale ) && mass.matrix.m12() < this.poolBounds.minY ) {
        mass.teleportUp();
      }
```

which interrupts the dragging and removes the pointer constraint. So we have options like:

1. Prevent teleportation in cases like this
2. Prevent teleportation from interrupting input at all
3. Make sure teleportation fully interrupts input so that the next drag would be clean and start over with a new pointer constraint.
4. Prevent keyboard drag from trying to push the block too far into the ground

**Comment by samreid** [comment]
This is incredibly buggy, but only for a very low density, low volume block. Try dragging the block with the mouse, it can go through the ground easily.  Likely p2 is having trouble.

**Comment by samreid** [comment]
These numbers address the bugs for a variety of mass + volume combinations in buoyancy:basics explore:

<details>

```diff

Subject: [PATCH] Node from the vbox needs to be set to invisible, https://github.com/phetsims/density-buoyancy-common/issues/415
---
Index: js/common/model/PhysicsEngine.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/model/PhysicsEngine.ts b/js/common/model/PhysicsEngine.ts
--- a/js/common/model/PhysicsEngine.ts	(revision c22a525940eb520b74ef717f986c16ae83ab1183)
+++ b/js/common/model/PhysicsEngine.ts	(date 1727965539272)
@@ -379,10 +379,12 @@
 
     body.wakeUp();
 
+    const maxForce = DensityBuoyancyCommonQueryParameters.p2PointerMassForce * body.mass + DensityBuoyancyCommonQueryParameters.p2PointerBaseForce;
+    console.log( DensityBuoyancyCommonQueryParameters.p2PointerMassForce, body.mass, DensityBuoyancyCommonQueryParameters.p2PointerBaseForce, maxForce );
     const pointerConstraint = new p2.RevoluteConstraint( nullBody, body, {
       localPivotA: globalPoint,
       localPivotB: localPoint,
-      maxForce: DensityBuoyancyCommonQueryParameters.p2PointerMassForce * body.mass + DensityBuoyancyCommonQueryParameters.p2PointerBaseForce
+      maxForce: maxForce
     } );
     this.pointerConstraintMap[ body.id ] = pointerConstraint;
     this.world.addConstraint( pointerConstraint );
Index: js/common/DensityBuoyancyCommonQueryParameters.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/DensityBuoyancyCommonQueryParameters.ts b/js/common/DensityBuoyancyCommonQueryParameters.ts
--- a/js/common/DensityBuoyancyCommonQueryParameters.ts	(revision c22a525940eb520b74ef717f986c16ae83ab1183)
+++ b/js/common/DensityBuoyancyCommonQueryParameters.ts	(date 1727965619016)
@@ -110,14 +110,14 @@
   // An amount of force applied to all pointer-mass interactions (e.g. when you grab it with the mouse)
   p2PointerBaseForce: {
     type: 'number',
-    defaultValue: 2500
+    defaultValue: 10
   },
 
   // Adds to the amount of force applied to all pointer-mass interactions (e.g. when you grab it with the mouse), but
   // is this value TIMES the mass's mass value.
   p2PointerMassForce: {
     type: 'number',
-    defaultValue: 0
+    defaultValue: 250
   },
 
   // Stiffness:

```

</details>

How can we ensure that we don't disrupt previously working functionality with a force change like this?

**Comment by zepumph** [comment]
Does the solution in https://github.com/phetsims/density-buoyancy-common/issues/404 completely solve this bug?

**Comment by zepumph** [comment]
Taking a look

**Comment by zepumph** [comment]
I tested after fixing https://github.com/phetsims/density-buoyancy-common/issues/404 by increasing the minimum density allowed for the custom block in B:B:Explore and can no longer reproduce. @Nancy-Salpepi let me know if you can though (in next RC).

**Comment by Nancy-Salpepi** [comment]
This is mostly fixed in rc.2. 
If at min density and min volume, dragging the block to the bottom with `shift` + `down arrow` will still produce sputtering (like in https://github.com/phetsims/density-buoyancy-common/issues/403#issuecomment-2351149353) .

**Comment by Nancy-Salpepi** [comment]
Sorry--I was only looking at the PhET brand sim earlier.
I can still reproduce the sputtering noted in https://github.com/phetsims/density-buoyancy-common/issues/403#issuecomment-2351149353 if I change the density of a mystery block to a small value in Studio (eg. density = 15 and fluid density = 12)

**Comment by samreid** [comment]
@zepumph and I reproduced the sputtering in a few cases. We feel it is part of p2, and we are glad there is no TypeError on the console to go along with it. Since @Nancy-Salpepi did not report the TypeError, this issue seems safe to close.
