### ISSUE TITLE
Able to set Earth's gravity outside of range

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#406]
**Test device**
MacBook Air M1 chip

**Operating System**
14.6.1

**Browser**
Safari 17.6

**Problem description**
For https://github.com/phetsims/qa/issues/1141, when using the query parameter ?gEarth, the possible range is between 9-10. In studio, I am able to set the range for Earth between 0.1 and 25 without getting an error or popup message. 

**Steps to reproduce**
1. In studio go to the Lab screen
2.  Change the value of `buoyancy.global.model.gravities.earth.gravityValueProperty` to 4. 
 
**Visuals**
<img width="672" alt="Screenshot 2024-09-16 at 1 31 24 PM" src="https://github.com/user-attachments/assets/3c3796db-2f84-4f03-9d1b-72ae0cc06c33">

**Comment by zepumph** [comment]
Let's double check with designers, I bet that it would be fine to increase the range of the query parameter. It is also easy to change the numberProperty range just for earth (or make them all different).  Let's talk to designers.

**Comment by zepumph** [comment]
Discussed at design meeting:

Primary reason for gEarth is to be able to set it to 10 for easier mental math. Let's keep the gEarth parameter the same. 

We will just do nothing here. ?gEarth was designed with a different mindset for teachers. PhET-iO often allows more customization   abilities. 

Closing
