### ISSUE TITLE
Min and Max mass listed don't take material into consideration

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density-buoyancy-common#407]
**Device**
Samsung
**OS**
Win 11
**Browser**
Chrome
**Problem Description**
For https://github.com/phetsims/qa/issues/1141
In studio, the mass ranges given for blocks may not take into account the material the block is currently made of. For example, the range for `buoyancy.exploreScreen.view.blockAPanel.massNumberControl.massProperty` is .1-27, but depending on the material is usually smaller than that.

**Visuals**
![setvaluegivenwrong](https://github.com/user-attachments/assets/5436a579-b6be-40a0-b03e-ef22e4cb047b)

**Comment by KatieWoe** [comment]
Actually, this looks like it's already addressed in the examples doc, so it can probably be closed.

**Comment by Nancy-Salpepi** [comment]
I asked about this same thing in the Buoyancy slack channel! 
Here is the response:

Sam Reid
My understanding is that the range shown there (at the bottom) is the total composite range for any material. It is static and unchanging, whereas the enabledRange is able to change. But studio (at the bottom) is supposed to show the static range, not the dynamic enabledRange.


Kathy Perkins
[@arouinfar](https://phetsims.slack.com/team/U5PTARWV7) should weigh in on this question as well.


Amy Rouinfar

Yes, that behavior is fine. The examples clarifies that resultant volume needs to be 1-10L and recommends clients first refer to enabledRangeProperty before setting mass.


Nancy Salpepi

Wondering if that statement in the examples should come before the massProperty phetio IDs or do you think it is OK as is 
[@arouinfar](https://phetsims.slack.com/team/U5PTARWV7)?

**Comment by KatieWoe** [comment]
I noticed this discrepancy with the mystery fluids, which doesn't make sense to me.
![fluidcbounds](https://github.com/user-attachments/assets/47aca8c8-7d60-4668-a3a5-a211d579d6b9)

**Comment by Nancy-Salpepi** [comment]
@KatieWoe your last [comment](https://github.com/phetsims/density-buoyancy-common/issues/407#issuecomment-2353791665) is part of issue #405

**Comment by KatieWoe** [comment]
Ahh, thanks

**Comment by zepumph** [comment]
Ok great. Yes I believe all the actionables are in https://github.com/phetsims/density-buoyancy-common/issues/405 and examples.md. Closing.

**Comment by zepumph** [comment]
Oh, we need to update examples. @arouinfar can you add this sentiment from the [above comment](https://github.com/phetsims/density-buoyancy-common/issues/407#issuecomment-2353772434):

>Wondering if that statement in the examples should come before the massProperty phetio IDs or do you think it is OK as is
[@arouinfar](https://phetsims.slack.com/team/U5PTARWV7)?

**Comment by arouinfar** [comment]
In the above commits, I made minor wording changes and combined the phetioIDs into a single list so folks encounter `massProperty` and `enabledRangeProperty` together.  

Since these are the same commits as the changes in #400, we can close this issue and handle the cherry-picks over there.
