### ISSUE TITLE
Substantial aliasing seen with iOS 18 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#408]
**Test device**
iPad 9th generation

**Operating System**
iPadOS 18

**Browser**
Safari 

**Problem description**
For https://github.com/phetsims/qa/issues/1141 and related to https://github.com/phetsims/density-buoyancy-common/issues/316, after updating my iPad to the latest iOS, the aliasing is much worse for the side of the pool, blocks and shapes.

The pixel density is still listed as a 2 using https://johankj.github.io/devicePixelRatio/. 

**Visuals**
<img width="483" alt="Screenshot 2024-09-17 at 3 43 39 PM" src="https://github.com/user-attachments/assets/669b7f1a-e574-43a1-b3ea-284fb19e6ed7">
<img width="161" alt="Screenshot 2024-09-17 at 3 44 01 PM" src="https://github.com/user-attachments/assets/e3f86b7d-39dc-4475-80dc-dc43f6b9c1e7"><img width="161" alt="Screenshot 2024-09-17 at 3 44 24 PM" src="https://github.com/user-attachments/assets/19ae06d9-b3f2-40db-8960-25d6be09d697">

https://github.com/user-attachments/assets/ba60d763-5f3b-4e20-96db-2e620d42457a

**Comment by Ashton-Morris** [comment]
Test Device
iPad Pro 11 inch 4th gen

OS
Latest

Browser
Safari

I am getting the same aliasing as shown above.

**Comment by samreid** [comment]
@zepumph and I discussed. We feel we have limited options to keep memory within a good boundary to prevent crashing. We searched for webkit changes related to aliasing and did not find anything. It is possible Apple could improve this or make it worse in future versions. Let's check in at our upcoming design meeting.

**Comment by samreid** [comment]
@arouinfar @DianaTavares @zepumph and I discussed this at yesterday's design meeting. The consensus is that we have limited options to keep the memory in a good limit, and the aliasing does not significantly disrupt the usability. We made a note for the postmortem that in future simulations, we will try to explore aspects like memory usage + webgl characteristics in advance where possible. Closing.
