### ISSUE TITLE
Assertion errors when changing density for custom material inside bottle

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#409]
**Test device**
MacBook Air M1 chip

**Operating System**
15.0

**Browser**
Safari 18.0

**Problem description**
For https://github.com/phetsims/qa/issues/1141 in Studio on the Applications screen, assertion errors will pop up in studio and in the console when changing the density of the custom material inside the bottle when the volume is 10.00L. 

**Steps to reproduce**
1. In studio, go to the Applications screen and change the Material to Custom
2. Move the Volume slider thumb to max value
3. Move the Density slider thumb to the right -- errors appear
Following the same steps in the PhET brand sim doesn't cause an error. 

**Visuals**
<img width="637" alt="Screenshot 2024-09-18 at 12 42 05 PM" src="https://github.com/user-attachments/assets/bf1d298e-3640-45a5-94c5-45a5622925f9">
<img width="637" alt="Screenshot 2024-09-18 at 12 42 20 PM" src="https://github.com/user-attachments/assets/8d690837-3507-4678-84ad-875faf27ee70">
<img width="637" alt="Screenshot 2024-09-18 at 12 42 36 PM" src="https://github.com/user-attachments/assets/1abe98a2-65b0-4acc-9aaa-aaeb64bdb285">

**Comment by Nancy-Salpepi** [comment]
also noting that the `customMaterial.densityProperty` for objects is now Read Only, but `buoyancy.applicationsScreen.model.objects.bottle.materialInside.materialProperty.customMaterial.densityProperty` is still readOnly=false.

**Comment by Nancy-Salpepi** [comment]
Also seen using the state wrapper with ?phetioDebug=true

**Comment by zepumph** [comment]
We just need to support the custom mass max in the range for the Property. @samreid can you help me get rid of the `!` in this patch?

```diff
Subject: [PATCH] Node from the vbox needs to be set to invisible, https://github.com/phetsims/density-buoyancy-common/issues/415
---
Index: js/common/view/MaterialMassVolumeControlNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/MaterialMassVolumeControlNode.ts b/js/common/view/MaterialMassVolumeControlNode.ts
--- a/js/common/view/MaterialMassVolumeControlNode.ts	(revision 7cb3bd8a1e1115b5f3652be3508ba1f0d6a2b09c)
+++ b/js/common/view/MaterialMassVolumeControlNode.ts	(date 1727894919678)
@@ -172,7 +172,7 @@
 
     // passed to the NumberControl
     const numberControlMassProperty = new GuardedNumberProperty( massProperty.value, {
-      range: new Range( options.minMass, options.highDensityMaxMass || options.maxMass ),
+      range: new Range( options.minMass, Math.max( options.maxMass, options.maxCustomMass, options.highDensityMaxMass! ) ),
       units: 'kg',
       tandem: massNumberControlContainerTandem.createTandem( 'massProperty' ),
       phetioFeatured: true,

**Comment by samreid** [comment]
`highDensityMaxMass` can be null, so how about a conditional spread?

```diff

Subject: [PATCH] Node from the vbox needs to be set to invisible, https://github.com/phetsims/density-buoyancy-common/issues/415
---
Index: js/common/view/MaterialMassVolumeControlNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/MaterialMassVolumeControlNode.ts b/js/common/view/MaterialMassVolumeControlNode.ts
--- a/js/common/view/MaterialMassVolumeControlNode.ts	(revision c22a525940eb520b74ef717f986c16ae83ab1183)
+++ b/js/common/view/MaterialMassVolumeControlNode.ts	(date 1727923480836)
@@ -172,7 +172,7 @@
 
     // passed to the NumberControl
     const numberControlMassProperty = new GuardedNumberProperty( massProperty.value, {
-      range: new Range( options.minMass, options.highDensityMaxMass || options.maxMass ),
+      range: new Range( options.minMass, Math.max( options.maxMass, options.maxCustomMass, ...( options.highDensityMaxMass === null ? [] : [ options.highDensityMaxMass ] ) ) ),
       units: 'kg',
       tandem: massNumberControlContainerTandem.createTandem( 'massProperty' ),
       phetioFeatured: true,

**Comment by zepumph** [comment]
Thanks. That is excellent. I found another one that is just a bit shorter:

![image](https://github.com/user-attachments/assets/2bc8b3a8-bac0-4397-9d83-6ce998945e51)

**Comment by Nancy-Salpepi** [comment]
Working nicely in rc.2
Closing
