### ISSUE TITLE
Is the js/ directory properly structured?

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#41]
The directory structure for the density/ repo js/ directory does not match the specification in the code review document.  For #5

**Comment by jonathanolson** [comment]
To clarify, I should have:

- density/js/view/compare/CompareScreen.js
- density/js/view/explore/ExploreScreen.js
- density/js/view/mystery/MysteryScreen.js

Correct?

**Comment by samreid** [comment]
The `Screen` subclasses are above model and view, so I think it would be like this:

density/js/compare/CompareScreen.js

etc.

**Comment by jonathanolson** [comment]
Handled in Density/Buoyancy, can you verify?

**Comment by samreid** [comment]
Looks great, thanks!  Closing.
