### ISSUE TITLE
Drag listener isn't interrupted when pressing Reset Boat button

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#410]
*Test device**
iPad 9th generation

**Operating System**
iPadOS 18

**Browser**
Safari 

**Problem description**
For https://github.com/phetsims/qa/issues/1141, on the Applications screen pressing the resetBoatButton with one finger while holding onto the boat or block with the other doesn't interrupt the drag listener. 

**Steps to reproduce**
1. On the iPad go to the Applications screen of Buoyancy and select the Boat scene
2. Grab the Boat with one finger and drag it to the bottom of the pool or in the air and hold it there
3. With another finger press the resetBoatButton

**Visuals**

https://github.com/user-attachments/assets/b4deb548-41cc-412e-8c16-ccc206c39db2

**Comment by zepumph** [comment]
Fixed by interrupting masses on scene reset, Cherry picking now.

**Comment by Nancy-Salpepi** [comment]
All good in rc.2.
Closing
