### ISSUE TITLE
Custom block will jump when slowly dragged upward in pool 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#412]
*Test device**
iPad 9th generation and MacBook Air (m1 chip)

**Operating System**
iPadOS 18  macOS 15.0

**Browser**
Safari 

**Problem description**

For https://github.com/phetsims/qa/issues/1141, in Buoyancy and Buoyancy Basics with ?stringTest=double 
and ?stringTest=dynamic:
On the Explore screen when I grab the Custom block and slowly drag it around, it will repeatedly jump elsewhere and then back again. The Percent Submerged accordion panel needs to be open for this to happen. 

**Steps to reproduce**
In Buoyancy Basics:
1. Add ?stringTest=double to the end of the url
2. For block A, move both slider thumbs to max amounts
3. Open the % submerged panel
4. Grab the block and slowly move it around the pool

**Visuals**
I show the issue with Block B in this video, but it also happens in the One Block scene
https://github.com/user-attachments/assets/860f68ee-6c7a-4f74-b478-0d6eab2258e8

**Comment by samreid** [comment]
Discoveries so far:

0. The problem is easy to reproduce on the buoyancy basics: explore
1. teleport left and up are not being called
2. the barriers look correct
3. Substituting new Text('hello') for the contents of the submerged accordion box avoids the problem
4. The scenery helper does not indicate faulty bounds for the contentst of the submerged accordion box.

Let's check in with @zepumph

**Comment by zepumph** [comment]
When the %submerged was opened, and the block was moving between 100% and less submerged, the panel adjusted width, causing a resize in the barrier which triggered a reset of the mass position from this block 🤯:

https://github.com/phetsims/density-buoyancy-common/blob/289819c99bf316237fede18b5baea84613263e5e/js/common/view/DensityBuoyancyScreenView.ts#L381-L387


We are ready for QA after the above commits.

**Comment by Nancy-Salpepi** [comment]
I am no longer able to reproduce in rc.2
Closing.
