### ISSUE TITLE
Firefox recording wrapper can have graphical glitches

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density-buoyancy-common#413]
**Device**
Samsung
**OS**
Win 11
**Browser**
Firefox
**Problem Description**
For https://github.com/phetsims/qa/issues/1141
When using the recording wrapper on firefox, I've notice blocks of white showing up on the loading screen. I've also seen bits of the nav bar disappear briefly, though I haven't gotten a recording of it. It only seems to appear when the console is open.
**Visuals**
![recordoff](https://github.com/user-attachments/assets/19ee448b-db38-4738-80d3-e8518cf70c78)

**Comment by zepumph** [comment]
Good find! Full screen wrappers have a white background, so the flash is before the sim background draws. I'll update on main, but @samreid and I agree that cherry picking isn't worth it.

**Comment by zepumph** [comment]
@samreid and I don't recommend more changes here. Closing
