### ISSUE TITLE
Panel doesn't resize after removing Density Number control 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#415]
**Test device**
MacBook Air M1 chip

**Operating System**
15.0

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1141, this is minor but in Buoyancy Basics on the Explore Screen, setting `densityNumberControl.visibleProperty` to false doesn't resize the panel. If the `volumeNumberControl.visibleProperty` is set to false, the panel gets smaller.

**Steps to reproduce**
1. In Buoyancy Basics Studio Wrapper set `buoyancyBasics.exploreScreen.view.blockAPanel.densityNumberControl` to false

**Visuals**
<img width="221" alt="Screenshot 2024-09-24 at 7 36 42 PM" src="https://github.com/user-attachments/assets/3916700d-1070-49c8-89e8-b73048413f7b">

**Comment by zepumph** [comment]
taking a look

**Comment by Nancy-Salpepi** [comment]
looks good in rc.2 
Closing
