### ISSUE TITLE
Displaced fluid flickers when amount is 0.1L

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#417]
**Test device**
MacBook Air M1 chip

**Operating System**
15.0

**Browser**
Firefox

**Problem description**
For https://github.com/phetsims/qa/issues/1141#ref-issue-2546446848, in Buoyancy on the Lab Screen, when the fluid displaced is very small, the liquid in the Fluid Displayed panel will flicker. 

**Steps to reproduce**
1. On the Lab Screen, set the Fluid Density and Gravity to max values
2. Change the block material to styrofoam
3. Set the block volume to minimum value

**_From Slack:_**

Diana Lopez
Is better open the issue. Now that I see your setup, I see that is easy for users to get into that situation. And I think that is something easy for developers to "hide" if it can be solved.

**Visuals**

https://github.com/user-attachments/assets/740c4a06-c282-4b30-a9a2-3f1bd5b54b46

**Comment by samreid** [comment]
This helps, but you can still seek out a combination of values that shows flickering.

<details>

```diff

Subject: 
---
Index: js/buoyancy/view/FluidDisplacedAccordionBox.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/buoyancy/view/FluidDisplacedAccordionBox.ts b/js/buoyancy/view/FluidDisplacedAccordionBox.ts
--- a/js/buoyancy/view/FluidDisplacedAccordionBox.ts	(revision 234443020a88a811a2c932ac0fb83d4d6ba2a85d)
+++ b/js/buoyancy/view/FluidDisplacedAccordionBox.ts	(date 1727894297567)
@@ -102,7 +102,9 @@
     }, FluidDisplacedAccordionBox.getBeakerOptions() ) );
 
     displacedVolumeProperty.link( displayedLiters => {
-      beakerVolumeProperty.value = displayedLiters / maxBeakerVolume;
+      const newValue = displayedLiters / maxBeakerVolume;
+      console.log( 'newValue', newValue );
+      beakerVolumeProperty.value = Math.abs( newValue ) > 0.005 ? newValue : 0;
     } );
 
     const numberDisplay = new NumberDisplay( displacedVolumeProperty, new Range( 0, maxBeakerVolume ), {

**Comment by Nancy-Salpepi** [comment]
Looks good to me in rc.2
Closing
