### ISSUE TITLE
Buoyancy shapes reset is slow

### ISSUE THREAD

**Issue by zepumph** [phetsims/density-buoyancy-common#419]

**Comment by zepumph** [comment]
Here @samreid and I improved performance by changing the initial value of mass visibility in the Buoyancy Shapes screen. Please double check that the shapes screen is still behaving well as it pertains to the correct shapes showing at the right times, especially during/after/with reseting all. Please test pressing the button and using Alt+R for reset.

**Comment by KatieWoe** [comment]
Looks ok to me on Win 11 Chrome. I did notice if you press alt (like to press alt r) after having used a drop down it highlights it like you tabbed to it. Is this alright?
![focusshowsup](https://github.com/user-attachments/assets/dc5abf82-d738-4c4d-bb69-c2592833b160)

**Comment by KatieWoe** [comment]
From @samreid on Slack
>This is a known and acceptable behavior at the moment. The closest issue that describes this problem is https://github.com/phetsims/joist/issues/750
