### ISSUE TITLE
Is there a file in assets/ for every resource file in sound/ and images/? Note that there is not necessarily a 1:1 correspondence between asset and resource files; for example, several related images may be in the same .ai file. Check license.json for possible documentation of why some reesources might not have a corresponding asset file.

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#42]
Is there an asset for the single and double cuboid mipmaps?  For #5

**Comment by jonathanolson** [comment]
They were generated, but it adds a lot of overhead (and webgl contexts) to do so on startup, so they were exported to images. Added more documentation above.

Thoughts on whether that's acceptable?

**Comment by samreid** [comment]
Looks great, thanks!  Closing.
