### ISSUE TITLE
Was the README.md generated by `grunt published-README` or `grunt unpublished-README`?

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#43]
From #5, what should the README for density-buoyancy-common look like?  It seems like https://github.com/phetsims/circuit-construction-kit-common/ has a generated one.  The density-buoyancy-common one looks reasonable but doesn't match the code review document so I thought I'd mention it.

**Comment by jonathanolson** [comment]
I usually consider this applying to sim repos. density-buoyancy-common isn't a sim repo (it won't get published on its own), so the CCK-common one looks... incorrect.

Thoughts? Should this be discussed at a dev meeting?

**Comment by samreid** [comment]
counting-common has unpublished-README.  inverse-square-law-common has a custom README.  number-line-common has a custom README.  Hopefully we can decide this on slack, I'll reach out.

**Comment by samreid** [comment]
We agreed it is OK for common code repos to have custom README.md files.  The density-buoyancy-common one looks good.  Back to @samreid to update the code review checklist to indicate that is OK.

**Comment by samreid** [comment]
I noted this in the code review checklist.  Closing.
