### ISSUE TITLE
Does package.json refer to any dependencies that are not used by the sim?

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#44]
For #5, I noticed that density-buoyancy-common and density have different preloads.  Density lists `"../sherpa/lib/poly-decomp-0.3.0.js",` but density-buoyancy-common does not.  Also, I forget if preloads are transitive or have to be mentioned in each file.

**Comment by jonathanolson** [comment]
It's not transitive, I could probably toss the density-buoyancy-common dependencies. For me it's helpful documentation, but I'm curious what your thoughts are. I updated it above, but should we just get rid of them?

**Comment by samreid** [comment]
I would keep them for clarity, keeping in mind one day density-buoyancy-common may have a test harness.  The commit looks good, closing.
