### ISSUE TITLE
Is the LICENSE file correct? (Generally GPL v3 for sims and MIT for common code, see this thread for additional information).

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#45]
For circuit-construction-kit-common, it was decided that repo should be licensed as GPL since it is very sim-specific, I suspect the same applies for density-buoyancy-common.  For #5.

Should we also update the code review document?

**Comment by jonathanolson** [comment]
Sounds good to me, @kathy-phet can you verify?

> Should we also update the code review document?

Also, @kathy-phet, does this sound correct in general?

**Comment by zepumph** [comment]
That seems very reasonable to me! Updated to CRC to note "very sim-like common repos" as GPL v3.
