### ISSUE TITLE
Properties should use type-specific subclasses where appropriate (e.g. BooleanProperty, NumberProperty, StringProperty) or provide documentation as to why they are not.

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#46]
For #5, I saw several places that could use EnumerationProperty, and some that could use Vector2Property.

**Comment by jonathanolson** [comment]
I just fixed up what I was able to find. I definitely didn't see any place where EnumerationProperty could be used that isn't, could you clarify?

Additionally, should we open up a common code issue about Vector3Property, Bounds3Property, and other things not existing that I would have expected would have been kept in-line with the other dimensional equivalents?

**Comment by samreid** [comment]
Could EnumerationProperty be used in cases like these:

```js
this.interiorMaterialProperty = new Property( BOTTLE_INITIAL_INTERIOR_MATERIAL );

new Property( Material.WOOD )

new Property( Gravity.EARTH, {
```

etc?

**Comment by samreid** [comment]
> Additionally, should we open up a common code issue about Vector3Property, Bounds3Property, and other things not existing that I would have expected would have been kept in-line with the other dimensional equivalents?

Perhaps https://github.com/phetsims/axon/issues/221 was intended for that?  I'm OK with any of these plans:
* create an issue for making those
* create those
* just use the ones that exist and not worry about the others at the moment.

What do you recommend?

**Comment by jonathanolson** [comment]
> Could EnumerationProperty be used in cases like these

Not that I'm aware of, custom gravities and materials are created dynamically and seem unsuitable to Enumeration. If there's a way to provide better phet-io support, let me know.

> Perhaps phetsims/axon#221 was intended for that? I'm OK with any of these plans:
> 
> create an issue for making those
> create those
> just use the ones that exist and not worry about the others at the moment.
>
> What do you recommend?

I'd defer to your judgment, I'm fine to not make changes.

**Comment by samreid** [comment]
Thanks, I forgot about the custom ones.  All seems well, closing.
