### ISSUE TITLE
Are `Validator` validation options (`valueType`, `validValues`, etc...) utilized? These are supported in a number of core types like `Emitter` and `Property`. Is their presence or lack thereof properly documented?

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#47]
For #5, I'm seeing several places where validators could be used.  For instance:

```js
    // @public {Property.<Material>}
    this.materialProperty = new Property( config.material, {
      reentrant: true,
      tandem: tandem.createTandem( 'materialProperty' ),
      phetioType: Property.PropertyIO( Material.MaterialIO )
    } );
```

could be:

```js
    // @public {Property.<Material>}
    this.materialProperty = new Property( config.material, {
      valueType: Material,
      reentrant: true,
      tandem: tandem.createTandem( 'materialProperty' ),
      phetioType: Property.PropertyIO( Material.MaterialIO )
    } );
```

However, once we move to TypeScript, that kind of value type checking won't be necessary.  `validValues` should be better supported once we are using EnumerationProperty in #46.  Other places like:

```js
    // @public {Property.<number>} - In m^3 (cubic meters)
    this.volumeProperty = new NumberProperty( config.volume, {
      tandem: tandem.createTandem( 'volumeProperty' )
    } );
```

may wish to specify the range of values?

**Comment by jonathanolson** [comment]
Forgot to tag https://github.com/phetsims/density-buoyancy-common/commit/7e4d0bcaf93a0488a550d44fc36683bd76958f0f, in addition to the above commit (added validations and ranges to things that seemed workable).

How does that look?

**Comment by samreid** [comment]
Excellent, thanks!  Also, I should mention another dev showed me you can comment in a commit thread like I did in https://github.com/phetsims/density-buoyancy-common/commit/7e4d0bcaf93a0488a550d44fc36683bd76958f0f to attach a commit to an issue.  Closing.
