### ISSUE TITLE
What is Engine.Body?

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#53]
For #5, I saw references to `Engine.Body` but I wasn't sure where the implementation is.  Can you clarify?

**Comment by jonathanolson** [comment]
Each engine typically has its own body type (p2.Body is the type for p2.js), so it's just an abstraction over a reference to a body/object that can be provided back to the Engine API.

**Comment by samreid** [comment]
Is there a natural place that could be documented in a comment?  Perhaps in a typedef?

**Comment by jonathanolson** [comment]
Commented in the top of PhysicsEngine.js. A typedef doesn't really... make sense for any code. Presumably this would be doable/enforceable with TypeScript? Thoughts?

**Comment by samreid** [comment]
That seems good for now.  Not sure whether TypesScript would use generics or an interface, etc.  Closing.
