### ISSUE TITLE
Some `@param {function}` could specify types

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#54]
For #5 the code review document recommends specifying types for functions.  For instance, there are several places in the code like:

```js
      // {function} - Given a main value, returns whether it is a custom value or not
      isCustomValue: null,
```

where it doesn't mention the parameter type or

```js
      // {function} - Given a numeric value, creates the corresponding rich object
      createCustomValue: null,
```
where it doesn't indicate the return type.

**Comment by jonathanolson** [comment]
Added docs above.

**Comment by samreid** [comment]
Looks great, thanks!  Closing.
