### ISSUE TITLE
Are any significant chunks of code duplicated? This will be checked manually as well as with https://github.com/danielstjules/jsinspect.

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#56]
From #5, I ran the Webstorm Code=>Analyze => Locate Duplicates and it found numerous duplicated code, like so:

![image](https://user-images.githubusercontent.com/679486/129085577-ad042132-9883-4dab-915b-9e0d4ba4dc24.png)

**Comment by jonathanolson** [comment]
I'd be curious about specific recommendations for avoiding duplicates? Would a utility function help out for the Cuboid/VerticalCylinder getDisplacedVolume case? (They happen to be the same, because they both independently have stepMaximumVolume AND their sides are vertical)

Or are there simplifications I could make to the vertex code?

Let me know if this would be good to discuss/prototype on a call.

**Comment by samreid** [comment]
How about a VerticalMass class that is a parent for both Cuboid and VerticalCylinder?  

Here is some of the duplicated code in the vertex code:

![image](https://user-images.githubusercontent.com/679486/130512857-4b33eddb-1ae5-47a6-8801-a5fb756e8254.png)

What about factoring out position, normal and uv (passing in the other closure variables as regular args)?

Bottle.js has this repeated twice:

```js
      return new Vector2(
        LIP_START + LIP_CORNER_RADIUS * ( 1 + Math.cos( theta ) ),
        LIP_RADIUS + LIP_CORNER_RADIUS * ( -1 + Math.sin( theta ) )
      );
```

This array is duplicated in DensityTableNode and DensityMysteryModel:

```js
[
  Material.WOOD,
  Material.GASOLINE,
  Material.APPLE,
  Material.ICE,
  Material.HUMAN,
  Material.WATER,
  Material.GLASS,
  Material.DIAMOND,
  Material.TITANIUM,
  Material.STEEL,
  Material.COPPER,
  Material.LEAD,
  Material.GOLD
]
```

I'm happy to schedule a call, reach out to me on slack at your discretion.

**Comment by jonathanolson** [comment]
I believe I handled the above cases (and the triangle code definitely should be simpler... it would mainly bottleneck in Buoyancy so I can handle performance issues there).

Can you review, anything else here?

**Comment by samreid** [comment]
TriangleArrayWriter looks great, thanks!  I don't see any more work to be done here.
