### ISSUE TITLE
Are there any `TODO` or `FIXME` or `REVIEW` comments in the code?  They should be addressed or promoted to GitHub issues.

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#57]
From #5, there are currently 20 TODOs.

**Comment by jonathanolson** [comment]
These are exclusively for Buoyancy, I'll handle those when doing work for just Buoyancy.

**Comment by AgustinVallejo** [comment]
TODO's will be handled here: https://github.com/phetsims/density-buoyancy-common/issues/86
