### ISSUE TITLE
Is PhetColorScheme used where appropriate? Verify that the sim is not inventing/creating its own colors for things that have been standardized in `PhetColorScheme`.  Identify any colors that might be worth adding to `PhetColorScheme`.

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#58]
From #5, some colors such as the gravity force differ from the PhetColorScheme. Is this by design?

**Comment by jonathanolson** [comment]
Was decided to use the PhetColorScheme gravitational force colors. The others don't apply, and seem sim-specific.
