### ISSUE TITLE
Should the PhET-iO API be tracked as stabilized?

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#59]
If this simulation is nearing RC.1 for a PhET-iO brand release, then it could be wise to check in its API and add it to phet-io-api-stable so we can detect regressions.  For #5

**Comment by jonathanolson** [comment]
I saw this in the documentation:

> * When phetio structure and metadata for a component have been specified by a designer and implemented in a simulation,
>   the developer should take the following steps:
> 1. Mark the component as `phetioDesigned: true` 
> 2. Mark the package.json phet-io section with `"compareDesignedAPIChanges": true` (if it hasn't already been marked).  
>    This will cause CT to automatically check for regressions in any metadata or tandem structure below the marked element.
>    Don't forget to run `grunt update`
> 3. Generate the API by running `grunt generate-phet-io-api` and commit the file that is output to phet-io/api

It's unclear to me whether I should be marking `phetioDesigned: true` on the full simulation, or if we're relying only on validation of tracked components. There are many different components in the simulation.

What steps should I take to do this? Sounds like it's ready, and I can regenerate the API when needed if further changes happen.

**Comment by samreid** [comment]
If a PhET-iO designer has signed off on the design for the entire sim, then the Sim itself can be marked as `phetioDesigned: true`.  Please see natural-selection/js/natural-selection-main.js for an example.

Please also add it to perennial/data/phet-io-api-stable

**Comment by jonathanolson** [comment]
@arouinfar let me know when the phet-io design for the sim is signed-off!

**Comment by arouinfar** [comment]
@jonathanolson consider this the sign-off for density.

**Comment by jonathanolson** [comment]
Done above, closing!
