### ISSUE TITLE
Check phetioDocumentation coverage?

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#60]
For #5 I observed very few occurrences of `phetioDocumentation`, it was unclear whether this was an oversight or by design.  @jonathanolson can you please review?

**Comment by jonathanolson** [comment]
@arouinfar let me know what should have phetioDocumentation?

**Comment by arouinfar** [comment]
@jonathanolson I made recommendations for phetioDocumentation in https://github.com/phetsims/density/issues/91.
