### ISSUE TITLE
Tandems switch between parameter and option

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#61]
For #5, I noticed tandems move between required parameter and appearing in the options.  The "best practices for Tandems" section indicates that where options are supported, the tandem should be in the options:

https://github.com/phetsims/phet-io/blob/master/doc/phet-io-instrumentation-technical-guide.md#best-practices-for-tandem

For instance:

```js
constructor( materialProperty, massProperty, volumeProperty, materials, setVolume, listParent, tandem, options ) {
```

**Comment by jonathanolson** [comment]
Should be done with the above two commits.

**Comment by samreid** [comment]
Looks good, I didn't see any more occurrences of `, tandem`, closing.
