### ISSUE TITLE
Why are there so many instrumented ProfileColorProperties?

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#65]
At today's design meetings, we were wondering why there are so many ProfileColorProperties showing in Studio? I wasn't sure Material requires value-based serialization, and why the predefined ones cannot use ReferenceIO serialization?  It seems we want to find out if some ProfileColorProperties can be removed from the Studio tree, or, if not, then mark them as phetioReadOnly: true or make sure they cannot be edited.

**Comment by samreid** [comment]
It seems reasonable to keep ProfileColorProperty like `comparingYellowColorProperty` instrumented, since it is part of the Material state.  It should be marked as `phetioReadOnly: true` so it cannot be edited in studio.

Other colors like `radioBackgroundColorProperty` seem like the instrumentation should be removed.

@jonathanolson can you take a first pass?

**Comment by jonathanolson** [comment]
Implemented those thoughts above.

Thoughts on creating a separate name mapping and re-implementing reference serialization locally to avoid the colors being given tandems and showing up in phet-io studio?

**Comment by samreid** [comment]
My understanding from the last meeting was that it would be "good enough" for them to be marked as read-only.  And since you were able to uninstrument some, that is even better.  I do have some hesitation since there are still 32 or so instrumented (read-only) color properties, it is more than I expected.  But I'm not sure how fragile the "a separate name mapping and re-implementing reference serialization locally" would be or how bad it is to have so many colors instrumented.

**Comment by jonathanolson** [comment]
Ok, sounds good! Closing then.
