### ISSUE TITLE
Add separate Properties for visibility of subpanels

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/density-buoyancy-common#66]
We want the users to be able to toggle visibility of subpanels independently, don't link the property

**Comment by jonathanolson** [comment]
I've hooked this up so now you can adjust the visibleProperty on blockAControlPanel or blockBControlPanel. This will be able to force-hide those panels (they are actually shown if that is visible AND the mass is visible in the play area).

@arouinfar can you check and see if this works as desired?

**Comment by arouinfar** [comment]
The `visibleProperty` of the panels is generally behaving as I'd expect, but it would be nice if the panel could resize to fit the contents to avoid empty space:
![image](https://user-images.githubusercontent.com/8419308/140404392-b1faca7b-2a8d-4be0-9f6b-4163ef83318e.png)

**Comment by jonathanolson** [comment]
This was pretty tricky, but should be fixed now (discovered some core layout issues).

**Comment by arouinfar** [comment]
Looks good in master, thanks @jonathanolson
