### ISSUE TITLE
The scale may disappear when pressing "Preview Sim" in studio.

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#67]
A client reported that the scale was disappearing in a studio-customized sim.  I tested by making a short, wide aspect ratio in studio, then pressing "Preview Sim" and confirmed the scale was missing.

![image](https://user-images.githubusercontent.com/679486/147990100-d976c991-4298-48ec-8ed4-23ea2d6912f3.png)

If you resize the window by 1px, the scale returns.  So perhaps there is some layout code that phet-io will have to run when the sim launches.  Or that should just run on every startup.

Studio-customized sims are often embedded in fixed-size-iframes so we will need to get this correct during initialization.

@jonathanolson can you please advise?

**Comment by arouinfar** [comment]
This looks potentially related to https://github.com/phetsims/density/issues/117. Essentially, abruptly changing the aspect ratio of the sim can have odd effects.

**Comment by kathy-phet** [comment]
@samreid - This seems likely a general phet-io issue as you mention, and not Density specific. Can you investigate a solution in phet-io?

**Comment by samreid** [comment]
I considered 3 perspectives for this problem:

* First, I tried calling `resizeBarrier` later, like so:

<details>

```diff

Index: js/common/view/DensityBuoyancyScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/DensityBuoyancyScreenView.js b/js/common/view/DensityBuoyancyScreenView.js
--- a/js/common/view/DensityBuoyancyScreenView.js	(revision 821ecf2aaef402fa0a2f317d391b9f0434a81b86)
+++ b/js/common/view/DensityBuoyancyScreenView.js	(date 1641268219708)
@@ -707,6 +707,8 @@
     if ( !ThreeUtils.isWebGLEnabled() ) {
       ThreeUtils.showWebGLWarning( this );
     }
+
+    setInterval( resizeBarrier, 500 );
   }
 
   /**

```

</details>

In this case, when I run studio, make the sim short and wide, and press "Preview Sim", then when the `resizeBarrier` is called, it updates the position and the scale appears onscreen.

2. I investigated removing the scale's position from the phet-io state in `MassIO`, but was unable to get that working.
3. I'm not sure the desired behavior is clear.  If the designer puts the scale at x=50, then sizes an iframe so the left edge is at x=100 then wouldn't it be the least surprising behavior for the scale to be offscreen?

Also, if the position of "everything else" is saved in phet-io state, but the scale is either (1) updating itself to stay onscreen or (2) omitted from state, then it seems things could get out of sync--with masses that were on the scale when saved, not being on the scale when loaded.

So it seems like this issue warrants further discussion and potentially consultation with @zepumph, @jonathanolson or @arouinfar.

UPDATE: One more solution, let's call it (4) would be to just put the scale at a fixed location independent of the screen aspect ratio.  This would work well and be very simple.  I'm not sure why the design called for it to be all the way to the left when there is a wide aspect ratio like this:

![image](https://user-images.githubusercontent.com/679486/148007924-c322e340-83f1-4e92-9c81-dde72e6afdcb.png)

**Comment by zepumph** [comment]
During a meeting today, we found that this can also happen to the blocks, when their positions are way off the screen, they can get completely lost. @jonathanolson mentioned that this was a separate issue and the he would create another github issue to tackle this.

**Comment by arouinfar** [comment]
@jonathanolson updates to the client guide were made in the above commit, which will require cherry-picking into the release branch.

**Comment by jonathanolson** [comment]
Patched the client guide commit into the release branch. Working on the barrier fix.

**Comment by jonathanolson** [comment]
Barrier fix applied in master and release branch. @arouinfar can you verify?

**Comment by arouinfar** [comment]
@jonathanolson I am unable to lose the scale or blocks when previewing the sim in Studio.

I tested at wide aspect ratios like this.
![Density screenshot](https://user-images.githubusercontent.com/8419308/148323135-e9c91a5a-ee3b-4ecf-85c3-b3f5669d1fac.png)

When clicking "Preview Sim", blocks D & C get pushed into the pool. Blocks E & B also get shifted. Block E is apparently missing, but it reappears when moving block B out of the way.
![Density screenshot (1)](https://user-images.githubusercontent.com/8419308/148323131-8e61bef7-a5d6-4e7b-aa86-91c531cee97c.png)
<img src="https://user-images.githubusercontent.com/8419308/148323349-140d9394-d14f-4275-9ccb-2f3aceb900e9.png" width=200>

I think this behavior is to be expected, and the changes to the client guide made in https://github.com/phetsims/phet-io-client-guides/issues/16 cover this situation. If that's correct, then this issue is ready for verification in the next RC @jonathanolson.

**Comment by jonathanolson** [comment]
Yes, seems unfortunately expected. Marking for QA.

**Comment by KatieWoe** [comment]
I'm seeing the same thing as https://github.com/phetsims/density-buoyancy-common/issues/67#issuecomment-1006255968. Looks fixed. @jonathanolson I'm leaving this open in case we want to address the blocks moving and being in the scale in the future. Otherwise, this can be closed.

**Comment by zepumph** [comment]
@jonathanolson can you comment on why this is marked as fixed-awaiting-deploy? Does it need an MR, or is this old? Should this issue be closed?

**Comment by zepumph** [comment]
We will pick up remaining work in https://github.com/phetsims/density-buoyancy-common/issues/94
