### ISSUE TITLE
Lost enabledRangeProperty from PhET-iO API?

### ISSUE THREAD

**Issue by zepumph** [phetsims/density-buoyancy-common#69]
While working on https://github.com/phetsims/sun/issues/686, I saw that density had lost an enabledRangeProperty from its API. I need to investigate this. It may be purposeful, or it could be a regression from https://github.com/phetsims/scenery/issues/1340

**Comment by zepumph** [comment]
@jonathanolson, I'm trying to hunt down why the PhET-iO is showing a removal of the default 'enabledRangeProperty' for density. I feel like it may have something to do with the AccessibleSlider conversion, but I can't crack it. Did you make any changes to your sim? 



Ahh, I see https://github.com/phetsims/density-buoyancy-common/commit/56093e1a86bc016b2e970b4ce13cc2288fcec9e4, so perhaps this is safe. Can you confirm and potentially update the PhET-iO API for density if all looks good?

**Comment by zepumph** [comment]
@samreid, here is a case where we are now providing our own enabledRangeProperty, should we create a linkedElement for this case? This way we don't lose the reference?

**Comment by zepumph** [comment]
@samreid, does this seem reasonable to add a linkedElement for passed in enabledRangeProperty?

**Comment by samreid** [comment]
Yes, linking to the passed-in one sounds great!  Code changes look good. Closing.
