### ISSUE TITLE
Fuzzing fails an assertion if you resize the window while fuzzing

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#7]
The error is in mobius/js/ThreeIsometricNode.js

```js
    // @public {function} - Ideally should be called whenever the parent/screenView matrix is changed, or any camera
    // change (including zoom or fov).
    this.viewOffsetListener = () => {
      const screenWidth = this.stage.width;
      const screenHeight = this.stage.height;

      if ( screenWidth && screenHeight ) {
        assert && assert( screenWidth === window.innerWidth );
        assert && assert( screenHeight === window.innerHeight );

        this.stage.adjustViewOffset( this.parentToGlobalBounds( new Bounds2( 0, 0, this.layoutBounds.width, this.layoutBounds.height ) ) );
      }
    };
```

I was running http://localhost/main/density/density_en.html?brand=phet&ea&fuzz&debugger and resized the window manually.

**Comment by jonathanolson** [comment]
Removed those assertions. Their purpose was to at one point ensure that we weren't "missing" resizes. Since this is "a resize is queued", I don't think those assertions are needed. Behavior of resizing while fuzzing now works nicely.

**Comment by samreid** [comment]
Tagging for https://github.com/phetsims/density-buoyancy-common/issues/5

**Comment by samreid** [comment]
Working great, thanks!  Closing.
