### ISSUE TITLE
Impossible to grab scale through the readout

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density-buoyancy-common#71]
In Buoyancy, the scales are movable. However, the value text is not pickable, so users cannot grab the scale when the pointer is on top of the readout. The readout takes up a considerable portion of the scale, so this is really inconvenient.

@jonathanolson can you adjust things so that users can click through the readout and grab the scales?

**Comment by arouinfar** [comment]
Tangentially related to https://github.com/phetsims/buoyancy/issues/51

**Comment by jonathanolson** [comment]
Implemented above, can you verify?

**Comment by arouinfar** [comment]
Looks good, thanks!
