### ISSUE TITLE
`model.pool.liquidYInterpolatedProperty` should be phetioHighFrequency: true

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density-buoyancy-common#72]
Noticed in https://github.com/phetsims/buoyancy/issues/51 but applies to both density and buoyancy.

`model.pool.liquidYInterpolatedProperty` should be phetioHighFrequency: true. The other interpolatedProperties are all high-frequency, so it looks like we just missed this one first time around.

**Comment by jonathanolson** [comment]
Implemented, can you verify?

**Comment by arouinfar** [comment]
Thanks @jonathanolson, looks good in master
