### ISSUE TITLE
Setting block `nameProperty` to null leaves behind an artifact

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density-buoyancy-common#73]
Noticed during https://github.com/phetsims/buoyancy/issues/51

There is an artifact left on the block when its `nameProperty` is null.
<img width="72" alt="image" src="https://user-images.githubusercontent.com/8419308/170183937-3f914a16-35d3-4627-8107-f8f2cb0148ab.png">

To reproduce:
1. Navigate to `density.mysteryScreen.model.blockSets.set1.block1B.nameProperty` in Studio
2. Delete the "1B" in the text box
3. Observe artifact

**Comment by jonathanolson** [comment]
I'm hiding labels when the string is empty. `null` shouldn't be possible with a string Property however.

@arouinfar can you see how this behaves now?

**Comment by arouinfar** [comment]
Looks good, thanks @jonathanolson
