### ISSUE TITLE
ComboBox will not accept a DynamicProperty.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/density-buoyancy-common#74]
In https://github.com/phetsims/sun/issues/768, the order of parameters was changed for ComboBox.  That suddenly exposed this problem in MaterialMassVolumeControlNode.ts:

<img width="811" alt="screenshot_1711" src="https://user-images.githubusercontent.com/3046552/175448155-91dd7ce7-4f20-44b8-ab5f-8b041af69781.png">

I worked around it for now by adding a `@ts-ignore`:

```js
    // @ts-ignore TS2345: Argument of type 'DynamicProperty<MaterialEnumValue, Material, Property<Material>>' is not assignable to parameter of type 'Property<MaterialEnumValue>'.
    const comboBox = new ComboBox( comboBoxMaterialProperty, [
```

So there's apparently a problem in the axon Property hierarchy, or some change that was made to the hierarchy. 

I'm not sure why this problem surfaced when it did.  There's no way that it's related to ComboBox. And that doesn't give me a lot of confidence in PhET's transpiler or githooks.

Assigning to @jonathanolson (responsible dev) and @samreid (who recently changed axon Property hierarchy.)

**Comment by samreid** [comment]
The problem is that DynamicProperty no longer extends Property.  I'm not sure how that should work, since not all DynamicProperties are bidirectional/settable.  @jonathanolson should we change `bidirectional` from an option to a subtype?

**Comment by pixelzoom** [comment]
@samreid any thoughts on why this problem didn't surface until quite some time after the Property heirarchy was changed?

**Comment by samreid** [comment]
On June 9 ComboBox was changed from taking IProperty => Property.  At that time, MaterialMassVolumeControlNode was marked with:

```ts
      // @ts-ignore see https://github.com/phetsims/axon/issues/382
      comboBoxMaterialProperty, listParent, {
```

There are 2 other sites marked with `see https://github.com/phetsims/axon/issues/382`.

**Comment by pixelzoom** [comment]
Ah, I see. When I changed the constructor signature for ComboBox, WebStorm "Change signature" relocated the `// @ts-ignore` to the incorrect location.  Instead of keeping it with `comboBoxMaterialProperty`, it moved it above `new ComboBox`.  See e43c9a04.

EDIT: Actually... WebStorm totally removed the `// @ts-ignore` for `comboBoxMaterialProperty` -- how rude!  The other `// @ts-ignore` in https://github.com/phetsims/density-buoyancy-common/commit/e43c9a04ce8556f14059342d77bdb836361b5079 is one that I added.

**Comment by pixelzoom** [comment]
Actually... WebStorm totally removed the `// @ts-ignore` for `comboBoxMaterialProperty` -- how rude!  The other `// @ts-ignore` in https://github.com/phetsims/density-buoyancy-common/commit/e43c9a04ce8556f14059342d77bdb836361b5079 is one that I added.

**Comment by jonathanolson** [comment]
> should we change bidirectional from an option to a subtype?

That sounds possible (they should be bidirectional or not on creation), however unless we use mixins (yuk), I don't see how that would fix the inheritance hierarchy. @samreid would that resolve the issue? If we create BidirectionalProperty (and don't just... duplicate a ton of code), I'm fine with that.

**Comment by samreid** [comment]
In the commit, I annotated the type as `IProperty<T> & ReadOnlyProperty<T>` which roughly means "you can set it" and also "you can link to it".  It seems to be working OK.  If we see many cases like this we can think of a clever nickname and make a type alias for it.  @jonathanolson or @pixelzoom can you please review?

**Comment by pixelzoom** [comment]
A few concerns:

* This feels like a bandaid for ComboBox, when it's a general problem with using an argument of type DynamicProperty.
 
* This same problem can occur for other UI components (e.g. radio buttons) and potentially any constructor/method that has a `Property<T>` parameter.  Are we going to duplicate `IProperty<T> & ReadOnlyProperty<T>` in those cases too? Eagerly or when someone needs it?  

* I worry about the maintainability of `IProperty<T> & ReadOnlyProperty<T>`.  It's not at all obvious what it means ("you can set it" and also "you can link to it").  Perhaps a new type alias should be created to document it.

**Comment by samreid** [comment]
> I worry about the maintainability of IProperty<T> & ReadOnlyProperty<T>. It's not at all obvious what it means ("you can set it" and also "you can link to it"). Perhaps a new type alias should be created to document it.

I added `LinkableProperty` which is defined like so:

```ts
type LinkableProperty<T> = TProperty<T> & LinkableElement;
```

> Are we going to duplicate IProperty<T> & ReadOnlyProperty<T> in those cases too?

I tried it in Checkbox.ts and it seemed to work OK.

> This feels like a bandaid for ComboBox, when it's a general problem with using an argument of type DynamicProperty.

Should we mark DynamicProperty as `implements LinkedElement<ThisValueType>`, and would that address that problem sufficiently?  Please also note the proposal to split DynamicProperty into uni and bidirectional implementations in https://github.com/phetsims/axon/issues/410

**Comment by pixelzoom** [comment]
`LinkableProperty` is an improvement, thanks for doing that.

> Should we mark DynamicProperty as `implements LinkedElement<ThisValueType>`, and would that address that problem sufficiently?  Please also note the proposal to split DynamicProperty into uni and bidirectional implementations in https://github.com/phetsims/axon/issues/410

I'm not familiar with DynamicProperty. Better to ask @jonathanolson.

**Comment by samreid** [comment]
I decided to add `implements LinkableProperty<T>` in DynamicProperty because it is clearer and more discoverable.  In my opinion, this issue is ready to close.  But also OK with me if you want to discuss with @jonathanolson first.

**Comment by pixelzoom** [comment]
Like I said... I'm not at all familiar with DynamicProperty.  So me discussing it with @jonathanolson will not be fruitful.  If you'd like to discuss it with @jonathanolson, go for it.  Otherwise feel free to close.
