### ISSUE TITLE
branch: explicit-member-accessibility

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/density-buoyancy-common#75]
For https://github.com/phetsims/chipper/issues/1258, I ran into serious merge conflicts.  Changes pushed to this branch for @jonathanolson to sort out.

**Comment by pixelzoom** [comment]
@jonathanolson note that this branch may have some `@ts-ignore` directives in Material.ts that will be unnecessary when correctly merged.

**Comment by jonathanolson** [comment]
Got the main part merged in, but need to check for the ts-ignores

**Comment by jonathanolson** [comment]
Handled ignores above, closing.
