### ISSUE TITLE
Dynamically constructed enumerations wind up with the same structure, confusing PhET-iO

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#76]
In https://github.com/phetsims/phet-core/issues/99, we saw that density-buoyancy-common creates material enumerations dynamically.  PhET-iO expects the enumeration structure to be different since it differentiates based on key names.  I'll commit a workaround momentarily.

**Comment by samreid** [comment]
I added a mini-cache for when enumerations happen to be the same.  I'm not sure what the best long term solution is for this sim, since it seems enumerations are being created dynamically (which is less conventional).  @jonathanolson what do you recommend?

**Comment by jonathanolson** [comment]
The workaround seems tricky. Perhaps I could learn more about why it was applied? It seems valid on the client end to create Enumerations dynamically, and I don't see any notes to not do that in Enumeration itself.

**Comment by samreid** [comment]
Perhaps it would be most efficient to get @zepumph recommendation for this first, or feel free to send it back to me if you prefer.

**Comment by zepumph** [comment]
It seems like @jonathanolson was not just dyamically creating these, but also relying on the being able to use them interchangeably. 

>PhET-iO expects the enumeration structure to be different since it differentiates based on key names.

That isn't really true anymore I don't think. We cache based on the enum instance, not key names. What was the trouble? 
https://github.com/phetsims/tandem/blob/b566970b3cfd12bf74abc5af76422988d0b19bda/js/types/EnumerationIO.ts#L23

**Comment by zepumph** [comment]
I see https://github.com/phetsims/phet-core/issues/99, I think the solution is to provide a unique identifier to EnumerationIOs that share the same values. This will make it clearer on the wrapper side and prevent us from such a downstream assertion as in that other issue.

**Comment by samreid** [comment]
> We cache based on the enum instance, not key names. What was the trouble?

Maybe it was that selecting a value from studio would not know which Enumeration to take the value from on the sim side?

> I think the solution is to provide a unique identifier to EnumerationIOs that share the same values.

It's unclear how this should be implemented.  Is the unique identifier the IO Type name?  If so, enumerationIOs that have the same values will have the same identifier.  But this is not invertible--the same identifier could come from different EnumerationIO instances. So I thought the cache could help with that.

**Comment by arouinfar** [comment]
Publishing Density 1.1 with PhET-iO is a current priority, and it's getting very close.

This seems like a blocking issue to me. It's unclear what the next steps are and who needs to be involved, so I'm adding @jonathanolson and @samreid to the assignees.

**Comment by jonathanolson** [comment]
> It seems like @jonathanolson was not just dyamically creating these, but also relying on the being able to use them interchangeably.

I don't think I needed them to be interchangeable. Each control node uses its own enumeration.

Perhaps we could PhetioGroup the enumerations?

> I think the solution is to provide a unique identifier to EnumerationIOs that share the same values.

Would that mean I'd just pass in an incrementing global ID for these?

> Maybe it was that selecting a value from studio would not know which Enumeration to take the value from on the sim side?

But it's being used as `validValues` and with an `EnumerationIO`, so it should have a direct reference to the enumeration being used?

How... would we handle a case (it doesn't happen in this sim) where phet-io could customize a set, and then we need an enumeration based on that new set? What about when keys are inserted in different orders? PhetioGroup?

**Comment by samreid** [comment]
This sim is currently using `EnumerationDeprecated` which would be good to upgrade.

> It seems valid on the client end to create Enumerations dynamically

The way we use Enumerations is typically more static--we treat them more like classes than instances, so it's unconventional for our project to create them dynamically.

Can we try using `string[]` instead of `EnumerationDeprecated` or `EnumerationValue`?

**Comment by jonathanolson** [comment]
I do think the usages of it would work with string[], looking into it.

**Comment by jonathanolson** [comment]
Works nicely, and I'm able to improve the type-checking by using `keyof ( typeof Material )` so that a bunch of casts aren't needed anymore.

@samreid can you review? @arouinfar can you verify that the phet-io behavior of this looks good to you?

**Comment by arouinfar** [comment]
@jonathanolson the updates to `comboBoxMaterialProperty` look good in master. Was anything else changed? I notice that `materialEnumProperty` is still an enum, is that okay? I'm not sure which enums need to be converted to strings.

**Comment by samreid** [comment]
Some questions from code review. Should we change the types like this?

```diff

Subject: [PATCH] Update wording in the validation error message, see https://github.com/phetsims/density/issues/154
---
Index: js/common/model/Material.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/model/Material.ts b/js/common/model/Material.ts
--- a/js/common/model/Material.ts	(revision d88a0f284c00f2fde9ec26f56c5421eb105dead7)
+++ b/js/common/model/Material.ts	(date 1680893750239)
@@ -30,7 +30,7 @@
 const NullableColorPropertyReferenceType = NullableIO( ReferenceIO( Property.PropertyIO( Color.ColorIO ) ) );
 
 type MaterialState = {
-  identifier: null | string;
+  identifier: null | keyof typeof Material;
   name: ReferenceIOState;
   tandemName: string | null;
   density: number;
@@ -524,7 +524,7 @@
     },
     fromStateObject( obj: MaterialState ): Material {
       if ( obj.identifier ) {
-        const material = Material[ obj.identifier as keyof typeof Material ];
+        const material = Material[ obj.identifier ];
         assert && assert( material, `Unknown material: ${obj.identifier}` );
         return material as Material;
       }

```

I also saw this code `this.materialProperty.value = Material[ materialEnum.name as MaterialNonCustomIdentifier ];` which makes me wonder if we would want to change `class MaterialEnumeration extends EnumerationValue {` to strings as well?

**Comment by jonathanolson** [comment]
> @jonathanolson the updates to comboBoxMaterialProperty look good in master. Was anything else changed? I notice that materialEnumProperty is still an enum, is that okay? I'm not sure which enums need to be converted to strings.

It was ONLY `comboBoxMaterialProperty`, that's correct.

**Comment by jonathanolson** [comment]
> if we would want to change class MaterialEnumeration extends EnumerationValue { to strings as well?

I'm fine to leave it as-is, it's more of a constant one. But also fine if it should be strings, seems like it's a question for @arouinfar. It would affect materialEnumProperty (and if we do that, we might want to rename it to materialNameProperty).

**Comment by arouinfar** [comment]
> It was ONLY `comboBoxMaterialProperty`, that's correct.

Good to know, thanks!

>  But also fine if it should be strings, seems like it's a question for @arouinfar. 

To a Studio user, there appears to be very little difference between an enum and a string. I don't see any particular benefit to changing things (again, as someone who only uses Studio).  Unless there are implementation or maintenance benefits to switching to strings, I'd leave it as-is, but I'll let @jonathanolson decide.

> we might want to rename it to `materialNameProperty`

If we go with strings, I like this name.

**Comment by jonathanolson** [comment]
I think it looks good as-is!
