### ISSUE TITLE
TypeScript problem with CuboidIO.toStateObject

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/density-buoyancy-common#79]
Changes to Mass.ts in https://github.com/phetsims/density-buoyancy-common/commit/ca2896ee272512284db4d4405e2fbebc1fccb4df fo https://github.com/phetsims/tandem/issues/278 exposed a problem with CuboidIO.  I added some `@ts-ignore` comments that need to be addressed at some point.  Here's the relevant code in Cuboid.ts:

```typescript
 toStateObject: ( cuboid: Cuboid ): CuboidIOStateObject => {
      const parentStateObject = Mass.MassIO.toStateObject( cuboid );
      // @ts-ignore parentStateObject has type MassIOStateObject, which has no size field
      parentStateObject.size = Bounds3.Bounds3IO.toStateObject( cuboid.sizeProperty.value );
      // @ts-ignore parentStateObject has type MassIOStateObject, which is not the return type of this method
      return parentStateObject;
    },
```

**Comment by pixelzoom** [comment]
@jonathanolson see a similar fix that @samreid applied in https://github.com/phetsims/circuit-construction-kit-common/commit/4215e88ccf24c151111dfc50b8f48c0a95962de8.

**Comment by jonathanolson** [comment]
Thanks! Handled above.
