### ISSUE TITLE
THREE.MeshPhysicalMaterial: 'clearcoatRoughness' is not a property of this material.

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#8]
After fuzzing http://localhost/main/density/density_en.html?brand=phet&ea&fuzz&debugger for #5 about a minute on Mac/Chrome, I saw this error output a few times:

> THREE.MeshPhysicalMaterial: 'clearcoatRoughness' is not a property of this material.  three-r104.js:12858

What is the cause of this? Might it indicate a problem?

**Comment by jonathanolson** [comment]
Interesting, https://threejs.org/docs/#api/en/materials/MeshPhysicalMaterial shows `clearcoatRoughness`, but inspecting build 104 shows `clearCoatRoughness` (slightly different spelling).

Since the appearance currently is fine and it was having no effect, I've removed that option.

**Comment by samreid** [comment]
Looks great, thanks!  Closing.
