### ISSUE TITLE
Use of `children` in GridBox without `autoColumns`

### ISSUE THREAD

**Issue by marlitas** [phetsims/density-buoyancy-common#80]
Coming from https://github.com/phetsims/scenery/issues/1554. @samreid and I saw something that looked potentially buggy in `BouyancyExploreScreenView`

**Comment by jonathanolson** [comment]
What looks buggy here? I see layoutOptions specified for each item.

**Comment by marlitas** [comment]
That's my bad, I didn't see the layoutOptions implementation. We were moving fast. Closing.
