### ISSUE TITLE
Address 20 legacy TODOs

### ISSUE THREAD

**Issue by zepumph** [phetsims/density-buoyancy-common#86]
Instead of pointing to https://github.com/phetsims/tasks/issues/1129.

**Comment by AgustinVallejo** [comment]
Listing the ones that probably don't need their own issue, or possibly need more clarification to understand further steps:

- [ ] // TODO: Ask MK about why the parent options seem to be made optional, this cast shouldn't be needed (@zepumph)
- [ ] // TODO: Ask MK about why the parent options seem to be made optional, this cast shouldn't be needed (@zepumph)
- [ ] // TODO: remove shapeProperty for perf?
- [ ] // TODO: Don't require a reverse here
- [ ] // TODO: reduce these allocations?
- [ ] // TODO: better way to factor this out? (preceeding a bunch of hieroglyphs)
- [ ] // TODO: we'll presumably need to reverse these (more context needed)
- [ ] TODO: What is the most efficient to have the value of V? (more context needed)
- [ ] // TODO: check sign (more context needed, also, which sign?)
- [ ] // TODO: figure out segments improvement

**Comment by samreid** [comment]
This TODO says:

> // TODO: ensure maxWidth for combo box contents so this isn't an issue. How do we want to do layout? https://github.com/phetsims/density-buoyancy-common/issues/86

I confirmed that the contents in that combo box respect the max width:

<img width="504" alt="image" src="https://github.com/phetsims/density-buoyancy-common/assets/679486/e47825df-e3b1-48af-a960-7572c752b84f">

So I will remove that TODO

**Comment by samreid** [comment]
Issues addressed, documented, removed or moved elsewhere. Closing.
