### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#9]
As part of https://github.com/phetsims/density-buoyancy-common/issues/5 I made a recording of memory keep snap shot every minute for the first three minutes using the unmangled built version on Mac/Chrome with ?fuzz.

| Time (minutes)  | Heap Size (MB) |
| ------------- | ------------- |
| 0  | 35.0  |
| 1  | 86.1  |
| 2  | 113.0  |
| 3  | 141.0  |

This seems like it warrants further investigation.

**Comment by jonathanolson** [comment]
Definitely seeing a leak pattern in unbuilt. I'd tested a week or so ago with a built version (no leak), investigating.

**Comment by jonathanolson** [comment]
Looks like we're leaking SVGBlocks somehow.

**Comment by jonathanolson** [comment]
Looks like the leak can be triggered with:

```js
new phet.mobius.NodeTexture( new phet.scenery.Rectangle( 0, 0, 100, 100, { fill: 'red' } ), 100, 100 ).dispose()
```

in the console, but we're disposing the Display. An SVGBlock seems to be created, but not disposed.

**Comment by jonathanolson** [comment]
https://github.com/phetsims/scenery/issues/1265 was causing this, but I was able to avoid it with the above commit for NodeTexture. It looks like the sim is quite stable with memory now, @samreid can you verify?

**Comment by samreid** [comment]
I tested the sim in data-stream-colorized for phet-io and the memory usage was stable.  Closing.
