### ISSUE TITLE
Missing tandems

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/density-buoyancy-common#92]
Relieving TODO's from https://github.com/phetsims/density-buoyancy-common/issues/86

**Comment by samreid** [comment]
All 3 simulations are now launching in phet-io brand with validation enabled and no tandems are reported as missing. There are no TODOs listed for this issue, and none of the TODOs in https://github.com/phetsims/density-buoyancy-common/issues/86 refer to missing tandems. Closing.
